### ISSUE TITLE
when app in background then local notifacation not showing

### ISSUE THREAD

**Issue by heaveninfosoft** [MaikuB/flutter_local_notifications#1323] opened 2021-10-01 13:36 UTC
App works
1. when app open
2. when app closed

App not works
1.when app killed(app killed from recent apps)  

in short app when in background not showing notifacation but the notification which supposed to show in background that show when we open app

**Comment by MaikuB** [comment] 2021-10-05 09:58
The info you've provided isn't sufficient and bug reports should use the bug report template. Please make sure to use this or this will be closed

**Comment by MaikuB** [comment] 2021-10-30 00:50
Closing as there's been no further updates and lack of minimal app to reproduce the problem. Feel free to re-open if you're able to do so but please ensure you clearly communicate what the problem is as I can't tell from what you've written

**Closed by MaikuB** 2021-10-30 00:50 UTC
