### ISSUE TITLE
onSelectNotification dismisses ongoing notification

### ISSUE THREAD

**Issue by joshuakoh1** [MaikuB/flutter_local_notifications#749] opened 2020-08-10 12:48 UTC
Hello,

It seems that if I tap on an ongoing notification, it opens the app but also dismisses the ongoing notification. Which defeats the purpose of it being ongoing. Is there a way to preserve the notification while also opening the app?

```
Future selectNotification(String payload) async {
  if (payload != null) {
    debugPrint('notification payload: ' + payload);
  }
}

```
Thanks!

**Comment by MaikuB** [comment] 2020-08-11 08:59
To confirm
1. are you running this on Android?
2. are you observing this behaviour in your own app or did you confirm there's an issue via a minimal app (e.g. the example app in the repo)?

**Comment by MaikuB** [comment] 2020-08-18 07:48
Closing due to lack of further information. If you have more info, then please file a bug a report and make sure to first check the example app and then provide a link to a repository with a minimal app that can reproduce the problem

**Closed by MaikuB** 2020-08-18 07:48 UTC
