### ISSUE TITLE
change applicationId on Android

### ISSUE THREAD

**Issue by yegenpres** [MaikuB/flutter_local_notifications#1581] opened 2022-05-01 09:45 UTC
If try to change applicationId on Android project plugin doesn't work, show issue attacked on bottom.
Doesn't meter change applicationId manual or by different package - the same issue. Haw solve this problem?

PlatformException (PlatformException(error, Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setSmallIcon(FlutterLocalNotificationsPlugin.java:304)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:215)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:1009)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:1347)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:1226)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by yegenpres** [comment] 2022-05-12 12:13
I just comped code from example main fail on plugin repository to my project, and when I try to invoke method _showNotification and this exception received. 
When I copied this example code on clear project special for test, it works good. I am sure it something wrong with configs in android folder.

**Comment by yegenpres** [comment] 2022-05-13 23:15
https://github.com/yegenpres/issue_notification

Here is example where you can get this issue. Just run app on Android and push first button.

**Comment by yegenpres** [comment] 2022-05-13 23:16
> If my guess on what you're trying to describe here is right, this would expected as from what I understand, changing the package id can result in the resource IDs being changed. However, it's not absolutely clear to me what you tried doing so can you be more explicit on the steps to reproduce the issue here?

https://github.com/yegenpres/issue_notification

Here is example where you can get this issue. Just run app on Android and push first button.

**Comment by MaikuB** [comment] 2022-05-19 02:21
Cannot run the example you've provided as there are dependencies there that can't be resolved. Could you update this so it provides the bare minimum needed to reproduce the issue? Also is your issue happening on debug build or release builds only? Asking as if it's a release build issue then that's because the release build configuration hasn't been done properly

**Comment by yegenpres** [comment] 2022-05-19 12:27
> Cannot run the example you've provided as there are dependencies there that can't be resolved. Could you update this so it provides the bare minimum needed to reproduce the issue? Also is your issue happening on debug build or release builds only? Asking as if it's a release build issue then that's because the release build configuration hasn't been done properly

It is ready for tuning, I forgot remove one local dependency. Issue happening on both builds.

**Comment by MaikuB** [comment] 2022-05-26 11:49
Is the error you shared actually what you get? If so, could share the output of running `flutter doctor -v`? For me, I'm seeing the following

```
/MethodChannel#dexterous.com/flutter/local_notifications( 6610): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Intent.setAction(java.lang.String)' on a null object reference
E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:192)
E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:1013)
E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:1354)
E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:1230)
E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at android.app.ActivityThread.main(ActivityThread.java:7839)
E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
D/EGL_emulation( 6610): app_time_stats: avg=1145.05ms min=6.61ms max=2283.49ms count=2
```

This is something that has been raised but I don't recall others sharing a way to reproduce this so good that there's something provides on this now

**Comment by yegenpres** [comment] 2022-05-27 12:34
But haw can I fix that, I don’t understand.

Чт, 26 мая 2022 г. в 13:49, Michael Bui ***@***.***>:

**Comment by yegenpres** [comment] 2022-05-27 12:37
> Is the error you shared actually what you get? If so, could share the output of running `flutter doctor -v`? For me, I'm seeing the following
> 
> ```
> /MethodChannel#dexterous.com/flutter/local_notifications( 6610): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Intent.setAction(java.lang.String)' on a null object reference
> E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:192)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:1013)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:1354)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:1230)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at android.os.Handler.handleCallback(Handler.java:938)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at android.os.Handler.dispatchMessage(Handler.java:99)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at android.os.Looper.loopOnce(Looper.java:201)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at android.os.Looper.loop(Looper.java:288)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at android.app.ActivityThread.main(ActivityThread.java:7839)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at java.lang.reflect.Method.invoke(Native Method)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> E/MethodChannel#dexterous.com/flutter/local_notifications( 6610):       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
> D/EGL_emulation( 6610): app_time_stats: avg=1145.05ms min=6.61ms max=2283.49ms count=2
> ```
> 
> This is something that has been raised but I don't recall others sharing a way to reproduce this so good that there's something provides on this now

It the same problem what I got, to reproduce that it will be enough create new project with Local notification plugin and change aapplicationid manualy or by editing plugins.

**Comment by MaikuB** [comment] 2022-05-28 01:32
> It the same problem what I got, to reproduce that it will be enough create new project with Local notification plugin and change aapplicationid manualy or by editing plugins.

Please confirm exactly what issue you're having then as this is different to what you originally posted. Are you absolutely sure this is the issue? If so then please provide evidence of this as what you've provided doesn't prove that it is to do with changing the app id. I've just tried this myself with another repository On the [main branch](https://github.com/MaikuB/changeAppIdTest/tree/main) was the original code where notification works when i tap on the first button. On [this branch](https://github.com/MaikuB/changeAppIdTest/tree/changeAppId) the app id was then changed using a package and the notification still works

**Comment by yegenpres** [comment] 2022-05-31 16:01
I will check, I got the same issue like you 100%. Stack trace early was a little different but after updates package issue stayed the same but error message become a different a bit. So I have the same problem which  resolved by the same steps.
It is very strange, may be You have idea what is the reason of this issue?

`PlatformException (PlatformException(error, Attempt to invoke virtual method 'android.content.Intent android.content.Intent.setAction(java.lang.String)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Intent.setAction(java.lang.String)' on a null object reference
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:192)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:1013)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:1354)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:1230)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
))`

**Comment by yegenpres** [comment] 2022-05-31 16:02
Really, now issue disappeared after latest updates, but in old project problem still appear, and don't know haw to fix.

**Comment by MaikuB** [comment] 2022-06-01 12:31
From what I could tell, this is because you've misconfigured your app when comes to deep linking in the manifest file. Refer to the Android docs and/or the docs for Firebase dynamic links. I don't use either so you'll need to more investigation on this but at leas the docs point out that you be having a separate intent filter. You haven't done this, instead you modified the existing intent filter use to identity the main activity used to launch the app. This prevents any library from finding how the details needed to launch an app in response to an action and therefore leads to the exception being reported by the plugin

**Comment by MaikuB** [comment] 2022-06-13 05:10
Closing this as there's been no evidence to show that there's an issue with the plugin itself. If you believe there's an issue please ensure you provide more detailed info that demonstrates this and the actual steps to reproduce the issue given the steps you originally provided don't lead to a problem

**Closed by MaikuB** 2022-06-13 05:10 UTC
