### ISSUE TITLE
Problem when clicking scheduled notification and callback had been looping.

### ISSUE THREAD

**Issue by edwardmelody** [MaikuB/flutter_local_notifications#182] opened 2019-03-12 18:13 UTC
If application is **not running**, then user tap the notification by scheduled notification.
After the application has launched. The callback of that notification had been looping.

**Comment by MaikuB** [comment] 2019-03-17 19:45
There's an example application for this plugin and it doesn't exhibit the problem you're reporting. I'd suggest you look at how you structured the code around calling this plugin. Note that for the case of making sure the callback is triggered when the app isn't running relies on calling the `initialize` method. Sounds like you may have a scenario where you are calling it multiple times or there is another issue within your app

**Comment by MaikuB** [comment] 2019-05-20 12:04
Closing due to lack of further respond. Feel free to re-open if you still have an issue but be good if you could attach or link to code that could be used to reproduce the problem

**Closed by MaikuB** 2019-05-20 12:04 UTC
