### ISSUE TITLE
Enable user to change the notification sound ?

### ISSUE THREAD

**Issue by harryandroiddev** [MaikuB/flutter_local_notifications#1789] opened 2022-11-15 08:02 UTC
As i have seen in whats app that user can change the sound of the notification in the settings , but in this package there is no feature to support this , i request you to add this functionality to change the sound of the notification as of users' s choice .

**Comment by MaikuB** [comment] 2022-11-19 08:34
Duplicate of #1784 so closing. Do not spam to ask the spam. Thanks

**Closed by MaikuB** 2022-11-19 08:34 UTC
