### ISSUE TITLE
Swing up on heads-up notifications 

### ISSUE THREAD

**Issue by Jate1601** [MaikuB/flutter_local_notifications#320] opened 2019-09-16 18:21 UTC
**Describe the bug**
Swiping towards the top of the screen when the heads-up notification is shown, sends the notification to the notification menu of the device. Launching new notifications stop showing as a heads-up notification until restarting the application, even after dismissing it from the dropdown menu

**To Reproduce**
Press on one of the buttons to summon the notification
Swipe UP to dismiss it
Dismiss it from the dropdown
Repress one of the buttons

**Expected behavior**
Swiping left or right on the notification dismisses it completly, but new notifications dont show.

    Future<void> _showNotification() async{ 
       var androidPlatformChannelSpecifics = AndroidNotificationDetails( 
         'channel_id', 'channel_name', 'description', importance: Importance.Max, priority: Priority.High  , ticker: 'ticker'); 
       var IOSPlatformChannelSpecifics = IOSNotificationDetails(); 
       var platformChannelSpecifics = NotificationDetails( 
         androidPlatformChannelSpecifics, IOSPlatformChannelSpecifics); 
       await flutterLocalNotificationsPlugin.show( 
         0, notifications.heads_up, notifications.notification, platformChannelSpecifics, payload:'item x'); 
     } 

    IconButton( 
       icon: Icon(Icons.notifications), 
       onPressed: () async{ 
         await _showNotification(); 
       }, 
     ), 
  
     FloatingActionButton( 
       child: Icon(Icons.notifications), 
       onPressed: () async{ 
         await _showNotification(); 
       }, 
     )

**Comment by MaikuB** [comment] 2019-09-17 08:07
Sorry I'm having trouble understanding the issue here perhaps a video here would help with a description of it. Also what device are you testing on?

Part of the confusion is that in the description of the bug you talk about how notifications stop showing until app is restarted but expected is for notifications to not show after being dismissed. Swiping left or right to dismiss a notification isn't suppose to prevent further notifications from showing

**Comment by Jate1601** [comment] 2019-09-17 09:20
https://drive.google.com/open?id=11AcjZ1dzdGfYb0fKfMAlCOgSZuJorYP3
Open the link above to see a recording of the issue. 

To clarify, the idea is that you should always get a heads-up notification when pressing the buttons. Even after dismissing, the only time you should not get one is when one is still active either on screen or in the dropdown menu. As shown in the recording, the notification does not appear as a heads-up notification after swiping up to dismiss it.

**Comment by MaikuB** [comment] 2019-09-17 11:01
Thanks, the video makes it a lot clearer now. So if it looks like if the notification is dismissed by pulling down the notifications drawer, triggering a notification no longer displays a heads-up notification. I've tried to reproduce this on my Pixel 2 XL but don't run into the same issue. As such I would think this is device specific. 

I don't think it's an issue with the plugin either as it simply calls the platform's notification APIs. I would suspect that if you were to create a brand new Android app (i.e. not a Flutter one) with code for displaying notifications that you would run into the same issue on the devices. It'd be worth seeing if you run into the same issue in that scenario on those devices

**Comment by vruss** [comment] 2019-09-17 13:40
> So if it looks like if the notification is dismissed by pulling down the notifications drawer

I think the notifications break after they are simply "hidden" by pulling up.

**Comment by Jate1601** [comment] 2019-09-19 06:56
https://github.com/Jate1601/Notification/tree/notification_counter

The above link is the Branch for the most "clear" view of the issue. I have tried with multiple VM's and the issue remains, including a Pixel 2XL so I reckon there is something wrong with my code.

**Comment by MaikuB** [comment] 2019-09-19 07:47
Haven't gotten to run it yet but a quick glance would indicate your app isn't using AndroidX and that's required

**Comment by Jate1601** [comment] 2019-09-19 10:59
I tried to implement AndroidX by creating a brand new project. However this did not work, and there are some red squigly lines within app/build.gradle , but they dont stop the compilation of the code.

https://github.com/Jate1601/Notification/tree/androidXtest

**Comment by MaikuB** [comment] 2019-09-20 11:51
Unless I'm doing something different, I can't reproduce the issue. Triggered a notification, pulled down the notification drawer and dismissed the notification with the expectation that the next one wouldn't result in a heads-up notification displayed. The next one still appeared as one. Wonder if there's a problem with your Android SDK installation. Have you tried creating a normal Android app like I mentioned in one of my previous responses to see what happens?

**Comment by MaikuB** [comment] 2019-09-20 11:56
Forgot to mention whilst I did see squiggly lines in build.gradle, they weren't red. Not sure if it's to do with the colour scheme I'm using. They all seemed to around not targeting the latest SDK and how there were newer versions of the dependencies being referenced

**Comment by Jate1601** [comment] 2019-09-20 12:02
It sounds like you are actually dismissing the notifcation instead or putting it aside for later. Swiping up on a android based system useally sends the notification into the dropdown menu, where you can later dismiss it by either pressing it or swiping it to the sides. 
![Example](https://user-images.githubusercontent.com/54976072/65325466-3830e900-dbaf-11e9-9aa4-293ce79ad613.png)

**Comment by MaikuB** [comment] 2019-09-20 12:25
Ah yes you're right. Though from what I've seen and tried now, this isn't an issue to do the plugin as  I tried creating a normal Android app and the same behaviour occurs. I suspect you've come across a gesture for controlling notifications that may not have been documented well or not widely known. As such I'm closing this issue

**Closed by MaikuB** 2019-09-20 12:25 UTC
