### ISSUE TITLE
onDidReceiveNotificationResponse doesn't seem to automatically fire in full-screen notificaiton

### ISSUE THREAD

**Issue by fulanpiet** [MaikuB/flutter_local_notifications#1758] opened 2022-10-14 23:33 UTC
Since upgrading to version ^11.0.0 from ^3.0.2 I am encountering a problem that the callback function `onDidReceiveNotificationResponse` is not firing automatically when showing full-screen notification. It only fires when I tap on the notification. In version ^3.0.2 I used the `onSelectNotification` callback function and it was called automatically when the screen is off and the notification is showing. Based on the documentation I expect this should still be working with version ^11.0.0. Instead, although the screen gets turned on and my app is opened, the callback function does not get called unless I 'manually' tap on the notification.

Steps to reproduce (I am using Android Alarm Manager Plus plugin to schedule notification):

1. Initialize local notification plugin with `onDidReceiveNotificaitonResponse` callback. Push a new 'alarm page' in this callback, so that when this callback is called, the app will end up showing this page instead of staying on the home/initial page.
2. Schedule an alarm to show a notification with full-screen set to `true`
3. Kill the app and turn the phone screen off
4. Wait until alarm fires

Expected result: screen turns on, app is opened, home page is briefly shown and immediately followed by the 'alarm page'.
Actual result: screen turns on, app is opened and stays on the home page. Only when notification is tapped is the 'alarm page' shown.

**Comment by fulanpiet** [comment] 2022-10-16 21:35
Upon further investigating, seems to have to do with initializing the plugin (calling `initialize()`) in a background isolate (as result of android alarm plugin firing) as well as in the main isolate. I will try to confirm this analysis and will close this issue if it is indeed the case. It is, however, still a mystery to me as it did seem to work with the older version of the plugin.

**Comment by fulanpiet** [comment] 2022-10-23 21:51
I can confirm that the 'first' call (if the app has been killed before the alarm fires) to `initialize()` function of the plugin is done in an Isolate where the callback function of Android Alarm Manager Plus plugin lives. When the screen finally turns on and the app is opened, I can see that the app is running on another Isolate and is thus calling `initialize()` from that Isolate.

However the call to `initialize()` from the app doesn't seem to trigger `onDidReceiveNotificationResponse`, which leads to the app failing to identify the 'payload' of the notification. This behavior is not expected as the documentation mentions that the plugin treats 'full screen notification' as if the notification has been tapped. In that case, `onDidReceiveNotificationResponse` should be triggered upon calling to `initialize()`, enabling the app to read the payload of the notification and act accordingly.

And as I mentioned before that this was working with an older version of the plugin, can you perhaps look into this and confirm or deny whether this issue is indeed introduced in version newer than ^3.0.2?

**Comment by MaikuB** [comment] 2022-10-26 08:17
Thanks for sharing the info around your investigation as I did see that the example app works with firing the callback. As for if changes in the plugin broke the functionality, the answer is no. However, the callback works has fundamentally remained the same. With this in mind, I believe your change is more likely to do with Flutter brought changes to do with [this](https://docs.flutter.dev/development/platform-integration/android/plugin-api-migration) that affected how plugins work in general. A similar issue was raised in https://github.com/MaikuB/flutter_local_notifications/issues/1730. The person who reported this issue submitted a PR at https://github.com/MaikuB/flutter_local_notifications/pull/1744 but it's not something that will be compatible with the changes I'm looking to bring into the plugin (see PR for more details) and they have yet to reply further for ideas on how to tackle it. My suggestion would be you try out a fork of that PR to see if it will solve your issue. I suspect it would and you may need to use the fork in the meantime. The issue as I understand it, is a general one that affects how all plugins with callbacks work

**Comment by MaikuB** [comment] 2022-12-03 01:32
I mentioned something on the other issue at https://github.com/MaikuB/flutter_local_notifications/issues/1730#issuecomment-1335983321. Could you have a read and see if you can help with testing out my hypothesis?

**Comment by MaikuB** [comment] 2023-02-25 08:41
@fulanpiet I'm going to close this as I believe it's an duplicate of #1730. FYI I posted an update at https://github.com/MaikuB/flutter_local_notifications/issues/1730#issuecomment-1445013097, be great if you can help test the changes mentioned

**Closed by MaikuB** 2023-02-25 08:41 UTC
