### ISSUE TITLE
Scheduling notifications

### ISSUE THREAD

**Issue by chethanprabhakar** [MaikuB/flutter_local_notifications#253] opened 2019-06-19 19:16 UTC
Hi,

We are working on an app that requires scheduling both one time (scheduled) and repeat (recurring) notifications. It's set up on the page with a form for users to create a task and opt to be notified.

Once the form is submitted ive set 5 second duration for the notification to show up. However, it doesnt seem to be working as expected. Is there something im missing here?...

Posting piece of code below

Initializing:

```
@override
  void initState() {
    super.initState();
    var initializationSettingsAndroid = AndroidInitializationSettings('icon');
    var initializationSettingsIOS = IOSInitializationSettings(
        onDidReceiveLocalNotification: (id, title, body, payload) =>
            onSelectNotification(payload));
    notifications.initialize(
        InitializationSettings(
            initializationSettingsAndroid, initializationSettingsIOS),
        onSelectNotification: onSelectNotification);
  }
```

Scheduling
```
try {
          _showNotification() async {
            var androidPlatformChannelSpecifics = AndroidNotificationDetails(
                'your channel id',
                'your channel name',
                'your channel description',
                importance: Importance.Max,
                priority: Priority.High,
                ticker: 'ticker');
            var iOSPlatformChannelSpecifics = IOSNotificationDetails();
            var platformChannelSpecifics = NotificationDetails(
                androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
            await flutterLocalNotificationsPlugin.show(
                0, 'plain title', 'plain body', platformChannelSpecifics,
                payload: 'item x');
          }

          _cancelNotification() async {
            await flutterLocalNotificationsPlugin.cancel(0);
          }

          _scheduleNotification() async {
            print('here in one time notification');
            var scheduledNotificationDateTime =
                DateTime.now().add(Duration(seconds: 5));
            var vibrationPattern = Int64List(4);
            vibrationPattern[0] = 0;
            vibrationPattern[1] = 1000;
            vibrationPattern[2] = 5000;
            vibrationPattern[3] = 2000;

            var androidPlatformChannelSpecifics = AndroidNotificationDetails(
              'your channel id',
              'your channel name',
              'your channel description',
              /* icon: 'secondary_icon',
                sound: 'slow_spring_board',
                largeIcon: 'sample_large_icon',
                largeIconBitmapSource: BitmapSource.Drawable,
                vibrationPattern: vibrationPattern,
                enableLights: true,
                color: const Color.fromARGB(255, 255, 0, 0),
                ledColor: const Color.fromARGB(255, 255, 0, 0),
                ledOnMs: 1000,
                ledOffMs: 500 */
            );
            var iOSPlatformChannelSpecifics =
                IOSNotificationDetails(sound: "slow_spring_board.aiff");
            var platformChannelSpecifics = NotificationDetails(
                androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
            await flutterLocalNotificationsPlugin.schedule(
                0,
                'plain title',
                'plain body',
                scheduledNotificationDateTime,
                platformChannelSpecifics);
          }
        } catch (e) {
          print(e.toString());
        }
      } else if (_task_schedule_type == 'Recurring') {
        if (_task_schedule_frequency == 'Hourly') {
          var androidPlatformChannelSpecifics = AndroidNotificationDetails(
              'repeating channel id',
              'repeating channel name',
              'repeating description');
          var iOSPlatformChannelSpecifics = IOSNotificationDetails();
          var platformChannelSpecifics = NotificationDetails(
              androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
          await flutterLocalNotificationsPlugin.periodicallyShow(
              0,
              'repeating title',
              'repeating body',
              RepeatInterval.Hourly,
              platformChannelSpecifics);
        } else if (_task_schedule_frequency == 'Daily') {
          var androidPlatformChannelSpecifics = AndroidNotificationDetails(
              'repeating channel id',
              'repeating channel name',
              'repeating description');
          var iOSPlatformChannelSpecifics = IOSNotificationDetails();
          var platformChannelSpecifics = NotificationDetails(
              androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
          await flutterLocalNotificationsPlugin.periodicallyShow(
              0,
              'repeating title',
              'repeating body',
              RepeatInterval.Daily,
              platformChannelSpecifics);
        }
```

Thank you,
Chethan

**Comment by MaikuB** [comment] 2019-06-19 21:10
Is the on Android? If so, did you follow the steps described in the Android integration section of the readme?

**Comment by chethanprabhakar** [comment] 2019-06-20 02:56
Yes android

I've added the app icon here: android/app/src/main/res/drawable/icon.png

The following is added to AndroidManifest.xml
```
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
<uses-permission android:name="android.permission.VIBRATE" />

        // the following goes under <application...
        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />
        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"></action>
            </intent-filter>
        </receiver>
```

Thanks,
Chethan

**Comment by MaikuB** [comment] 2019-06-20 13:14
What device are you running this on and have you tried cloning the repo to run the example to see if scheduling works on that same device? Note that there are some phones that have different behaviours that may prevent it from working e.g. see https://stackoverflow.com/questions/37171730/alarmmanager-not-working-on-asus-zenfone-2-devices-with-android/40694048

**Comment by chethanprabhakar** [comment] 2019-06-20 14:13
Yes. I have cloned your repo. It works

The issue crops up when I use it in my app. Am i missing something?

Thank You,
Chethan

**Comment by chethanprabhakar** [comment] 2019-06-21 03:23
@MaikuB 
I'm testing with this device

![image](https://user-images.githubusercontent.com/2182800/59895363-ef2b9600-9401-11e9-88b8-ad6ae16d7d70.png)


Thanks
Chethan

**Comment by MaikuB** [comment] 2019-06-21 10:59
> Yes. I have cloned your repo. It works

Did you only check if the apps run or did you check if scheduling works as? The scheduling code you pasted is pretty much copied from the example so the code works fine.

As stated above, there can be issues running on some Android devices due to the restrictions they have place and Xiaomi's devices fall into that category. I suspect you only ran the example app but didn't check the scheduling on the same device as I'm expecting that to fail. As far as I know, there's nothing I can do

**Comment by chethanprabhakar** [comment] 2019-06-21 13:15
> I suspect you only ran the example app but didn't check the scheduling on the same device as I'm expecting that to fail.

scheduling working when i run example app

**Comment by MaikuB** [comment] 2019-06-21 13:19
Will need access to a repository with code that can reproduce the problem

**Comment by michinchin** [comment] 2019-06-21 17:51
I'm having a similar issue trying to create recurring notifications based on multiple days chosen. Works on iOS but not on android:

`  Future<void> _createNotification(LocalNotification n) async {
    final time = Time(n.time.hour, n.time.minute, 0);
    final androidPlatformChannelSpecifics = AndroidNotificationDetails(
      'channel ${n.id}',
      'channel ${n.label}',
      'description',
      importance: Importance.Max,
      priority: Priority.High,
    );
    final iOSPlatformChannelSpecifics = IOSNotificationDetails();
    final platformChannelSpecifics = NotificationDetails(
        androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
    // await _localNotificationsPlugin.show(
    //     idx, 'plain title', '${n.label}', platformChannelSpecifics,
    //     payload: '$time');
    debugPrint('${n.label} ${n.id}');
    final daysChosen = weekdayListFromBitField(n.week.currentBitfield);

    for (final day in daysChosen) {
      final dayValue = _formatDay(day);
      debugPrint('Creating notification for: ${n.id + dayValue.value}');
      await _localNotificationsPlugin.showWeeklyAtDayAndTime(
          n.id + dayValue.value,
          'Time to read!',
          'Devotionals are waiting for you :)',
          dayValue,
          time,
          platformChannelSpecifics);
    }
  }`

**Comment by MaikuB** [comment] 2019-06-21 21:37
@michinchin as above, please provide a link to a repository with a sample app that can reproduce the issue

**Comment by chethanprabhakar** [comment] 2019-06-23 03:27
@MaikuB 
Here's a sample code to reproduce the issue
https://github.com/chethanprabhakar/scheduling

**Comment by MaikuB** [comment] 2019-06-23 03:55
@chethanprabhakar the issue you're having is to do with you've written your code. You call `validateAndSave` but that method only defines other methods to do with showing notifications. It doesn't do anything else. Don't know why you've done it that way, it looks as though you simply copied and pasted the code from the example app into that one method. You may need to spend more time learning Dart.

**Comment by MaikuB** [comment] 2019-06-23 07:42
Closing this as the issue was do how the code was written

**Closed by MaikuB** 2019-06-23 07:42 UTC
