### ISSUE TITLE
onSelectedNotification does not works across isolates on iOS

### ISSUE THREAD

**Issue by Henry-Keys** [MaikuB/flutter_local_notifications#322] opened 2019-09-20 10:30 UTC
I'm using a [push notification data handling plugin](https://github.com/nextbss/flutter-push-notification) i developed to handle silent remote push notifications data.

I use flutter_local_notifications to show a notification after processing the data, this in a background isolate. In the UI isolate, i set the onSelectedNotification callback to navigate to a certain screen when the notification is tapped.

```dart
// Background Isolate
await localNotificationsPlugin.show(
  0,
  notification.body.title,
  notification.body.subtitle,
  platformSpecifics,
  payload: notification.toJsonString(),
);

.....

// UI Isolate
localNotificationsPlugin.initialize(
  initializationSettings,
  onSelectNotification: (payload) => _navigate(payload, navigator),
);
```

Please be aware that these are different instances of the plugin. But, it works great in Android, i saw the Android implementation of *show* method and could conclude that it's because the notification data is passed in an intent.

But it does not works on iOS. I don't know how data passing while showing iOS notifications works, if i did, i would perhaps determine the cause and send a pull request.

Thanks in advance.

**Comment by Henry-Keys** [comment] 2019-09-20 10:40
As a workaround solution, i'm thinking in using SharedPreferences to share the notification payload between isolates.

**Comment by MaikuB** [comment] 2019-09-20 11:49
I believe your issue is a duplicate of https://github.com/MaikuB/flutter_local_notifications/issues/278

**Comment by MaikuB** [comment] 2019-09-20 12:46
Closing this as a duplicate

**Closed by MaikuB** 2019-09-20 12:46 UTC
Labels: duplicate

**Comment by Henry-Keys** [comment] 2019-09-20 12:52
Gotcha!! Thanks!
