### ISSUE TITLE
Scheduled notifications not working after deployed on stores

### ISSUE THREAD

**Issue by macfleid** [MaikuB/flutter_local_notifications#331] opened 2019-09-27 07:24 UTC
Hi,
After many tests i've noticed all my local notifications scheduled are not working after deploying them to the Apple store and Android stores. 
what tests i made : 
- create a scheduled notification on debug mode [Android / iOS works OK]
- create a scheduled notification on build mode and installed manually [iOS ok, Android OK]
- create an instant notification on apk and ipa deployed to the stores [iOS / Android OK]
- **create a scheduled notification on apk and ipa deployed to the stores [iOS not working, Android not working]**

Flutter version in production is 1.5 this can be a because of it but i don't have more ideas about this. 
Is there anything i'm missing ? Thanks in advances.

**Comment by MaikuB** [comment] 2019-09-27 07:34
Sorry don't have ideas at the moment. Have you tried creating a release build and have that loaded on a device to try it (e.g. via testflight for iOS). If you have an Android device, you could try loading the app on a device and look at the logcat logs to see if an error appears

**Comment by macfleid** [comment] 2019-09-27 08:27
Yes, i tried with testflight and no errors in crashlitics. That is just not working when sent on testflight or android store.

**Comment by MaikuB** [comment] 2019-09-27 12:09
It's unlikely you'll see the problem in crashlytics and it make more in the native side. This is why suggested looking at logcat on Android. I believe iOS should have ways to check the device logs via Xcode as well

**Comment by p02rosea** [comment] 2019-09-27 23:56
Hello, I have a similar issue, I tested the local notifications (daily, weekly and squedule) and all of them works perfectly on debug mode, but on release the app crash, it doesn't work. I am testing in Android 9.

**Comment by MaikuB** [comment] 2019-09-27 23:57
@p02rosea so in your case it actually crashes? If so, can you see if adding the Proguard rule mentioned in [this post](https://github.com/MaikuB/flutter_local_notifications/issues/326#issuecomment-536112086) solves the problem? In the meantime, I'm going to see if I can reproduce this

**Comment by p02rosea** [comment] 2019-09-28 00:09
@MaikuB yeah, I just tried that and it seems like it works, at least now it let me set the notification. Thank you so much!

**Comment by MaikuB** [comment] 2019-09-28 01:28
@p02rosea no worries. Would you be able to let me know what rules you have now and what version of the Gradle plugin you were using?

**Comment by MaikuB** [comment] 2019-09-28 01:49
Also I found that having the following in the proguard rules file worked fine (note: this was in the readme)

```
-keep class com.dexterous.** { *; }
```

**Comment by MaikuB** [comment] 2019-09-28 09:19
@macfleid your case seems quite weird to me. Without a sample to reproduce the problem it'll be hard to figure out what the problem might be. I say it's quite weird as it's normally only Android that others have issues with as Proguard rules haven't been configured. Haven't had any other accounts of this issue either. I don't think the fact that you're using Flutter SDK 1.5 would be the issue though you could try upgrading to see if it'll help.

**Comment by macfleid** [comment] 2019-09-30 07:40
@MaikuB Thank you, we are testing it. The thing is, that was working on our first release and then stopped working (i don't know when). 
We are investigating, i'll keep you in touch if we find anything.

**Comment by MaikuB** [comment] 2019-09-30 07:44
Worth checking to see versions of the plugin in your first release compared to now. I noticed your original post doesn't mention the version used

**Comment by MaikuB** [comment] 2019-09-30 07:45
Forgot to add the different versions of the plugin are unlikely to explain the differences in the behaviour you've described though

**Comment by macfleid** [comment] 2019-09-30 07:57
Sorry, 
Our first release was on flutter_local_notifications 0.7.0
Last build runs on 0.8.2

**Comment by MaikuB** [comment] 2019-09-30 12:34
Perhaps worth seeing if the issue you're seeing also occurs in the current version of your app with version 0.7.0 of the plugin. As far as I can tell though, I don't see any changes between 0.7.0 and 0.8.2 that should result in a problem like this.

**Comment by MaikuB** [comment] 2019-10-31 21:25
Closing due to lack of further response and no repro

**Closed by MaikuB** 2019-10-31 21:25 UTC

**Comment by badaween-ahmed** [comment] 2020-01-02 14:02
@MaikuB I also have the same issue, the app worked in debug, release and in a physical device (version ^0.8.4) after deploying on the play store app started to crash, then I updated to version ^0.9.1+1 initialized once inside main.dart and again same issue. I don't know what I am doing wrong?

**Comment by badaween-ahmed** [comment] 2020-01-02 14:33
Sorry, it worked after adding the` proguard-rules.pro` file to `/android/app/`. I copied from the example app is this okay to that? I don't have much knowledge about native development. And I didn't write any native code.

**Comment by MaikuB** [comment] 2020-01-02 19:06
That should be fine
