### ISSUE TITLE
Icon not found only when publishing appbundle

### ISSUE THREAD

**Issue by JCKodel** [MaikuB/flutter_local_notifications#1120] opened 2021-04-11 17:45 UTC
**Describe the bug**
I have a custom icon for the notification that works on almost all devices. Last night, I've formatted an old Moto G 2013 (arm 32) and tried to run my app (from the Google Play), it crashed with this error:

```
FATAL EXCEPTION: main
Process: br.art.code.meucronogramacapilar, PID: 18977
android.app.RemoteServiceException: Bad notification posted from package br.art.code.meucronogramacapilar: Couldn't create icon: StatusBarIcon(pkg=br.art.code.meucronogramacapilaruser=0 id=0x7f060087 level=0 visible=true num=0 )
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1459)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5256)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
```

I tried to run it in both debug and release mode and the error was not triggered.
Tried then generate the appbundles and then installing on the device using bundletool.
The crash was there.

Something in appbundle is messing with the chosen notification icon, for some devices (in this specific case, a XT 1033 (falcon), in pt-BR running Android 5.1).

**To Reproduce**
1. Set a custom notification icon
2. Generate an appbundle
3. Run it on a real device with bundletool

**Expected behavior**
To work, as thousands of other models.

**Comment by MaikuB** [comment] 2021-04-11 21:16
When you say you've tried release mode, does this include trying to reproduce the issue but creating an APK?

**Comment by JCKodel** [comment] 2021-04-11 21:18
> When you say you've tried release mode, does this include trying to reproduce the issue but creating an APK?

`flutter run --release` --> works
`flutter build apk --split-per-abi`, then install the apk --> works
`flutter build appbundle`, then creating apks using bundletool and installing using bundletool --> doesn't work
Installing from Google Play on production --> doesn't work

**Comment by MaikuB** [comment] 2021-04-11 21:43
Thanks. I've tried this with the example app and can't reproduce this. Can you try cloning the repository and creating an appbundle from the example app there as well and see it how it goes? I'm wondering if it's device-specific, if so then it's not something I know how to resolve

**Comment by MaikuB** [comment] 2021-05-08 00:31
Closing this due to lack of further response and haven't been about to reproduce this. Feel free to reopen the issue you can provide a minimal app that can reproduce the issue

**Closed by MaikuB** 2021-05-08 00:31 UTC

**Comment by vladaman** [comment] 2021-05-11 07:19
@MaikuB we are having same issue. This time on Samsung A50. What further details do you need?

**Comment by vladaman** [comment] 2021-05-11 07:27
@MaikuB this seems to be related to packaging / build process and specific phone type. Not to the app directly. Trying to figure out how to solve this and find common reason.
