### ISSUE TITLE
The notification icon is not appearing correctly on schedule

### ISSUE THREAD

**Issue by mdmota** [MaikuB/flutter_local_notifications#947] opened 2020-12-14 11:21 UTC
Flutter 1.22.3
flutter_local_notifications: ^3.0.1+4
Android 10

see attachments(screens, icon png, res folder)

```
 _initializeNotificationsSetttings() async {
    await initializeTimeZOne();
    const AndroidInitializationSettings initializationSettingsAndroid =
    AndroidInitializationSettings('ic_notificacao');

    final InitializationSettings initializationSettings = InitializationSettings(
        android: initializationSettingsAndroid);
    await flutterLocalNotificationsPlugin.initialize(initializationSettings);
  }
```
```
scheduleNotification(NotificationModel dados) async{
    DateTime dataNot = DataUtils.dateStringToDateTime(dados.dtNotificacao);
    String dataFormatada = "${dataNot.year}${DataUtils.twoDigits(dataNot.month)}${DataUtils.twoDigits(dataNot.day)} 08:00:00";

    await flutterLocalNotificationsPlugin.zonedSchedule(
        dados.id,
        Sistema.APP_NAME,
        'Message xxxx x xxxx x xxxxxxxx',
        tz.TZDateTime.parse(tz.local, dataFormatada),
        const NotificationDetails(
            android: AndroidNotificationDetails('so_div_id',
                'so_div_channel', 'AppXXX')),
        androidAllowWhileIdle: true,
        uiLocalNotificationDateInterpretation:
        UILocalNotificationDateInterpretation.absoluteTime);
  }
```
icon png: [link icon png](https://drive.google.com/file/d/1y_CFw_R8FS6O4nlpzt9U5amr6JGCEhtj/view?usp=sharing)
![Screenshot_20201214-080328_One UI Home](https://user-images.githubusercontent.com/21266037/102075507-1ab7f280-3de5-11eb-8c5e-8b72ec1600bb.jpg)
![Screenshot_20201214-080624_One UI Home](https://user-images.githubusercontent.com/21266037/102075510-1b508900-3de5-11eb-8b42-722dfca2e8f5.jpg)
![Screenshot_20201214-080322_One UI Home](https://user-images.githubusercontent.com/21266037/102075512-1be91f80-3de5-11eb-936e-64c5a5027f73.jpg)
![ic_notificacao](https://user-images.githubusercontent.com/21266037/102075524-1f7ca680-3de5-11eb-906b-3cb80a420f4e.png)
![res images](https://user-images.githubusercontent.com/21266037/102075526-20153d00-3de5-11eb-8905-053cd3509f43.png)

**Comment by MaikuB** [comment] 2020-12-14 12:02
If your icon isn't appearing properly then it means you have a configuration issue. Either you haven't provided an appropriate icon (note: using colours can cause issues), or if this is from a doing a release build, then not all of the [release build configuration](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration) and a warning in the readme has been written on this

**Comment by mdmota** [comment] 2020-12-14 12:35
The icon has no colors and is transparent as you can see in the drive link
[https://drive.google.com/file/d/1y_CFw_R8FS6O4nlpzt9U5amr6JGCEhtj/view](https://drive.google.com/file/d/1y_CFw_R8FS6O4nlpzt9U5amr6JGCEhtj/view)

**Comment by MaikuB** [comment] 2020-12-16 08:43
You'll need to at least apply a colour to the bag as even if you get the icon working, it'll look white, which you can verify by updating the example app in this repo to use your icon. When I was warning against using colours, it was because some others had mistakenly applied a coloured background that could lead to a square being shown.

My earlier response also mentions another cause for the problem you're seeing and is the most common cause when it comes to this issue where users of the plugin haven't done all of the release build. This is something you need to check by referring to the documentation that has been linked there and make use of the example to cross-reference. Closing this as there no known issues with the plugin when it comes to this. You're welcome to re-open this issue if you have found a bug and can provide a link to a repository with a minimal app that can reproduce the issue

**Closed by MaikuB** 2020-12-16 08:43 UTC

**Comment by mdmota** [comment] 2020-12-18 12:09
Solved! thanks
