### ISSUE TITLE
zonedSchedule doesn't work with workmanager plugin (release mode)

### ISSUE THREAD

**Issue by Romain-Guillot** [MaikuB/flutter_local_notifications#2243] opened 2024-02-21 15:14 UTC
**Describe the bug**
`FlutterLocalNotificationsPlugin.zonedSchedule` doesn't work if [workmanager](https://pub.dev/packages/workmanager) plugin is also used. Latest version of workmanager tested: 0.5.2 (Sep 28, 2023)

**To Reproduce**
I add the workmanager dependency to the example app: [flutter_local_notifications/example](https://github.com/Romain-Guillot/flutter_local_notifications/tree/master/flutter_local_notifications/example)

[Here is the commit](https://github.com/Romain-Guillot/flutter_local_notifications/commit/ebc469abcc49960949cf2ebeca9f84c20eda31b1).

The app needs to be launched in release mode (in debug mode it works fine).

**Expected behavior**
The following code works without workmanager plugin but doesn't work with the workmanager plugin installed.
```dart
    await flutterLocalNotificationsPlugin.zonedSchedule(
        123,
        'scheduled alarm clock title',
        'scheduled alarm clock body',
        tz.TZDateTime.now(tz.local).add(const Duration(seconds: 5)),
        const NotificationDetails(
            android: AndroidNotificationDetails('alarm_clock_channel', 'Alarm Clock Channel',
                channelDescription: 'Alarm Clock Notification')),
        androidScheduleMode: AndroidScheduleMode.alarmClock,
        uiLocalNotificationDateInterpretation: UILocalNotificationDateInterpretation.absoluteTime);
```

**Sample code to reproduce the problem**
[flutter_local_notifications/example](https://github.com/Romain-Guillot/flutter_local_notifications/tree/master/flutter_local_notifications/example).
The app needs to be launched in release mode (in debug mode it works fine).

**Related issues**  
* #2074 - no solution provided (except removing workmanager)

**Comment by md-rifatkhan** [comment] 2024-02-22 12:44
same problem

**Comment by MaikuB** [comment] 2024-04-13 00:41
I downloaded your fork, bumped the device_info_plus dependency and compileSdk version and built a release APK to put on my Pixel 8 and it works as expected 
https://github.com/MaikuB/flutter_local_notifications/assets/25263378/e7c64a65-4faa-4f38-a460-cea900dd3f77

**Comment by MaikuB** [comment] 2024-06-06 22:04
Closing as the information given didn't reproduce the issue and due to lack of further response

**Closed by MaikuB** 2024-06-06 22:04 UTC
