### ISSUE TITLE
Sound does not play

### ISSUE THREAD

**Issue by momoDragon** [MaikuB/flutter_local_notifications#958] opened 2020-12-28 07:48 UTC
I run the example project from this repo. 

**On Android**
On android emulator there is no notification sound
On Physical device there is no notification sound

**On IOS**
On IOS emulator works perfect for custom and default notification sound

**Comment by faisalmushtaq007** [comment] 2021-01-12 06:54
have you solved this issue?

**Comment by tehsunnliu** [comment] 2021-01-13 14:08
Hi, I'm facing the same issue. After installing the app I found that Sound is disabled in Settings by default, I tried on two physical devices and unfortunately, both are of Xiaomi with the same issue. I found [here](https://github.com/MaikuB/flutter_local_notifications/issues/928), that by default Sounds are disabled in Mi OS and there is no way we can enable it programmatically. 
Hoping to find some solution to this.

**Comment by momoDragon** [comment] 2021-01-13 14:13
I am having inconsistent result, also some others here are facing similar issues. i Guess i will reopen the issue

**Comment by MaikuB** [comment] 2021-01-13 21:18
If you're having issues with sound on your emulator as well then you've got an environmental issue to look into that I can't help. As for physical device, as @tehsunnliu mentioned earlier, there are some manufacturers that don't allow sound to play by default. There isn't anything the plugin can do about that. These are restrictions imposed by them since they've modified the Android OS that it is different than the standard/stock Android OS/experience

You should also check the settings of the emulator and device as the sound volume is separate from the phone ringer that determines if a notification sound should play.

There isn't a bug in the plugin itself around playing around playing with the sound. You can grab one of the official Android notification example apps or write an Android app using Kotlin/Java to compare when it comes playing sound

**Comment by MaikuB** [comment] 2021-01-22 13:19
Closing this based on the response I've given earlier as there isn't anything I've seen that indicates the problem is with the plugin when all it does it call the native APIs as regular Android apps would do

**Closed by MaikuB** 2021-01-22 13:19 UTC
