### ISSUE TITLE
Issue regarding scheduling local notification for multiple days on next coming weekdays

### ISSUE THREAD

**Issue by Afrintaj** [MaikuB/flutter_local_notifications#1046] opened 2021-02-22 04:39 UTC
I am working on a flutter app, I am using flutter_local_notifications for the local notification. Weekly notification is working fine for selecting the multiple days in the present week. Now I want to schedule notifications for multiple days on next coming weekdays like (Monday, Thursday, and Saturday). It's working fine for the present week but for next week on wards all notifications scheduled triggers on same day(example: all scheduled notifications triggers on Monday). I couldn't find any solution to implement.

List<int> dayList = [1,2,3,4,5,6,7]  // ( 1 = Day.sunday, 2 = Day.monday, 3 = Day.tuesday, 4 = Day.wednesday, 5 = Day.thursday, 6 = Day.friday, 7 = Day.saturday)

for (int i = 0; i < dayList.length; i++) {
                                print(
                                    "Unique ID : || ${int.parse(myID + "$i")}");
                                FlutterLocalNotification
                                    .scheduleMultipleDayViseNotification(
                                        uniqueId: int.parse(myID + "$i"),
                                        title: labelNameController.text,
                                        body:
                                            "Your Reminder for ${labelNameController.text}",
                                        hour: int.parse(timeController.text),
                                        min: int.parse(minController.text),
                                        day: Day(dayList[i]));
                              }

static scheduleMultipleDayViseNotification(
      {int uniqueId,
      String title,
      String body,
      Day day,
      int hour,
      int min}) async {
    var time = Time(hour, min, 0);
    var androidChannelSpecifics = AndroidNotificationDetails(
      'CHANNEL_ID 5',
      'CHANNEL_NAME 5',
      "CHANNEL_DESCRIPTION 5",
      importance: Importance.max,
      priority: Priority.high,
    );
    var iosChannelSpecifics = IOSNotificationDetails();
    var platformChannelSpecifics = NotificationDetails(
        android: androidChannelSpecifics, iOS: iosChannelSpecifics);
    // ignore: deprecated_member_use
    await flutterLocalNotificationsPlugin.showWeeklyAtDayAndTime(
      uniqueId,
      title,
      body,
      day,
      time,
      platformChannelSpecifics,
      payload: "${uniqueId}Test",
    );
  }

**Comment by MaikuB** [comment] 2021-02-22 09:01
The code snippets don't tell indicate much. Moreover, you're using a deprecated method that will no longer be supported in the plugin. If you intend to continue using a deprecated method, then you'll need to keep your own fork to look into the issue yourself as these would be removed later on

**Comment by Afrintaj** [comment] 2021-02-22 09:13
Thankyou for the response !!

Can you please suggest me any alternative solution with respect to flutter local notifications.

**Comment by MaikuB** [comment] 2021-02-22 09:17
You either need to use the `zonedSchedule` method that was mentioned in the deprecation warning or look into addressing the issue yourself if you continue to use the deprecated method. Prior to `showWeeklyAtDayAndTime`, no one had reported issues on this besides issues with daylight savings. As such, I'm more inclined to think you have some issue with the logic in the your application e.g. perhaps you have part of the code that reuses the same id

**Comment by Afrintaj** [comment] 2021-02-22 09:51
Thank you for the response

I have already tried with zonedSchedule method, but still I am facing related to triggering notifications after delay of 1 day.

**Comment by MaikuB** [comment] 2021-02-22 12:08
That method has been around for a while and there are no known issues on that so I suspect you still have an issue with your code to look into. If you suspect there's a bug in this then a link to a repository containing a minimal app to reproduce the issue will be needed for it to be investigated further. There's an example app in the repository that can be used to test and modified by forking the repo

**Comment by Afrintaj** [comment] 2021-02-22 13:00
Thankyou, I will check with my code, if same issue arises then, I will share the repository containing minimal app code.

**Comment by Jai05-techie** [comment] 2021-03-01 09:45
Hi @MaikuB 

I am working on ```Flutter app which is like Scheduling meeting and reminder```.

Facing same issue ! 

Case : (Example)

If i schedule Notification for ```(Monday & Tuesday & Wednesday) at 10:00 AM``` for current week notifications triggering properly. But on next week Monday 10:00 AM i should get one notification for Monday but am getting all notifications of (Tuesday & Wednesday) at once. After that Tuesday & Wednesday notification not triggering coz its already triggered on Monday only.

**Comment by MaikuB** [comment] 2021-03-01 10:31
@Jai05-techie which API are you calling?

**Comment by Jai05-techie** [comment] 2021-03-01 12:48
Hi @MaikuB  am using ```flutterLocalNotificationsPlugin.zonedSchedule```.

**Comment by MaikuB** [comment] 2021-03-01 13:30
Which platforms do you see this behaviour happening on and which version of the plugin are you using?

**Comment by Afrintaj** [comment] 2021-03-03 05:38
Hi **@MaikuB**  I tried with flutterLocalNotificationsPlugin.zonedSchedule. but am facing issue with this method.
 
Example : If I schedule notification on Monday 10:00 AM it will trigger scheduled notification on Tuesday 10:00 AM here am attaching example repository https://github.com/Afrintaj/Local_Notification

**Comment by MaikuB** [comment] 2021-03-03 06:45
You left out the crucial parts that were mentioned in the docs for this plugin and the timezone package. The timezone package doesn't know what the local timezone is so you need to specify what that is if you're going to use `tz.local`. Not specifying it leaves it at the default of UTC, which would lead to issues like the one you've described

**Comment by MaikuB** [comment] 2021-03-14 00:19
Thanks @Afrintaj. I'll be closing this then.

@Jai05-techie you're going to need to debug your app for logic issues since @Afrintaj confirmed it works and no one else has reported an issue on this. I've tried to modify the example app to see if I can reproduce this but everything has been working as expected. I don't see any issues in the code for the plugin either. The code is open source so you can see this for yourself

**Closed by MaikuB** 2021-03-14 00:19 UTC
