### ISSUE TITLE
Android Group of notifications

### ISSUE THREAD

**Issue by neestell** [MaikuB/flutter_local_notifications#956] opened 2020-12-25 09:56 UTC
Notifications do not groups with the same `groupKey` and 'setAsGroupSummary=true' flag

**To Reproduce**
1) Create and schedule(**zonedSchedule**) 2  notifications with the same `groupKey`
2) Wait some time

**Expected behavior**
Two notifications are visible in one group

**Actual behavior**
Two separate notifications are visible

Thanks!

**Comment by MaikuB** [comment] 2020-12-26 12:36
Please provide a link to a repository that can reproduce this issue as covered in the original bug report template. You can fork the repo and update the example app as a way of doing this. On that note, grouping has been covered in the example app so if you haven't done so already, I'd suggest cross referencing it with what you've done

**Comment by MaikuB** [comment] 2021-01-01 23:15
Closing since a link hasn't been provided. Feel free to re-open once you have done so

**Closed by MaikuB** 2021-01-01 23:15 UTC
