### ISSUE TITLE
All notifications come at once

### ISSUE THREAD

**Issue by guilhermeeng99** [MaikuB/flutter_local_notifications#770] opened 2020-08-26 14:44 UTC
Hi, thanks for this plugin,
When the phone is in energy saving all the notifications are blocked, but if the user puts in normal mode, all notifications come at once. The same thing happens when the user turns on the phone after a while it was turned off,  the same happens.

**Comment by MaikuB** [comment] 2020-08-27 22:38
I'm assuming you're scheduling notifications and if so what method are you using? Asking as there's a documented caveat in the readme [here](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#recurring-android-notifications).

Regarding the scenario on if the phone is turned on after it's off, if the notification was suppose to appear during the time it was off then that is the expected behaviour

**Comment by MaikuB** [comment] 2020-09-04 22:21
Closing due to lack of further response

**Closed by MaikuB** 2020-09-04 22:21 UTC
