### ISSUE TITLE
custom notification sound did not work on Android

### ISSUE THREAD

**Issue by TristanWYL** [MaikuB/flutter_local_notifications#291] opened 2019-08-13 11:03 UTC
When clicking on the button for scheduling a custom notification, it is expcted to fire the notification along with playing the specified audio file in 5 seconds, and the notification is triggered, but it does not play the specified audio, instead of that the default sound is played.

I have tried the built-in example of this plugin, the custom sound could work. However, when I copy the main.dart to a new flutter project and load the same dependency plugins, it does not work. 

When I tried to dig deeper, I found that when executing this line of code:
`Notification notification = createNotification(context, notificationDetails);`
the argument `notificationDetails` contains a field with the resource id of the specified audio file, but the returned `notification ` has a field "sound" of value "null", I am not sure whether this is normal or not.

Please refer to [https://github.com/TristanWYL/flutter_notification_test.git](url) for the sample code.

It has costed me two days for solving this issue, but still failed. Would appreciate a lot if you could help. Thanks very much!

**Comment by MaikuB** [comment] 2019-08-13 12:46
haven't had a chance to run your app but one thing that stands out looking at your repo is that it looks like your app hasn't been migrated to AndroidX

**Comment by MaikuB** [comment] 2019-08-13 12:48
also should point that if you're on the latest version of Flutter on the stable channel then you should be able to specify the --androidx flag so that the Android app will use AndroidX instead of the old support libraries

**Comment by TristanWYL** [comment] 2019-08-13 13:17
> haven't had a chance to run your app but one thing that stands out looking at your repo is that it looks like your app hasn't been migrated to AndroidX

When I follow steps from flutter official instructions to migrate to AndroidX, it prompted that _No Usages Found in the Project_. I am not sure what this means. After all the migration, the custom notification sound still does not work as expected.

**Comment by MaikuB** [comment] 2019-08-13 13:20
I have found that sometimes that isn't actually accurate and requires a few attempts for it to work. If you look at the build.grade file in your app, it still doesn't use AndroidX (you can compare with the example app). I'd advise also trying to recreate your app with the AndroidX flag

**Comment by TristanWYL** [comment] 2019-08-13 14:24
> I have found that sometimes that isn't actually accurate and requires a few attempts for it to work. If you look at the build.grade file in your app, it still doesn't use AndroidX (you can compare with the example app). I'd advise also trying to recreate your app with the AndroidX flag

I upgraded flutter and recreated a flutter project with --androidx tag. After getting all need plugins and organizing all res files, I started to run the application. However, the notification does show up when I did click on some buttons to schedule one notification. When I set breakpoints the java code, I found `schedule(MethodCall call, Result result)` is called, but the notification never fired. It is so wierd.

**Comment by MaikuB** [comment] 2019-08-13 20:18
Sounds like the manifest file hasn't been edited to include the appropriate permissions and receivers

**Comment by TristanWYL** [comment] 2019-08-14 08:35
> Sounds like the manifest file hasn't been edited to include the appropriate permissions and receivers

Yes, you are right. I did as what you said and it did work by creating a new project with the "--androidx" tag. Thanks very much. However, it brings up another problem, which is that one cannot change the sound dynamically, even with different notification id's for different sounds. The first fired sound would dominate for each installation of the APP when using the "schedule" method.

**Comment by MaikuB** [comment] 2019-08-14 08:38
This is actually the expected behaviour due to how Android works and is mentioned in the API docs the plugin here https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/AndroidNotificationDetails/sound.html

**Comment by TristanWYL** [comment] 2019-08-14 09:10
But I did change the "sound" and "id" of the method "schedule" simultaneously, but only the first fired sound would be played for multiple times. It seems that different id's does not work.

**Comment by TristanWYL** [comment] 2019-08-14 09:12
Do you mean the method "schedule" is only corresponding to one channel, while the id has nothing to do with the channel?

**Comment by MaikuB** [comment] 2019-08-14 09:12
What about the channel ID?

**Comment by MaikuB** [comment] 2019-08-14 09:24
> Do you mean the method "schedule" is only corresponding to one channel, while the id has nothing to do with the channel?

No I'm not, to partially quote the API doc I've written

> For Android 8.0+, this is tied to the specified channel cannot be changed afterward the channel has been created for the first time.

This means the sound is associated with a notification channel. If you're going to post notifications to the same channel, the sound that gets played is from the first notification that created the channel

**Comment by MaikuB** [comment] 2019-08-14 09:31
If you haven't already, it's worth spending a bit of time understanding how notifications work on Android https://developer.android.com/guide/topics/ui/notifiers/notifications

**Comment by TristanWYL** [comment] 2019-08-14 09:38
Hey man, I got you, and what you said is right. I fixed this problem by changing the channel ID. This issue could be well closed. Thanks again. You are so cool!

**Comment by MaikuB** [comment] 2019-08-14 09:39
Thanks for the kind words and glad you were able to sort it out :)
Will close this then

**Closed by MaikuB** 2019-08-14 09:39 UTC

**Comment by guodf** [comment] 2020-01-16 15:51
@TristanWYL Can you give me a successful example? I tried but couldn't succeed? Please help me, thank you!
