### ISSUE TITLE
Fatal Exception on android after removing the library - java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by asiepshtain** [MaikuB/flutter_local_notifications#1794] opened 2022-11-18 16:09 UTC
Our latest build has removed the flutter library, as the version we were using was not compatible with android api 31 and we were no longer using local notifications. We are now seeing mass crash reports ( 97% of users!) with the following issue:

Fatal Exception: java.lang.RuntimeException: Unable to instantiate receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver: java.lang.ClassNotFoundException: Didn't find class "com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver" on path: DexPathList[[zip file "/data/app/~~PUSVNZQbJB1wrFdkL9wSdA==/com.bbumgames.rummystars-Esoy2W8b4RxcPOZq7WlLow==/base.apk", zip file "/data/app/~~PUSVNZQbJB1wrFdkL9wSdA==/com.bbumgames.rummystars-Esoy2W8b4RxcPOZq7WlLow==/split_config.arm64_v8a.apk"],nativeLibraryDirectories=[/data/app/~~PUSVNZQbJB1wrFdkL9wSdA==/com.bbumgames.rummystars-Esoy2W8b4RxcPOZq7WlLow==/lib/arm64, /data/app/~~PUSVNZQbJB1wrFdkL9wSdA==/com.bbumgames.rummystars-Esoy2W8b4RxcPOZq7WlLow==/base.apk!/lib/arm64-v8a, /data/app/~~PUSVNZQbJB1wrFdkL9wSdA==/com.bbumgames.rummystars-Esoy2W8b4RxcPOZq7WlLow==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4726)
       at android.app.ActivityThread.access$1800(ActivityThread.java:310)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2292)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:57
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
       
      
We can't put the library back in (the one we are using can't be uploaded - no api 31 support ) and we don't want to implement a new version (we don't have local notifications anymore) but we can't release a new version because it has a 3% crash free rate.

We need a way to flush all future notifications without the actual library or any other way to prevent the crash?
This came in a very unfortunate time as we are trying to get a version out for black friday, so a prompt reply would be most appreciated. 
Thank you

**Comment by MaikuB** [comment] 2022-11-19 09:20
Can you please elaborate mode on what the Android API 31 issue is? If you want to fix it then you're most likely going to implement Java/Kotlin code specific to and within your own app to flush the notifications. This involves digging understanding how Android's APIs work, digging through the plugin to understand what APIs it uses to schedule notifications and how it saved and loaded notifications for (re)scheduling. The code is open-source so you should be able to dig further on how to do this and something you'd need to invest time to do

**Comment by timobaehr** [comment] 2022-11-20 12:20
**Describe the bug**
If I run the app on Android 6 or Android 7 devices, the app crashes. The user was automatically reported from real users on production version. On Android 13 everything works fine. 

**Affected versions**
Looks like this error came up in v10.0.0 and later. 9.x version works.
I tested:
* 10.0.0 - Crash
* 12.0.3+1 - Crash

**Stacktrace from users**
```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/LocalDateTime;
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedScheduleNotification(FlutterLocalNotificationsPlugin.java)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedSchedule(FlutterLocalNotificationsPlugin.java)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java)
       at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java)
       at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java)
       at io.flutter.embedding.engine.dart.DartMessenger.$r8$lambda$TsixYUB5E6FpKhMtCSQVHKE89gQ(DartMessenger.java)
       at io.flutter.embedding.engine.dart.DartMessenger$$InternalSyntheticLambda$0$ceffc6bae7d364cb48afaf1aaebd60bf9050360d0efb9035ebc54f0851df0a05$0.run(DartMessenger.java)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6410)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
```

**Stacktrace from debug version**
```
Launching lib/main.dart on SGP621 in debug mode...
...
E/MethodChannel#dexterous.com/flutter/local_notifications(22616): Failed to handle method call
E/MethodChannel#dexterous.com/flutter/local_notifications(22616): java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
E/MethodChannel#dexterous.com/flutter/local_notifications(22616): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.initialize(FlutterLocalNotificationsPlugin.java:1499)
E/MethodChannel#dexterous.com/flutter/local_notifications(22616): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:1293)
E/MethodChannel#dexterous.com/flutter/local_notifications(22616): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#dexterous.com/flutter/local_notifications(22616): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#dexterous.com/flutter/local_notifications(22616): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#dexterous.com/flutter/local_notifications(22616): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
E/MethodChannel#dexterous.com/flutter/local_notifications(22616): 	at android.os.Handler.handleCallback(Handler.java:739)
E/MethodChannel#dexterous.com/flutter/local_notifications(22616): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/MethodChannel#dexterous.com/flutter/local_notifications(22616): 	at android.os.Looper.loop(Looper.java:234)
E/MethodChannel#dexterous.com/flutter/local_notifications(22616): 	at android.app.ActivityThread.main(ActivityThread.java:5526)
E/MethodChannel#dexterous.com/flutter/local_notifications(22616): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#dexterous.com/flutter/local_notifications(22616): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/MethodChannel#dexterous.com/flutter/local_notifications(22616): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E/flutter (22616): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, java.lang.Integer cannot be cast to java.lang.Long, null, java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
E/flutter (22616): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.initialize(FlutterLocalNotificationsPlugin.java:1499)
E/flutter (22616): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:1293)
E/flutter (22616): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter (22616): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (22616): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter (22616): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
E/flutter (22616): 	at android.os.Handler.handleCallback(Handler.java:739)
E/flutter (22616): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/flutter (22616): 	at android.os.Looper.loop(Looper.java:234)
E/flutter (22616): 	at android.app.ActivityThread.main(ActivityThread.java:5526)
E/flutter (22616): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (22616): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/flutter (22616): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E/flutter (22616): )
E/flutter (22616): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter (22616): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
E/flutter (22616): <asynchronous suspension>
E/flutter (22616): #2      AndroidFlutterLocalNotificationsPlugin.initialize (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:151:12)
E/flutter (22616): <asynchronous suspension>
E/flutter (22616): #3      initLocalNotifications (package:energy_tracker/main_local_notification.dart:44:3)
E/flutter (22616): <asynchronous suspension>
E/flutter (22616): #4      main (package:energy_tracker/main.dart:126:5)
E/flutter (22616): <asynchronous suspension>
```

**To Reproduce**
1. Try to run the app
2. See crash, freezes on splashscreen

**Comment by timobaehr** [comment] 2022-11-20 21:38
https://stackoverflow.com/questions/28745205/cannot-resolve-symbol-java-time-localdate-error-in-android-studio

**Comment by MaikuB** [comment] 2022-11-21 05:38
@timobaehr your issue would indicate that you didn't follow the Android setup steps that were required from version 10 onwards and called out as the first breaking change in the changelog for the 10.0 release

**Comment by MaikuB** [comment] 2022-12-03 00:09
Closing this as this is something the OP will need to follow up to to try solve

**Closed by MaikuB** 2022-12-03 00:09 UTC
