### ISSUE TITLE
In Redmi devices notification panel which show first time when notification coming not show.But Samsung e.x everyting is ok.

### ISSUE THREAD

**Issue by KhayyamA47** [MaikuB/flutter_local_notifications#890] opened 2020-11-05 00:44 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sample code to reproduce the problem**

**Comment by KhayyamA47** [comment] 2020-11-05 00:51
![Uploading android-status-bar-icons-what-they-mean-and-how-to-remove-them-4774877-1-8279f90d9e0c44de836269a560aa4b05.jpg…]()

**Comment by KhayyamA47** [comment] 2020-11-05 01:05
![android-status-bar-icons-what-they-mean-and-how-to-remove-them-4774877-1-8279f90d9e0c44de836269a560aa4b05](https://user-images.githubusercontent.com/54634944/98184714-78bf0380-1f24-11eb-9527-a1d61df8b0e9.jpg)

**Comment by MaikuB** [comment] 2020-11-07 00:33
I don't know what issue you're trying to describe and you didn't fill in the bug report properly either. If this is to with scheduled notifications on Redmi devices, please refer to the readme (https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduled-android-notifications) where this is an issue to do with restrictions on those devices. There isn't anything this plugin can do.

Closing this for now. Feel free to reopen if the issue is different and you can fill in the bug report properly and describe the problem more clearly

**Closed by MaikuB** 2020-11-07 00:33 UTC
