### ISSUE TITLE
didReceiveLocalNotification on iphone 6s with ios 12.4

### ISSUE THREAD

**Issue by lgArlequin** [MaikuB/flutter_local_notifications#279] opened 2019-07-30 15:10 UTC
I don't know if it's an issue, but I'm testing on an iphone 6s with ios 12.4, the issue is that it doesn't work onSelectNotification, but it does work onDidReceiveLocalNotification, when in theory it shouldn't work for an ios under 10.
This is correct?

Sorry for my English :)

**Comment by MaikuB** [comment] 2019-07-30 20:57
Sorry having trouble understanding what you wrote but `onDidReceiveLocalNotification` is for iOS versions before 10

**Comment by lgArlequin** [comment] 2019-07-31 11:36
Hi @MaikuB, 
That's why I'm confused, I don't understand why it works when it shouldn't.
Maybe it's the way the ios version detects? In the case of this phone, can it be detected with an earlier operating system?

**Comment by MaikuB** [comment] 2019-07-31 12:50
Can you provide a sample to reproduce this issue? I've checked the example app in this repo on an iPad with iOS 12.4 and don't encounter the same behaviour

**Comment by lgArlequin** [comment] 2019-07-31 13:17
Here I tried to explain better
https://github.com/MaikuB/flutter_local_notifications/issues/111#issuecomment-516542339

**Comment by MaikuB** [comment] 2019-07-31 13:42
What might be happening is because the local notification hasn't been registered as the `UNUserNotificationCenter` delegate (i.e. the firebase_messaging is the one that has been), the older protocols on when a local notification has been displayed is being invoked (https://github.com/MaikuB/flutter_local_notifications/blob/78c879c354094e7a7a2b278e0ecf819e6ece3b09/ios/Classes/FlutterLocalNotificationsPlugin.m#L506). Without a full sample this is more of a guess though this is what I've seen happen if all of the code to do this registration was removed in the plugin. An extra guard could potentially be put in to handle this situation. Having said that I suspect that if the engine changes to allow for plugins to register as said delegate were put in that this wouldn't be necessary

**Comment by lgArlequin** [comment] 2019-07-31 13:54
Ok, thank you for your answer!
I think I understand what you're saying, but beats a little my knowledge :)

At the moment, this behavior helps me since I can handle both plugins.
I will try to get a newer iphone to perform other tests, I also want to upload a testflight to rule out that it is not something that happens only in debug.
When I do, I tell you my new results.

**Comment by MaikuB** [comment] 2019-08-02 10:36
I believe this should now be addressed in version 0.8.1 now

**Comment by lgArlequin** [comment] 2019-08-02 12:49
Hi @MaikuB, today I passed a testflight, so i can take new tests.
The results were different this time, closer to the behavior that the plugin should supposedly have. Now I am more confused ...

This is the new behavior in all cases (previous here: https://github.com/MaikuB/flutter_local_notifications/issues/111#issuecomment-516542339):

**Foreground**:
flutter_local_notifications: notification appear, execute onSelectNotification (I suppose), payload received.
firebase_messaging onMessage() not work.

**Background**:
flutter_local_notifications: notification appear, open the app, execute onSelectNotification (I suppose), payload received.
firebase_messaging onResume() open the app, but not redirect content.

**Terminated**:
flutter_local_notifications: notification appear, open the app, execute onSelectNotification (I suppose), payload received.
firebase_messaging works fine onLaunch().

The previous behavior was definitely something related to debug mode, but that served me better.

Now, is there any possibility to force debug behavior for releases?
Can you define some setting for this or have some hybrid between both behaviors?

I hope some of this helps you understand the problem.

I will continue doing some more tests and look forward to the development of this topic, and if in spite of my limited knowledge I can be of help in anything, do not hesitate to ask me.

**Comment by MaikuB** [comment] 2019-08-03 23:03
I don't believe what you're seeing has to do with the changes or debug build behaviour. It's likely a timing issue on which plugin is registered first and is the same issue as #111. As such I'm closing this one as it should be resolved. I don't know what you're using local notifications in your app but in general there's going to be issues with using this together with the firebase messaging one and nothing can done so they can both fully work together at the moment

**Closed by MaikuB** 2019-08-03 23:03 UTC
