### ISSUE TITLE
Scheduled notification in for loop

### ISSUE THREAD

**Issue by ClementG63** [MaikuB/flutter_local_notifications#1872] opened 2023-01-19 08:04 UTC
Hello,
I have a problem, i try to create multiple notification at precise date (stored in List). I browse date throw a for loop but only the LAST date is really scheduled. Others are not show.

I can't use Periodicallyshow because we can't set end date. 
Can somebody tell me how to create multiple notifications at same time ? 

```dart
 
  Future<void> configureNotification(String pillName) async {
    final now = DateTime.now();
    for(int i = 0 ; i <= selectedDuration+2 ; i++){
      for (final hourIndex in selectedHours) {
        final splitHour = possibleHours.elementAt(hourIndex).split("h");
        final scheduleDate = TZDateTime(local, now.year, now.month, now.day, int.parse(splitHour.first), int.parse(splitHour.last));

        if(scheduleDate.millisecondsSinceEpoch > now.millisecondsSinceEpoch){
          NotificationService().addNotification(
            title: "NowPills",
            body: "C'est l'heure de votre pillule $pillName",
            endTime: scheduleDate,
            sound: 'pills_notif.mp3', //Add this
            channel: "live",
          ).then((_) => Logger().i("Notification scheduled for: ${DateTime.fromMillisecondsSinceEpoch(scheduleDate.millisecondsSinceEpoch)}"));

        } else {
          if(selectedReccu == 1 && selectedDuration == 1){
            Logger().e("Can't schedule dat anterior date");
            throw ScheduleException("Can't schedule at anterior date");
          }
        }
      }
    }
    resetInput();
  }

```

```dart

  Future<void> addNotification({
    required String title,
    required String body,
    required tz.TZDateTime endTime,
    required String channel,
    required String sound
  }) async {
    final soundFile = sound.replaceAll('.mp3', '');
    final notificationSound = sound == '' ? null : RawResourceAndroidNotificationSound(soundFile);
    final androidDetail = AndroidNotificationDetails(
        channel,
        channel,
        playSound: true,
        sound: notificationSound,
        importance: Importance.max,
        priority: Priority.high,
        icon: "@mipmap/pills_notif",
        channelShowBadge: true,
    );

    final iosDetail = sound == ''
        ? null
        : DarwinNotificationDetails(presentSound: true, sound: sound);

    final noticeDetail = NotificationDetails(
      iOS: iosDetail,
      android: androidDetail,
    );

    localNotificationsPlugin.zonedSchedule(
      0,
      title,
      body.toLowerCase(),
      endTime,
      noticeDetail,
      uiLocalNotificationDateInterpretation: UILocalNotificationDateInterpretation.absoluteTime,
      androidAllowWhileIdle: true,
    );

  }

```

**Comment by sh3rlock97** [comment] 2023-01-27 13:20
u always use the same ID (first param) so the notifications are overwritten... Not a bug its a use error

**Comment by MaikuB** [comment] 2023-02-01 06:46
Closing as @sh3rlock97 has provided the answer. Thanks for jumping in the answer

**Closed by MaikuB** 2023-02-01 06:46 UTC
