### ISSUE TITLE
FlutterLocalNotificationsPlugin().getActiveNotifications() should just return notification that are shown by the PlugIn

### ISSUE THREAD

**Issue by stefanschaller** [MaikuB/flutter_local_notifications#1958] opened 2023-04-14 07:31 UTC
**Describe the bug**

`FlutterLocalNotificationsPlugin().getActiveNotifications()` returns Notifications that are not shown by the Plugin. 
If other plugins create a notification, this notification will also be returned. 

**To Reproduce**

1. Show a notification on the e.g. native iOS side by: 
```swift
    private func showLocalNotification() {
        let content = UNMutableNotificationContent()
                
        // just a random id
        let notificationId = 12;
        content.title = "Title"
        content.body = "Content"        
        content.sound = UNNotificationSound.default
        
        let trigger = UNTimeIntervalNotificationTrigger(timeInterval: 2, repeats: false)
        let request = UNNotificationRequest(identifier: "\(notificationId)", content: content, trigger: trigger)
        
        UNUserNotificationCenter.current().add(request) { error in
            if let error = error {
                print("Error: \(String.init(describing: error))")
            }
        }
    }
```

2. Call `FlutterLocalNotificationsPlugin().getActiveNotifications()`
3. Check the error

**Expected behavior**

The plugin ignores notification that are not shown from the plugin itself.

**Potential solution:**

Maybe by settings a unique key / value pair for each notification that was shown by the plugin.

**Comment by MaikuB** [comment] 2023-04-14 08:35
The entire premise behind this plugin is to act as a wrapper to a platform's APIs. This means the expected behaviour is that it can return notification information regardless of it was from another plugin as they would access the same APIs. There are already those in the community who have this expectation/understanding and use the API to get active notifications even if the source is elsewhere. Expectating otherwise actually breaks their app, requires all plugin authors to provide a way to active notifications specific to their plugin and agree on a standard way on where an identifier is placed for all plugins so it's not very feasible/realistic. If this behaviour doesn't work for your scenarios then that's specific to your application and you can fork the plugin to make the appropriate adjustments. In saying that, this plugin already provides a payload property that can attached with each notification so you could use this as a way to filter it out in your own app

**Comment by stefanschaller** [comment] 2023-04-14 14:58
That's totally understandable, but if other plugins need to add a "NotificationId" in the `userInfo`, otherwise activeUserNotificationRequests is crashing in Swift. 

`content.userInfo["NotificationId"] = payload.notificationId`

If this is value is not set, there is an error in: 
https://github.com/MaikuB/flutter_local_notifications/blob/238068076ae0859be6e3961bec9a5e3d948757e2/flutter_local_notifications/ios/Classes/FlutterLocalNotificationsPlugin.m#L233

Exactly right there: https://github.com/MaikuB/flutter_local_notifications/blob/238068076ae0859be6e3961bec9a5e3d948757e2/flutter_local_notifications/ios/Classes/FlutterLocalNotificationsPlugin.m#L246

**Comment by MaikuB** [comment] 2023-04-14 15:27
I'm assuming you're using the latest stable version of the plugin?  If so,I believe you're referring to an issue was already resolved by https://github.com/MaikuB/flutter_local_notifications/pull/1889 and the lines of code you're referring aren't where this crash actually occurs (reading from the dictionary would return null, not crash) and isn't in Swift either (note: the language used for implementing the plugin for iOS is Objective-C). The changes done as part of the PR I linked to are in the 14.0 prerelease

**Comment by stefanschaller** [comment] 2023-04-17 05:02
I'm now using the version `^14.0.0-dev.4`. Looks good so far, thanks.

**Comment by MaikuB** [comment] 2023-05-18 13:24
Will close this issue now since the changes 14.0 has moved to be a stable for a period of time and you were able to confirm the exception has been fixed

**Closed by MaikuB** 2023-05-18 13:24 UTC
