### ISSUE TITLE
IOS not triggering onSelectNotification

### ISSUE THREAD

**Issue by augusto3691** [MaikuB/flutter_local_notifications#1103] opened 2021-03-26 21:18 UTC
My config is as follow:

```dart
final IOSInitializationSettings initializationSettingsIOS =
      IOSInitializationSettings(
    requestAlertPermission: true,
    requestBadgePermission: true,
    requestSoundPermission: true,
    onDidReceiveLocalNotification:
        (int id, String title, String body, String payload) async {
      didReceiveLocalNotificationSubject.add(ReceivedNotification(
          id: id, title: title, body: body, payload: payload));
    },
  );
```
And on onSelectNotification:

```dart
await flutterLocalNotificationsPlugin.initialize(initializationSettings,
      onSelectNotification: (String payload) async {
    if (payload != null) {
      debugPrint('notification payload: $payload');
    }
    selectNotificationSubject.add(payload);
  });
```

I recieve notification without problem but when i tap it never fires `onSelectNotification`, in Android it works fine, im using version `4.0.1+2`

Any you guys passed for something like that?

**Comment by MaikuB** [comment] 2021-03-27 20:10
Please make sure you've done [this](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#general-setup)

**Comment by augusto3691** [comment] 2021-03-27 20:13
Yes i did, double checked and now triple checked, its weird because one day before yesterday was working normally and yesterday just stop, i checked to see if any new dependency was included but nop :/

**Comment by MaikuB** [comment] 2021-03-27 20:58
If you have done the setup, then the issue is generally happening when another dependency is pulled in and deals with notifications as well but doesn't implement code to make sure it processes notifications that it generates.

If you're certain that you haven't pulled in an additional dependency then I don't have any other guidance to give you and I'd need a link to a repository with code that can reproduce the issue

**Comment by augusto3691** [comment] 2021-03-29 14:40
I believe that the issue is that we are using OneSignal and `flutter_local_notification` any idea to workaroud that? I tried all the issues that talk about it

**Comment by MaikuB** [comment] 2021-03-29 18:42
Perhaps if you write the native code to do the local notifications yourself in a way that's compatible with OneSignal then it may work but I don't know for sure.

Otherwise you'll need to follow https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/197 for updates on their side. As far as I know, nothing can be done on the side of this plugin so will be closing

**Closed by MaikuB** 2021-03-29 18:42 UTC

**Comment by KirillBorodin** [comment] 2021-04-29 04:53
Hello, @MaikuB 
I carefully read [this](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#general-setup), but `onSelectNotification` is not triggering also on my side. 
It works for Android, but doesn't for iOS. 
I am using `^4.0.1+2` library version.

Just to mention, I am using [getstream](https://getstream.io/) library for chat messaging in the app, they are not sending push notifications when app is on foreground, but for my goals it's required. So, I am calling `flutterLocalNotificationsPlugin.show` directly in the app to display a user message in push notification.

What am I doing wrong? Could you help me, please?

```
    final NotificationAppLaunchDetails notificationAppLaunchDetails =
        await flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails();

    if (notificationAppLaunchDetails?.didNotificationLaunchApp ?? false) {
      String selectedNotificationPayload =
          notificationAppLaunchDetails?.payload;
      print('PUSH: didNotificationLaunchApp: $selectedNotificationPayload');
      if (selectedNotificationPayload != null) {
        selectNotificationSubject.add(selectedNotificationPayload);
      }
    }

    const AndroidInitializationSettings initializationSettingsAndroid =
        AndroidInitializationSettings('@mipmap/ic_launcher');
    const IOSInitializationSettings initializationSettingsIOS =
        IOSInitializationSettings();

    const InitializationSettings initializationSettings =
        InitializationSettings(
      android: initializationSettingsAndroid,
      iOS: initializationSettingsIOS,
    );

    await flutterLocalNotificationsPlugin.initialize(initializationSettings,
        onSelectNotification: (String payload) async {
        print('PUSH: onSelectNotification: $payload');
      if (payload != null) {
        selectNotificationSubject.add(payload);
      }
    });
```
