### ISSUE TITLE
Android Initialization throws Error: Null check operator used on a null value.

### ISSUE THREAD

**Issue by komape** [MaikuB/flutter_local_notifications#1364] opened 2021-10-30 13:01 UTC
**Describe the bug**
Initializing for Android throws error for an unhandled exception: Null check operator used on a null value.
Log:

```
E/flutter (13838): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter (13838): #0      MethodChannel.binaryMessenger                              package:flutter/…/services/platform_channel.dart:121
E/flutter (13838): #1      MethodChannel.setMethodCallHandler                      package:flutter/…/services/platform_channel.dart:375
E/flutter (13838): #2      AndroidFlutterLocalNotificationsPlugin.initialize          package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:87
E/flutter (13838): #3      FlutterLocalNotificationsPlugin.initialize                      package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:124
```

**To Reproduce**

1. Initialize the plugin as described in the manual:

```dart
const AndroidInitializationSettings androidSettings =
        AndroidInitializationSettings('@mipmap/ic_launcher');
final IOSInitializationSettings iosSettings = IOSInitializationSettings(
        onDidReceiveLocalNotification: _showNotificationForOldIos);
final InitializationSettings settings =
        InitializationSettings(android: androidSettings, iOS: iosSettings);
_notificationsPlugin.initialize(settings,
        onSelectNotification: _onSelectNotification);
```

2. Run your app with an Android emulator. 

**Expected behavior**

The initialization runs without any errors.

**Sample code to reproduce the problem**

It's just the standard initialization code.

**Comment by komape** [comment] 2021-10-31 07:39
I found the error. It is required to ensure that the Flutter Widgets are initialized if the plugin is initialized in the `main()` method.

```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  // initialize flutter local notifications
  // ...
} 
```

**Comment by MaikuB** [comment] 2021-11-06 09:12
This issue isn't specific to this plugin and is to do with general setup required by Flutter. Though it's not great that Flutter isn't providing a better error message Therefore, I would say the PR you've created is something belongs more with Flutter docs and/or see if they could improve how a better error message can be provided. Is this something you could look into doing?

In the past I've seen Flutter provide assertion messages on this but it's quite possibly that they inadvertently removed this as part of supporting null safety. Furthermore, as this can happen with any plugin, it wouldn't be sustainable/scalable for every maintainer to add this to their docs and then try to keep it up to date as Flutter changes over time.

**Comment by talamaska** [comment] 2022-04-06 16:29
The issue is not related to the ensureInitialized at all
on line 124 in flutter_local_notification_plugin.dart you have non null operator, yet the InitializationSettings clearly shows the android with a question mark, meaning it could be null.
![image](https://user-images.githubusercontent.com/299973/162022827-90536f67-4755-4ccb-893b-765176ad193a.png)

**Comment by MaikuB** [comment] 2022-04-09 02:37
@talamaska this was intentional as the plugin supports multiple platforms as whilst make the signature non-nullable would solve the issue you're highlighting, this would force all applications to specify settings for all of the platforms supported by the plugin. In other words, I felt it made more sense that developers get an error that indicates they should specify settings for platforms they're using as opposed to forcing consumers of the plugin to write code that isn't relevant to their use case.

**Comment by MaikuB** [comment] 2022-04-09 02:44
Forgot to add will close this issue as the issue raised is to do with Flutter that needs better documentation on this that I believe got broken upon moving to null safety

**Closed by MaikuB** 2022-04-09 02:44 UTC

**Comment by talamaska** [comment] 2022-04-09 20:54
This is wrong! You can't say first that something is nullable then make a call forcing it to be not-nullable. You need to have some other way of signaling to the user that he must set the settings according to the platform. For example checking the Platform and the check the value if it is null. The flutter docs are pretty clear for me and for all other devs creating packages for flutter.

**Comment by MaikuB** [comment] 2022-04-09 21:49
@talamaska given the downvote on closing the issue, let me be clear that it was closed because of the original issue mentioned. What you raised should be a separate. 

Also seems like there's a misunderstanding on what I wrote, I was referring more about how the signature says it is billable is intentional. I agree asserts would be better and the plugin is open source so you're welcome to submit a PR to contribute back

**Comment by talamaska** [comment] 2022-04-09 23:30
The original issue is the fact that your plugin is throwing "Null check operator used on a null value". How what I reported is different?

**Comment by MaikuB** [comment] 2022-04-09 23:56
Take a closer look at the first two posts, the code snippet shows values were actually given and that the error is throwing by the Flutter framework itself per the stack trace

**Comment by talamaska** [comment] 2022-04-11 10:36
@MaikuB If I'm ready to make a PR, which branch should i choose i see version 10 is around the corner

**Comment by MaikuB** [comment] 2022-04-11 11:06
The assertions wouldn't be a breaking change so could go to master as part of next stable release
