### ISSUE TITLE
fullScreenIntent dont work with Firebase_message

### ISSUE THREAD

**Issue by ygorrrteles** [MaikuB/flutter_local_notifications#844] opened 2020-10-07 13:46 UTC
I need to implement fullScreenIntent to make my app open the moment I receive a push notification, however, following the documentation, the process did not happen.
cloning the sample project the fullScreenIntent worked correctly.

would anyone know if it is possible to use fullScreenIntent together with firebase_message?

**Comment by MaikuB** [comment] 2020-10-09 10:45
Given you are dealing with push notifications from firebase then you need to read their docs to see if there's a way to do that. There's a difference between push notifications and local notifications so you need be careful as was most likely a push notification, especially when you were able to run the code in the example without any problem. The readme for the `firebase_message` documents the various scenarios when a notification is display or when a callback is called so I suggest you take a closer look.

Closing this as I'm pretty sure the issue here is due to confusion and you haven't been able to reproduce an issue with this plugin running on it's own. Feel free to reopen if you happen to be able to do so

**Closed by MaikuB** 2020-10-09 10:45 UTC
