### ISSUE TITLE
onSelectNotification is not called in IOS.

### ISSUE THREAD

**Issue by singlakaran** [MaikuB/flutter_local_notifications#523] opened 2020-03-11 06:26 UTC
[✓] Flutter (Channel unknown, v1.9.1+hotfix.5, on Mac OS X 10.15.3 19D76, locale en-US)
11:54
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[!] Android Studio (not installed)
[✓] VS Code (version 1.42.1)
[✓] Connected device (1 available)

in IOS when app is in foreground then i click on notification then onSelectNotification method not called.

in IOS when app is running then notification does not show.

**Comment by MaikuB** [comment] 2020-03-11 06:32
Please provide a link to a minimal app that can reproduce this problem. Have you also tried running the example app in this repository?

**Comment by singlakaran** [comment] 2020-03-11 06:55
currently i am using
flutter_local_notifications: ^0.8.2
in this version onSelectNotification method called for IOS?
@MaikuB

**Comment by MaikuB** [comment] 2020-03-11 06:58
That isn't what I asked for. Please read my previous message carefully

**Comment by MaikuB** [comment] 2020-03-11 10:44
If I'm going to take a guess though, you probably didn't follow all of the required setup. In particular the steps mentioned [here](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#general-setup)

**Comment by singlakaran** [comment] 2020-03-11 10:58
i did that, but somehow it was not working for me.

**Comment by MaikuB** [comment] 2020-03-11 11:10
That is meant for newer versions of the plugin (since 0.9.0 inclusive). Note that if you cannot provide the information that I asked above (i.e. [here](https://github.com/MaikuB/flutter_local_notifications/issues/523#issuecomment-597466929)) then I'll be closing this issue

**Comment by balajiks-dev** [comment] 2020-03-14 06:25
Hi,
onSelect Method is not calling on iOS on select notification but it works on Android.
Any code should be added in App Delegate for iOS?

**Comment by MaikuB** [comment] 2020-03-14 06:26
@balajiks-dev it's covered in the readme

**Comment by balajiks-dev** [comment] 2020-03-14 08:34
@MaikuB  Yeah, I read readme and also added the onSelectNotification method also. But it doesn't  react when notification is selected

**Comment by MaikuB** [comment] 2020-03-14 08:36
@balajiks-dev so you read and followed [this](https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/README.md#general-setup)? Note that I had left a comment above that was required since 0.9.0

**Comment by balajiks-dev** [comment] 2020-03-14 19:12
@MaikuB  yeah I read and followed your steps.
I'm getting notification in the app in foreground, background and after killed also.
I have a issue. when the app is in Foreground, onSelecting the notification, onSelectNotification method is not calling in iOS but it works perfectly in Android.

**Comment by balajiks-dev** [comment] 2020-03-14 19:16
@MaikuB Is any code is required to add in AppDelegate to work in onSelectNotification?

**Comment by MaikuB** [comment] 2020-03-14 21:30
@balajiks-dev please provide a link to a minimal sample app that can reproduce the problem. Note that if you happen to be using `firebase_messaging`  as well, there is a known compatibility issue (https://github.com/MaikuB/flutter_local_notifications/issues/111)

**Comment by balajiks-dev** [comment] 2020-03-16 06:58
@MaikuB  Hi, I'm using firebase_messaging plugin and flutter_local_notification plugin also.

**Comment by MaikuB** [comment] 2020-03-16 07:00
This is not the issue to be commenting. See the issue I had linked to in my previous post where there are details on a fork you can use

**Comment by MaikuB** [comment] 2020-03-16 07:05
@singlakaran as you haven't responded in providing a link to minimal app to reproduce this problem, I'll be closing this issue. Feel free to re-open when you have done so

**Closed by MaikuB** 2020-03-16 07:05 UTC
