### ISSUE TITLE
java.lang.NullPointerException in setupNotificationChannel

### ISSUE THREAD

**Issue by healthappsdev** [MaikuB/flutter_local_notifications#826] opened 2020-10-01 10:22 UTC
Hi, I have this issue 

Version   flutter_local_notifications: ^1.4.4+4

    • Flutter version 1.20.3 
    • Dart version 2.9.2

Initialization:

    var initializationSettingsAndroid =
        AndroidInitializationSettings('ic_notif_small');
    var initializationSettingsIOS = IOSInitializationSettings(
        onDidReceiveLocalNotification: onDidReceiveLocalNotification);
    var initializationSettings = InitializationSettings(
        initializationSettingsAndroid, initializationSettingsIOS);
    await flutterLocalNotificationsPlugin.initialize(initializationSettings,
        onSelectNotification: onSelectNotification);

Crash: 

java.lang.NullPointerException
com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setupNotificationChannel

java.lang.RuntimeException: 
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3998)
  at android.app.ActivityThread.access$1400 (ActivityThread.java:268)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1993)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:7814)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1068)
Caused by: java.lang.NullPointerException: 
  at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setupNotificationChannel (FlutterLocalNotificationsPlugin.java:634)
  at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification (FlutterLocalNotificationsPlugin.java:130)
  at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification (FlutterLocalNotificationsPlugin.java:688)
  at com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive (ScheduledNotificationReceiver.java:45)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3989)

**Comment by MaikuB** [comment] 2020-10-01 11:58
You've most likely missed something so you're going to need to debug and/or cross-reference your work with what's covered in the readme and the example app in the repo.

**Comment by healthappsdev** [comment] 2020-10-01 13:50
We have this crash only several user devices. We can't reproduce this crash in our side

**Comment by MaikuB** [comment] 2020-10-01 20:59
Unless you can provide ways to reproduce this then it can't be investigated. Issues like this tend to be from not having done the release build configuration covered in the readme

**Comment by MaikuB** [comment] 2020-10-12 09:38
I'm going to have to close this as no further details have been provided on how to reproduce this. Feel free to re-open if you're able to do so

**Closed by MaikuB** 2020-10-12 09:38 UTC

**Comment by zjamshidi** [comment] 2021-01-15 05:58
I'm getting similar crash reports on Huawei devices. I'm not able to reproduce it in the dev environment.

`flutter_local_notifications: ^3.0.1+5`

here is the crash stack trace:
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setupNotificationChannel(FlutterLocalNotificationsPlugin.java:46)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:4)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java)
       at com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive(ScheduledNotificationReceiver.java:76)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3695)
       at android.app.ActivityThread.-wrap18(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1979)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7425)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**Comment by MaikuB** [comment] 2021-01-15 06:04
@zjamshidi if by dev environment you mean you're trying to reproduce this by doing a debug build then that's expected. Any attempts at reproducing the issue should be done using release mode. This should help indicate if the release build configuration that's required from the plugin wasn't done in your app

**Comment by zjamshidi** [comment] 2021-01-15 06:17
Thanks for your quick reply. By "dev environment" I meant the devices that I have access and I can get the logs. I've already tried the release build on my devices and it seems to be working fine.

**Comment by zjamshidi** [comment] 2021-01-15 06:35
I don't even understand what's null. I only find one `intValue` in `FlutterLocalNotificationsPlugin.java` and it has an if-statement checking the value before calling the method. @MaikuB any thought?

**Comment by MaikuB** [comment] 2021-01-15 06:51
No, this is partly why it's confusing. At this stage, unless there's a way to reproduce this consistently, I don't know what the cause of the issue is. One PR tried to put a default value to fix a similar issue but it's not appropriate for the plugin to put in a fallback value when it's null as developers could be misled to thinking everything is working. I'm considering looking at removing these properties as there are methods that could be use to create the notification channels. Some of that logic could be leveraged so that the channels are specified as part of initialisation. It won't help with existing notifications that could trigger this issue though.

Note that the Proguard rules file for the example app and release build configuration documented at the moment, reflects the changes done in the plugin since [3.0.1+4](https://pub.dev/packages/flutter_local_notifications/changelog#3014). If your application had used an earlier version of the plugin at some of its life, the Proguard rules files would've needed to contain more rules. You can look at what it was like for the example app by going to the appropriate tag that matches the plugin version. If you have rules that were missing then there's not much that can be done is it results in notification data not being saved properly for it to be restored. Only thing I can think of in this case, is you'd need to use a fork to drop these notifications so you won't see crash reports on them anymore

**Comment by zjamshidi** [comment] 2021-01-18 04:52
Nice. I will check the proguard rules. Thanks by the way.

**Comment by zjamshidi** [comment] 2021-03-01 04:32
This crash is happening on and off. I checked the proguard rules and didn't find any issue. what should I do?

**Comment by MaikuB** [comment] 2021-03-01 06:07
@zjamshidi there may be nothing you can do. If at one point your application went out to users without the appropriate rules, having them added later isn't retroactive fix. This is because you would've had "corrupt" notification data saved before and there's nothing the plugin can do to restore that. Potentially, it's happening on and off as you have new users for your apps where the right rules were used. Users that with existing notifications are still going to have corrupt notification data that attempts to get read. You could potentially use a fork to ignore these so the crashes are no longer reported. This isn't going to be done by the plugin as it makes it harder for everyone using the plugin to know there's an issue if this gets silently ignored

**Comment by WaseemAbbasi22** [comment] 2022-03-07 11:36
I am using flutter_local_notifications 9.2.0 and give me this crash. I was unable to reproduce the crash, app is in production and getting this from firebase_crashlytics
**Log:**
java.lang.NullPointerException
com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setupNotificationChannel 
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:4766)
  at android.app.ActivityThread.access$1700 (ActivityThread.java:310)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2288)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8633)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:567)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1133)

**Caused by:**
 java.lang.NullPointerException: 
  at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setupNotificationChannel (Unknown Source:22)
  at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification (Unknown Source:14)
  at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification (Unknown Source)

Traget Android Version:
Android 11,
Android 12

**Comment by WaseemAbbasi22** [comment] 2022-03-07 11:37
@MaikuB could you please look at this

**Comment by MaikuB** [comment] 2022-03-08 08:29
@WaseemAbbasi22 you're going to need to provide a link to a repo hosting a minimal app that can reproduce the issue and no one has yet to provide

**Comment by Levi-Lesches** [comment] 2025-09-19 11:07
After some investigation, this is because your call to `show()` did not provide an `AndroidNotificationDetails` with a channel ID that corresponds to a channel you've created with `createNotificationChannel()`. Make sure to do that, and the error will go away. 

#2689 tracks a better error message for this
