### ISSUE TITLE
Not possible to set presentSound to false / sending a notification without sound

### ISSUE THREAD

**Issue by desmeit** [MaikuB/flutter_local_notifications#1861] opened 2023-01-04 13:12 UTC
I try to let my user send a silent notification if he wants to:
For that I set presentSound to false:

```
  static Future _notificationDetails() async {
    //print("sound: " + sound.toString());
    return NotificationDetails(
      android: AndroidNotificationDetails(
        'channel id',
        'channel name',
        //'channel description',
        channelDescription: 'channel description',
        importance: Importance.max,
        playSound: false,
        sound: const RawResourceAndroidNotificationSound('sound'),
      ),
      iOS: const DarwinNotificationDetails(
        presentSound: false,
        sound: 'sound.aiff',
      ),
    );
  }
```

This works in foreground but not if the app is terminated. I always get the notification with sound. I tried with flutter_local_notifications 9.3.2 and 13.0.0.
How can I create silent notifications?

**Comment by MaikuB** [comment] 2023-01-24 11:35
Could you provide a repository hosting a minimal app using only this plugin that can reproduce this issue? If this were a matter to do the app being terminated then it should be reproducing by change the notification so that it's scheduled to appear later, giving you enough time to terminate the app before the notification appears. There really shouldn't be any difference in how the notification behaves in this regard if this was a local notification.  What you've described would suggest you have an app using push notifications sent via something like Firebase Cloud Messaging. In this case, that is outside the scope of this plugin and would be something for you to investigate further on

**Comment by MaikuB** [comment] 2023-02-17 04:18
Closing due to lack of further response

**Closed by MaikuB** 2023-02-17 04:18 UTC
