### ISSUE TITLE
Flutter show daily at specific time is not working in apk mode, but it is delaying in debug mode, scheduling notification works fine on both modes plesase help me maikuB

### ISSUE THREAD

**Issue by titusfrezer** [MaikuB/flutter_local_notifications#474] opened 2020-02-10 15:49 UTC
**IMPORTANT**
If you are getting a build error on Android that mentions AndroidX incompatibilities, before reporting an issue, please make sure look at the error information carefully as there should be a URL that provides information on migrating your application to AndroidX.

Also note that the plugin has an example application that should cover all of the available functionality. Please check the example application and see if the functionality works before logging an issue. You'll need to clone the repository to run it

**Describe the bug**

**To Reproduce**
If applicable, steps to reproduce the behavior:

**Expected behavior**
If applicable, clear and concise description of what you expected to happen.

**Sample code to reproduce the problem**
Ideally, include a link to a repository that contains code that can reproduce the problem. Suggestion is to fork this repository to modify the example app. Note that without a sample, it'll be may be more difficult to reproduce the problem and/or investigate further

**Comment by MaikuB** [comment] 2020-02-11 09:44
Hey there. You posted an issue using the bug report template but hasn't been replaced with the appropriate details. Please read it again and fill it with the appropriate details.

**Comment by titusfrezer** [comment] 2020-02-11 10:38
Hi MaikuB, soory for being vague, what I am trying is,  i will accept time using date time picker from my user then i will repeat a notification on that specific time daily, i have used show daily at specific time function from the example app,but it  is not working in apk mode,it is delaying in debug mode(sometimes not showing), scheduling notification works fine on both modes, 
Is there bug in the example app that is provided on schedule daily notification? please help

**Comment by MaikuB** [comment] 2020-02-11 10:41
There shouldn't be any bug in the example app. Earlier today I did release APK build on my first and got the daily notification. It is a documented behaviour in the readme that it may not appear at the exact time

**Comment by titusfrezer** [comment] 2020-02-11 18:53
What makes me surprise is scheduling is working just fine, but show daily time notification is letting my app to crash, previously i encountered this issue when i implement scheduling but i fix it by switching minifiedEnabled to false in build.gradle file

**Comment by MaikuB** [comment] 2020-02-11 19:17
You said you ran the example app but what steps did you follow to install it as an APK and did you get the example app by cloning the repository with the latest code?

Also you may want to look at the crash logs via logcat. Don't know if you've followed all of the Android integration guide either. If you're able to provide a minimal app to reproduce the problem then that would help. Otherwise you may have to try to investigate to see what the cause might be. What device(s) does this occur on as well?

**Comment by titusfrezer** [comment] 2020-02-11 19:47
My device is android 7, i have definately followed the android integration guide, otherwise scheduling also mustn't work,i am not sure if the code i am running is the latest code,  but anyways i will try to schedule notification inside a for loop and try to repeat every day, anyways thanks for your quick response

**Comment by MaikuB** [comment] 2020-02-11 19:49
You may want to double check the Android integration guide with regards to setting up the Proguard rules though as it had been updated so there may be a difference between that point of time and when you last looked at it

**Comment by titusfrezer** [comment] 2020-02-11 20:40
thanks for your help 🙏🙏 finally it worked i forgot to add method channel,  but one thing is there any way to handle the delaying, i really want to thank because of your patience and time

**Comment by MaikuB** [comment] 2020-02-11 20:45
Not at the moment. Solving the timezone issues (#118 and #179) will likely result in scheduling one notification at a time but I won't be able to apply this behaviour to existing methods that schedule a single or recurring notification. I'll likely be marking the existing methods as deprecated

**Comment by MaikuB** [comment] 2020-02-12 07:26
Closing this since the original issue has been solved

**Closed by MaikuB** 2020-02-12 07:26 UTC
