### ISSUE TITLE
The backgroundHandler can't find top-level function

### ISSUE THREAD

**Issue by TheHudek** [MaikuB/flutter_local_notifications#2116] opened 2023-10-05 20:39 UTC
**Describe the bug**
The initialize function's onDidReceiveBackgroundNotificationResponse parameter can't find the top-level function. Tried moving it to a separate file as well, or instantiating the FlutterLocalNotificationsPlugin() inside the main() function. The app works perfectly without this parameter.
```bash
E/flutter ( 8923): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter_local_notifications/src/platform_flutter_local_notifications.dart': Failed assertion: line 897 pos 12: 'callback != null':           The backgroundHandler needs to be either a static function or a top
platform_flutter_local_notifications.dart:897
E/flutter ( 8923):           level function to be accessible as a Flutter entry point.
E/flutter ( 8923): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter ( 8923): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter ( 8923): #2      _evaluateBackgroundNotificationCallback
platform_flutter_local_notifications.dart:897
E/flutter ( 8923): #3      AndroidFlutterLocalNotificationsPlugin.initialize
platform_flutter_local_notifications.dart:138
E/flutter ( 8923): #4      FlutterLocalNotificationsPlugin.initialize
flutter_local_notifications_plugin.dart:143
E/flutter ( 8923): #5      main
test.dart:23
E/flutter ( 8923): <asynchronous suspension>
E/flutter ( 8923):
```

**To Reproduce**

Create a new flutter project, initialize Firebase and try initializing flutter_local_notifications.

**Expected behavior**

App should load with no problems and allow notification handling when shut down.

**Sample code to reproduce the problem**
```dart
import 'package:/firebase_options.dart';
import 'package:/utilities/dialogs/loading_dialog.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

@pragma('vm:entry-point')
void notificationTapBackground(NotificationResponse notificationResponse) {
  // handle action
}

FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
    FlutterLocalNotificationsPlugin();
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  const initializationSettingsAndroid =
      AndroidInitializationSettings("@mipmap/ic_launcher");
  const initializationSettingsDarwin = DarwinInitializationSettings();
  const initSettings = InitializationSettings(
    android: initializationSettingsAndroid,
    iOS: initializationSettingsDarwin,
  );
  await flutterLocalNotificationsPlugin.initialize(
    initSettings,
    onDidReceiveNotificationResponse:
        (NotificationResponse notificationResponse) {},
    onDidReceiveBackgroundNotificationResponse: (notificationResponse) async {
      notificationTapBackground;
    },
  );
  runApp(CupertinoApp(
    home: loadingIndicator(),
  ));
}
```

**Flutter doctor**
```bash
[√] Flutter (Channel stable, 3.13.6, on Microsoft Windows [Version 10.0.22621.2283], locale en-US)
    • Flutter version 3.13.6 on channel stable at 
    • Upstream repository 
    • Framework revision ead455963c (9 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at 
    • Platform android-33, build-tools 33.0.1
    • Java binary at: 
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at 

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.8)
    • Visual Studio at 
    • Visual Studio Build Tools 2019 version 16.11.32002.261
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.1)
    • Android Studio at 
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.83.0)
    • VS Code at 
    • Flutter extension version 3.74.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.2283]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 117.0.5938.132
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 117.0.2045.47

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by MaikuB** [comment] 2023-10-05 21:29
If you compared the code you wrote with what's in the readme and example app then you should find that there's a difference where your code is assigning `onDidReceiveBackgroundNotificationResponse` an anonymous function that calls a top level function as opposed to assigning it a top level or static function directly. This means it's failing as expected as the issue is with the code you have so will close this issue

**Closed by MaikuB** 2023-10-05 21:29 UTC
