### ISSUE TITLE
App Crashes When Big Picture Notifications Triggered

### ISSUE THREAD

**Issue by StrangeNoob** [MaikuB/flutter_local_notifications#1020] opened 2021-02-01 10:28 UTC
**Describe the bug**

When Big Picture Notifications triggered, the App crashes. It only happens in my devices i.e. Moto G5S and have tried on other devices, It works perfectly. 

** Sample Code  **
Here is the Sample Code I have used in my app.
`
  sendAndroidNotification(Map<String, dynamic> message) async {
    final String largeIconPath = await _downloadAndSaveFile('https://via.placeholder.com/48x48', 'largeIcon');
    final String bigPicturePath = await _downloadAndSaveFile('https://via.placeholder.com/400x800', 'bigPicture');
    final BigPictureStyleInformation bigPictureStyleInformation =
        BigPictureStyleInformation(FilePathAndroidBitmap(bigPicturePath),
            largeIcon: FilePathAndroidBitmap(largeIconPath),
            contentTitle: 'overridden <b>big</b> content title',
            htmlFormatContentTitle: true,
            summaryText: 'summary <i>text</i>',
            htmlFormatSummaryText: true);
    final AndroidNotificationDetails androidPlatformChannelSpecifics =
        AndroidNotificationDetails('big text channel id',
            'big text channel name', 'big text channel description',
            styleInformation: bigPictureStyleInformation);
    final NotificationDetails platformChannelSpecifics =
        NotificationDetails(android: androidPlatformChannelSpecifics);
    await flutterLocalNotificationsPlugin.show(
        0, 'big text title', 'silent body', platformChannelSpecifics);
  }
`

**Bug Log**

` 
FATAL EXCEPTION: main
 Process: com.android.systemui, PID: 15904
 java.lang.RuntimeException: Canvas: trying to draw too large(347972768bytes) bitmap.
 	at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
 	at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
 	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
 	at android.widget.ImageView.onDraw(ImageView.java:1380)
 	at com.android.systemui.statusbar.StatusBarIconView.onDraw(StatusBarIconView.java:456)
 	at android.view.View.draw(View.java:19200)
 	at android.view.View.updateDisplayListIfDirty(View.java:18150)
 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4224)
 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4204)
 	at android.view.View.updateDisplayListIfDirty(View.java:18109)
 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4224)
 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4204)
 	at android.view.View.updateDisplayListIfDirty(View.java:18109)
 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4224)
 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4204)
 	at android.view.View.updateDisplayListIfDirty(View.java:18109)
 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4224)
 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4204)
 	at android.view.View.updateDisplayListIfDirty(View.java:18109)
 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4224)
 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4204)
 	at android.view.View.updateDisplayListIfDirty(View.java:18109)
 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4224)
 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4204)
 	at android.view.View.updateDisplayListIfDirty(View.java:18109)
 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4224)
 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4204)
 	at android.view.View.updateDisplayListIfDirty(View.java:18109)
 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:669)
 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:675)
 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:783)
 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3020)
 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2834)
 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2387)
 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1420)
 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6835)
 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
 	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
 	at android.view.Choreographer.doFrame(Choreographer.java:658)
 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
 	at android.os.Handler.handleCallback(Handler.java:790)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:164)
 	at android.app.ActivityThread.main(ActivityThread.java:6626)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
`

**Comment by MaikuB** [comment] 2021-02-03 21:42
I don't have other devices to reproduce. Moreover, the stack trace is for code outside of the plugin and all the plugin does is call the appropriate native APIs so there's nothing that could be fixed when it comes to the plugin's code. If you look at the stack trace, it says it says the bitmap is too big for it to render so it looks like you may need to use a smaller bitmap for such devices

**Comment by MaikuB** [comment] 2021-02-09 06:45
Closing as stack trace is to do with bitmap being too big

**Closed by MaikuB** 2021-02-09 06:45 UTC
