### ISSUE TITLE
Based on this exception, what I'm doing wrong?

### ISSUE THREAD

**Issue by JCKodel** [MaikuB/flutter_local_notifications#425] opened 2020-01-02 23:56 UTC
```
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
       at android.app.Notification$BigTextStyle.makeBigContentView(Notification.java:4547)
       at android.app.Notification$BigTextStyle.populateBigContentView(Notification.java:4584)
       at android.app.Notification$Style.buildStyled(Notification.java:4254)
       at android.app.Notification$Builder.build(Notification.java:4061)
       at androidx.core.app.NotificationCompatBuilder.buildInternal(NotificationCompatBuilder.java:316)
       at androidx.core.app.NotificationCompatBuilder.build(NotificationCompatBuilder.java:224)
       at androidx.core.app.NotificationCompat$Builder.build(NotificationCompat.java:1590)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:146)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:634)
       at com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive(ScheduledNotificationReceiver.java:45)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3700)
       at android.app.ActivityThread.access$2000(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1903)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7406)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3707)
       at android.app.ActivityThread.access$2000(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1903)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7406)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

On 140k users, this exception was thrown 2 times in the last 30 days. Not worring, but I want to understand what is causing it (and I can't debug because this is not happening in any of my dev devices)

**Comment by MaikuB** [comment] 2020-01-03 10:40
Not something I can really tell here besides that something is null as the stack trace doesn't line up. Maybe you're on an older version of the plugin so will need that version of the source code from pub to cross-reference. If you're debugging, perhaps worth checking with the release build of your app.

**Comment by MaikuB** [comment] 2020-01-18 00:25
Closing since there's not enough information for me to investigate or reproduce the issue. If you manage to provide a sample app that can reproduce the problem then feel free to reopen the issue

**Closed by MaikuB** 2020-01-18 00:25 UTC
