### ISSUE TITLE
modify content of notification before its shown 

### ISSUE THREAD

**Issue by owais635** [MaikuB/flutter_local_notifications#1224] opened 2021-07-05 02:36 UTC
I'm new to Flutter and I'm using this plugin in my Task Reminder App. I'm not sure where to post my question.

Before the notification (reminder for the Task) is shown to the user, I would like to fetch the latest details about the Task and show the new details. Is there some callback in this library that I can use?

The problem is that, in this lib, we set the contents of the notification when we create the notification. So whenever a Task is modified in my app, I need to cancel the old notification and create a brand new scheduled notification. 

In my use case, it would be far simpler to register a scheduled notification in the future, when that time comes a callback runs and I set the contents and then that notification is shown to the user.

Is there a way to achieve this using this library or something else?

Thanks.

**Comment by MaikuB** [comment] 2021-07-05 08:23
No there isn't. Please see https://github.com/MaikuB/flutter_local_notifications/issues/769 which this is a duplicate of

**Closed by MaikuB** 2021-07-05 08:23 UTC
