### ISSUE TITLE
Any plan to support windows local notification?

### ISSUE THREAD

**Issue by jinfagang** [MaikuB/flutter_local_notifications#1183] opened 2021-05-29 14:06 UTC
Any plan to support windows local notification? this is really needed.

**Comment by MaikuB** [comment] 2021-05-30 08:42
There's an open issue on desktop support already. Please see https://github.com/MaikuB/flutter_local_notifications/issues/746. If you need support for Windows then you'll need to submit a PR. Closing as a duplicate of https://github.com/MaikuB/flutter_local_notifications/issues/746

**Closed by MaikuB** 2021-05-30 08:42 UTC
Labels: duplicate
