### ISSUE TITLE
FlutterLocalNotificationsPlugin.java uses or overrides a deprecated API

### ISSUE THREAD

**Issue by boldt** [MaikuB/flutter_local_notifications#1172] opened 2021-05-19 14:55 UTC
**Describe the bug**

We migratedto flutter 2.0. Now we're getting the following warning, while building our app:

```
Note: C:\Users\<USER>\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_local_notifications-5.0.0+4\android\src\main\java\com\dexterous\flutterlocalnotifications\FlutterLocalNotificationsPlugin.java uses or overrides a deprecated API.
```

**Environment**

* flutter 2.2.0
* flutter_local_notifications: 5.0.0+4

**Comment by MaikuB** [comment] 2021-05-19 20:37
Closing as this is a duplicate of https://github.com/MaikuB/flutter_local_notifications/issues/1148

**Closed by MaikuB** 2021-05-19 20:37 UTC
