### ISSUE TITLE
I use compileSdkVersion 34, is that okay?

### ISSUE THREAD

**Issue by hayatshin** [MaikuB/flutter_local_notifications#2255] opened 2024-03-06 15:51 UTC
I'm not sure but maybe due to flutter version, I need to set compileSdkVersion to 34.
If I set compileSdkVersion to 33, it throws error when building the project.

But `flutter_local_notifications` Android setup [document](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#androidmanifestxml-setup) asks user to set compileSdkVersion to 33..

And with upgraded flutter version, I can't add below in dependency since new format doesn't have buildscript and dependencies.

```
buildscript {
   ...

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.1'
        ...
    }
```

Since android devices face some issue on notification and background service, I'm looking into the setting.

So can this compileSdkVersion 34 cause critical issue?
If so,, then should I downgrade flutter..?

**Comment by RawadZogheib** [comment] 2024-03-07 11:58
I'm getting this:

``` 
flutter_local_notifications:testDebugUnitTest FAILED
```

when I use this package on SDK 34 too, any help?

**Comment by MaikuB** [comment] 2024-03-09 00:39
It should be fine though I will be bumping the SDK version soon

**Comment by MaikuB** [comment] 2024-03-09 23:39
The compile SDK version for the plugin has been bumped now so will close this. I've seen an app pull in version 16.x as a transitive dependency where it is set to 33 but app was set to 34 and there weren't issues either

@RawadZogheib if you have an issue then you'll going need to open a separate issue and include a link to a repository hosting a minimal app that can reproduce the problem. In saying that, I suspect you have an issue with your development environment rather than a plugin one otherwise I'd expect more issues to have been raise. Chances are you need to update the Android build tools you're using

**Closed by MaikuB** 2024-03-09 23:39 UTC

**Comment by RawadZogheib** [comment] 2024-03-10 17:47
Hello, , but when I remove this plugin and write ```./gradlew build``` it works perfectly.

But when I add this plugin I'm getting this error 
``` > Task :flutter_local_notifications:testDebugUnitTest

com.dexterous.flutterlocalnotifications.IsolatePreferencesTest > saveAndGet_ShouldReturnCorrectValues FAILED
    java.lang.NoClassDefFoundError at Shadows.java:2457
        Caused by: java.lang.ClassNotFoundException at SandboxClassLoader.java:161
            Caused by: java.lang.IllegalArgumentException at ClassReader.java:199

com.dexterous.flutterlocalnotifications.models.NotificationActionTest > constructor_populatesAllFields FAILED
    java.lang.NoClassDefFoundError at Shadows.java:2457
        Caused by: java.lang.ClassNotFoundException at SandboxClassLoader.java:161
            Caused by: java.lang.IllegalArgumentException at ClassReader.java:199

2 tests completed, 2 failed

> Task :flutter_local_notifications:testDebugUnitTest FAILED
```

and this error wasn't in the previous sdk are you sure that it's not about the new sdk?

**Comment by RawadZogheib** [comment] 2024-03-10 18:00
but when I build it works but the Schedule Notification is not working... can you help me or you Prefer that I Open a new issue?

**Comment by MaikuB** [comment] 2024-03-10 21:25
> and this error wasn't in the previous sdk are you sure that it's not about the new sdk?

Part of the pipeline setup for the repo is to build the example app on Android and you can see that it has run fine https://github.com/MaikuB/flutter_local_notifications/actions/runs/8214827779/job/22467656239. I'm also working on app that uses a package called [alice](https://pub.dev/packages/alice) that happens to use this plugin. The app is set to compile with 34 as well. I believe your issue is related to [roboelectic](https://github.com/robolectric/robolectric) and that you would need to check the version of the JDK you're using. The integration tests are set to use 17 and that also seems to be what was bundled with the version of Android Studio that I'm on. You may need to switch to use that

**Comment by RawadZogheib** [comment] 2024-03-11 05:48
> > and this error wasn't in the previous sdk are you sure that it's not about the new sdk?
> 
> Part of the pipeline setup for the repo is to build the example app on Android and you can see that it has run fine https://github.com/MaikuB/flutter_local_notifications/actions/runs/8214827779/job/22467656239. I'm also working on app that uses a package called [alice](https://pub.dev/packages/alice) that happens to use this plugin. The app is set to compile with 34 as well. I believe your issue is related to [roboelectic](https://github.com/robolectric/robolectric) and that you would need to check the version of the JDK you're using. The integration tests are set to use 17 and that also seems to be what was bundled with the version of Android Studio that I'm on. You may need to switch to use that

Thank you for your reply, now it works and the local notification works perfectly on iOS and android too, but the schedule notification only work on iOS and not on android, do you have any idea?

**Comment by MaikuB** [comment] 2024-03-11 05:53
You likely need to make sure you've updated your app to accommodate the changes Android 14 introduced when permissions. The plugin has exposed the necessary functionality for this and it was covered in the readme and changelog

**Comment by RawadZogheib** [comment] 2024-03-12 10:26
> You likely need to make sure you've updated your app to accommodate the changes Android 14 introduced when permissions. The plugin has exposed the necessary functionality for this and it was covered in the readme and changelog

The readme doesn't match with the sdk 34
```
buildscript {
   ...

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.1'
        ...
    }
```

but still I did all the steps and I can send a locale notification on android but the schedule notification only is not working with no exception, There is any way so I can be sure that I configure properly my android (I think it's properly configured because as I said before the locale notification works well without the schedule. And thank you for your help sir!

**Comment by capc0307** [comment] 2024-07-03 03:56
@RawadZogheib This is how I made it work: https://github.com/MaikuB/flutter_local_notifications/issues/2361

**Comment by Turtlepaw** [comment] 2025-05-16 02:25
> > Hello, , but when I remove this plugin and write `./gradlew build` it works perfectly.
> > But when I add this plugin I'm getting this error
> > ```
> > 
> > com.dexterous.flutterlocalnotifications.IsolatePreferencesTest > saveAndGet_ShouldReturnCorrectValues FAILED
> >     java.lang.NoClassDefFoundError at Shadows.java:2457
> >         Caused by: java.lang.ClassNotFoundException at SandboxClassLoader.java:161
> >             Caused by: java.lang.IllegalArgumentException at ClassReader.java:199
> > 
> > com.dexterous.flutterlocalnotifications.models.NotificationActionTest > constructor_populatesAllFields FAILED
> >     java.lang.NoClassDefFoundError at Shadows.java:2457
> >         Caused by: java.lang.ClassNotFoundException at SandboxClassLoader.java:161
> >             Caused by: java.lang.IllegalArgumentException at ClassReader.java:199
> > 
> > 2 tests completed, 2 failed
> > 
> > > Task :flutter_local_notifications:testDebugUnitTest FAILED
> > ```
> > 
> > 
> >     
> >   
> > and this error wasn't in the previous sdk are you sure that it's not about the new sdk?
> 
> Hi, i am currently facing the exact same issue as this. How did you fix this error? Thank youu

#2618 should fix this

If you'd like to use this fix now:

```yaml
flutter_local_notifications:
    git:
      url: https://github.com/Turtlepaw/flutter_local_notifications.git
```
