### ISSUE TITLE
uploaded date issue in local notification package

### ISSUE THREAD

**Issue by weddingstudio007** [MaikuB/flutter_local_notifications#1260] opened 2021-08-03 08:31 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sample code to reproduce the problem**

**Comment by weddingstudio007** [comment] 2021-08-03 08:31
upload date isuue

**Comment by MaikuB** [comment] 2021-08-04 11:24
You've not filled in what was required for the bug report template. Please do so or this will be closed. Also note that a  notification itself doesn't have an upload date as notifications do upload anything

**Comment by MaikuB** [comment] 2021-08-11 08:10
Closing to due to lack of information with no minimal app to reproduce the problem

**Closed by MaikuB** 2021-08-11 08:10 UTC
