### ISSUE TITLE
onSelectNotification Callback fires when new notification arrives.

### ISSUE THREAD

**Issue by carlfost** [MaikuB/flutter_local_notifications#487] opened 2020-02-20 16:12 UTC
When a new notification arrives in the android tray, the onSelectNotification callback fires.  It also fires again when I tap on the notification.

**Expected behavior**
I expect the callback to fires only when I tap on it, and not to fire when new notification arrives in the tray.

This is my callback routine:
// the getNotificationAppLaunchDetails() did not help here.

  Future onSelectNotification(String payload) async {
    if (payload != null) {
      var tx = await _flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails(); 
      print('notification payload: ' + payload);
      int eventid = int.parse(payload);
      //FIXME this is launching the EventDetail screen when a notification appears from the server
      if(!tx.didNotificationLaunchApp) {
      CEFEvent event = await CEFEvent().eventLookup(eventid);
       Navigator.push(ctx, MaterialPageRoute(builder: (ctx) => EventDetail(event)));
      }
    }
  }

**Comment by MaikuB** [comment] 2020-02-21 09:52
If I run the example app included in this repository, it doesn't trigger `onSelectNotification` when a notification appears. Please check other aspects of your code to see what's going as this not an issue that has been reported and I would the example app to exhibit the same problem. The code snippet you've pasted doesn't help provide a reproducible case either. You could look at forking the example app to provide one or a link to minimal sample app.

**Comment by MaikuB** [comment] 2020-02-28 09:02
Closing since there's been no further response on this for a while

**Closed by MaikuB** 2020-02-28 09:02 UTC
