### ISSUE TITLE
Periodically show Notification every 72h

### ISSUE THREAD

**Issue by DieGlueckswurst** [MaikuB/flutter_local_notifications#1423] opened 2021-12-21 09:32 UTC
**Describe the bug**
In my app I would like to send push notifications every 72h. But I couldn't find any way to achieve this! As far as I can see these are the only options to show periodically:

```
`/// The available intervals for periodically showing notifications.
enum RepeatInterval {
  /// An interval for every minute.
  everyMinute,

  /// Hourly interval.
  hourly,

  /// Daily interval.
  daily,

  /// Weekly interval.
  weekly
}`
```

Is there any work around? How is daily/weekly possible and no other period? Any help is appreciated here!

**Comment by MaikuB** [comment] 2021-12-22 10:24
What is supported by the plugin is based on what the native notification APIs support. You may need to familiarise yourself with the platforms you're targeting and APIs available as solution design actually should start from there.  Your issue also relates to https://github.com/MaikuB/flutter_local_notifications/issues/92. If the only iOS versions you're concerned with are version 10 or newer, you could look at forking to extending the plugin for your case. You could also submit a PR back to this repository to allow for custom intervals they don't care about daylight savings back to this repository afterwards

Depending on your use case, you might want to consider https://pub.dev/packages/device_calendar instead or look at native APIs that can run a generic task on a periodic basis, sometimes referred to background fetch APIs. These typically may not run on exact times as they would be subject to battery optimisations. 

Would also like to emphasise that this plugin is for local notifications not push notifications. Push notifications are triggered by a remote server e.g. Firebase Cloud Messaging. In saying that, perhaps that is another option you could consider

Note: this isn't a bug as it's not to do with an issue with functionality not being as expected.

**Comment by DieGlueckswurst** [comment] 2021-12-22 19:05
Issue #92  is exactly what I need. Seems like this is a many requested feature for years now. But no one had the time/knowledge to get it done... From my side, I have no idea how I would start here. Anyway, I hope someone will add this feature someday :) Thanks for your work anyway. This package is amazing

**Comment by MaikuB** [comment] 2021-12-29 21:25
Closing this as a duplicate of #92

**Closed by MaikuB** 2021-12-29 21:25 UTC
Labels: duplicate
