### ISSUE TITLE
Default Notification sound not playing when the app is killed/ in background in iOS device

### ISSUE THREAD

**Issue by DishitaShah** [MaikuB/flutter_local_notifications#1214] opened 2021-06-30 07:19 UTC
Notification sound plays when the app is in foreground but is silent when the app is killed / background.

 var androidPlatformChannelSpecifics = new AndroidNotificationDetails(
        'zx', 'zix', ' notification',
        importance: Importance.max, priority: Priority.high);
    var iOSPlatformChannelSpecifics = new IOSNotificationDetails();
    var platformChannelSpecifics = new NotificationDetails(
        android: androidPlatformChannelSpecifics,
        iOS: iOSPlatformChannelSpecifics);
    await flutterLocalNotificationsPlugin.show(
      0,
      title,
      body,
      platformChannelSpecifics,
      payload: payload,
    );

**Comment by MaikuB** [comment] 2021-07-02 07:52
Can you follow the bug report template and include a link to a repository that has a minimal app that can reproduce the issue? I'm also curious if you are using Firebase Cloud Messaging in case you are confusing what you see you happening with this plugin with FCM as the `show` method is typically called when the app is running. Notification messages (read https://firebase.google.com/docs/cloud-messaging/concept-options#notifications) from FCM will appear on their own. It isn't something from this plugin

**Comment by MaikuB** [comment] 2021-07-02 08:34
Another thing to add is you can schedule a local notification (e.g. via `zonedSchedule`) and kill the app. The notification would still appear and the sound should be played. This can be reproduced in the example app

**Comment by MaikuB** [comment] 2021-07-17 23:13
Closing due to lack of further response with a minimal app that can reproduce the reported issue. Feel free to reopen if can provide it

**Closed by MaikuB** 2021-07-17 23:13 UTC
