### ISSUE TITLE
FlutterLocalNotificationsPlugin.java line 25 - 'boolean java.lang.Boolean.booleanValue()' on a null object reference

### ISSUE THREAD

**Issue by Fasust** [MaikuB/flutter_local_notifications#780] opened 2020-09-01 12:10 UTC
First of all, thanks a lot @MaikuB for maintaining this Package. We have been using it in production and it worked amazingly for us so far.

**Describe the bug**
I have been receiving some crash reports through _Crashlytics_ over the Weekend. Multiple users with Android devices encountered crashes caused by the `FlutterLocalNotificationsPlugin.java`. This the Stack trace _Crashlytics_ provided:

````
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4238)
       at android.app.ActivityThread.access$1700(ActivityThread.java:274)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2113)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8154)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
````
Cause by: 
````
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:25)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:1)
       at com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive(ScheduledNotificationReceiver.java:14)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4229)
       at android.app.ActivityThread.access$1700(ActivityThread.java:274)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2113)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8154)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
````

Which is odd because I do not see any boolean comparisons at `FlutterLocalNotificationsPlugin.java:25`. Any Idea what could be causing this? 

Package Version : `^1.5.0-beta.6`

Device States for this Crash:

<img width="446" alt="Screenshot 2020-09-01 at 14 02 28" src="https://user-images.githubusercontent.com/30209993/91849078-c8026280-ec5b-11ea-9e23-7bade7c8124c.png">

**Sample code to reproduce the problem**
I have not encountered this issue myself so far and thus I can't provide a minimal app to reproduce it. But here are some relevant excerpts from our NotificationBloc, I hope this helps.

Initialise Plugin
````dart
  Stream<NotificationState> _mapInitializationToState(
    InitializeNotificationEvent event,
  ) async* {
    //Time Zone
    tz.initializeTimeZones();
    String currentTimeZone = await FlutterNativeTimezone.getLocalTimezone();
    tz.setLocalLocation(tz.getLocation(currentTimeZone));

    //Preferences
    _preferences = await SharedPreferences.getInstance();

    //Notifications
    AndroidInitializationSettings androidSettings =
        AndroidInitializationSettings('ic_launcher');

    IOSInitializationSettings iosSettings = IOSInitializationSettings(
      onDidReceiveLocalNotification: _onIosReceivedNotification,
      requestAlertPermission: event.requestPermissions,
      requestBadgePermission: event.requestPermissions,
      requestSoundPermission: event.requestPermissions,
    );

    InitializationSettings settings = InitializationSettings(
      android: androidSettings,
      iOS: iosSettings,
    );

    bool success = await _plugin.initialize(
      settings,
      onSelectNotification: _onTapNotification,
    );

    if (success) {
      List<LocalNotification> pending = await _loadPending();
      NotificationAppLaunchDetails launchDetails =
          await _plugin.getNotificationAppLaunchDetails();

      yield InitializedNotificationState(
        pendingNotifications: pending,
        launchDetails: launchDetails,
      );
    } else {
      yield MissingPermissionsNotificationState();
    }
  }
````

Schedule Notifications
````dart
  Stream<NotificationState> _mapScheduleToSate(
    ScheduleNotificationEvent event,
    List<LocalNotification> pending,
    NotificationAppLaunchDetails launchDetails,
  ) async* {
    DateTime schedule = event.dateTime ?? event.notification.payload?.scheduled;

    if (schedule.isBefore(DateTime.now())) return;

    _plugin.zonedSchedule(
      event.notification.id,
      event.notification.title,
      event.notification.body,
      tz.TZDateTime.from(schedule, tz.local),
      notificationDetails,
      payload: event.notification.payload.toString(),
      androidAllowWhileIdle: true,
      uiLocalNotificationDateInterpretation:
          UILocalNotificationDateInterpretation.absoluteTime,
    );

    yield ScheduledNotificationState(
      notifications: [event.notification],
      pendingNotifications: pending..add(event.notification),
      launchDetails: launchDetails,
    );
  }
````

**Comment by MaikuB** [comment] 2020-09-01 12:39
The line number may not line up on due to release build optimisations. Perhaps it's somehow to do with this line  https://github.com/MaikuB/flutter_local_notifications/blob/ce870cf553ea392774c92187b6cfde5178a822f4/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java#L182


I'm in the midst of testing daylight savings device on my phone so cannot test it out to confirm right now but if you're able to use a fork and change the condition in the if statement to make sure the value isn't null and is true to see if it works and get back to me then that would be much appreciated. A PR would be awesome as well. Unfortunately I don't have much else to go on without a minimal sample app and steps to reproduce

**Comment by Fasust** [comment] 2020-09-01 13:43
Thanks @MaikuB , I opened a PR with the changes and I'll try if this fixes the issue

**Comment by MaikuB** [comment] 2020-09-01 22:59
Thanks. I'll wait until you confirm before i merge it in although the code changes shouldn't break anything. Your app can reference the fork you have by following these steps  https://dart.dev/tools/pub/dependencies#git-packages

**Comment by MaikuB** [comment] 2020-09-10 08:17
@Fasust did you try to see if using the code changes you've made in your fork fixes the issue?

**Comment by Fasust** [comment] 2020-09-12 07:55
> @Fasust did you try to see if using the code changes you've made in your fork fixes the issue?

Sorry, I forgot to get back to you. Yes, since we have pushed the new version the error stopped accruing on updated devices. Thanks for the help !

**Comment by MaikuB** [comment] 2020-09-12 11:13
Thanks for letting me know. Pushed a new beta release after tweaking the PR. Will close this now

**Closed by MaikuB** 2020-09-12 11:13 UTC
