### ISSUE TITLE
app crashes when clicked on the actions.

### ISSUE THREAD

**Issue by inovatrik-vanjinathan** [MaikuB/flutter_local_notifications#1727] opened 2022-09-29 09:45 UTC
when i clicked on the notification it works fine . but when i clicked on action on the notification  then the app crashes.

it shows 

E/AndroidRuntime(14156): java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ActionBroadcastReceiver: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.view.FlutterCallbackInformation.callbackLibraryPath' on a null object reference
E/AndroidRuntime(14156): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4357)
E/AndroidRuntime(14156): 	at android.app.ActivityThread.access$1600(ActivityThread.java:256)
E/AndroidRuntime(14156): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2101)
E/AndroidRuntime(14156): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(14156): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(14156): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(14156): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/AndroidRuntime(14156): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14156): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(14156): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime(14156): Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.view.FlutterCallbackInformation.callbackLibraryPath' on a null object reference
E/AndroidRuntime(14156): 	at io.flutter.embedding.engine.dart.DartExecutor$DartCallback.toString(:421)
E/AndroidRuntime(14156): 	at java.lang.String.valueOf(String.java:2924)
E/AndroidRuntime(14156): 	at java.lang.StringBuilder.append(StringBuilder.java:132)
E/AndroidRuntime(14156): 	at io.flutter.embedding.engine.dart.DartExecutor.executeDartCallback(:175)
E/AndroidRuntime(14156): 	at com.dexterous.flutterlocalnotifications.ActionBroadcastReceiver.b(:87)
E/AndroidRuntime(14156): 	at com.dexterous.flutterlocalnotifications.ActionBroadcastReceiver.onReceive(:65)
E/AndroidRuntime(14156): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4348)
E/AndroidRuntime(14156): 	... 9 more
D/EGL_emulation(14156): app_time_stats: avg=86.93ms min=29.83ms max=264.88ms count=12
I/Process (14156): Sending signal. PID: 14156 SIG: 9

**Comment by MaikuB** [comment] 2022-10-04 10:13
Can you provide a link to a repository hosting a minimal app that can reproduce the issue?

**Comment by MaikuB** [comment] 2022-10-08 02:55
I believe your issue is the same as #1721 that occurs because you haven't tried to specify the callback to indicate how to handle the action via a background isolate. The 12.0.1 release will now log this as a warning so will close this. If you believe this is a different issue then feel free to re-open this provided you can provided a link to a repository hosting a minimal app that can reproduce the issue.

**Closed by MaikuB** 2022-10-08 02:55 UTC
