### ISSUE TITLE
Android App crashes on startup when desugaring is enabled

### ISSUE THREAD

**Issue by muccy** [MaikuB/flutter_local_notifications#1713] opened 2022-09-21 15:53 UTC
Android App crashes on startup when desugaring is enabled. If desugaring is disabled, app launches correctly.

**To Reproduce**

1. Follow documentation instructions
2. Launch on API 33 emulator

**Expected behavior**

Expecting the to start regularly

**Sample code to reproduce the problem**

My gradle file is like this:

```groovy
...
    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 33
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

...

    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

...

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'
}
```

The app crashes on startup with this in console:
```
E/AndroidRuntime(14287): java.lang.NoSuchMethodError: No interface method addWindowLayoutInfoListener(Landroid/app/Activity;Lj$/util/function/Consumer;)V in class Landroidx/window/extensions/layout/WindowLayoutComponent; or its super classes (declaration of 'androidx.window.extensions.layout.WindowLayoutComponent' appears in /system_ext/framework/androidx.window.extensions.jar)
E/AndroidRuntime(14287): 	at androidx.window.layout.ExtensionWindowLayoutInfoBackend.registerLayoutChangeCallback(ExtensionWindowLayoutInfoBackend.kt:68)
E/AndroidRuntime(14287): 	at androidx.window.layout.WindowInfoTrackerImpl$windowLayoutInfo$1.invokeSuspend(WindowInfoTrackerImpl.kt:52)
E/AndroidRuntime(14287): 	at androidx.window.layout.WindowInfoTrackerImpl$windowLayoutInfo$1.invoke(Unknown Source:8)
E/AndroidRuntime(14287): 	at androidx.window.layout.WindowInfoTrackerImpl$windowLayoutInfo$1.invoke(Unknown Source:4)
E/AndroidRuntime(14287): 	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
E/AndroidRuntime(14287): 	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:227)
E/AndroidRuntime(14287): 	at androidx.window.java.layout.WindowInfoTrackerCallbackAdapter$addListener$1$1.invokeSuspend(WindowInfoTrackerCallbackAdapter.kt:96)
E/AndroidRuntime(14287): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(14287): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/AndroidRuntime(14287): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(14287): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(14287): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(14287): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(14287): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/AndroidRuntime(14287): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14287): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(14287): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by muccy** [comment] 2022-09-21 16:14
If I add these lines the app starts:
```
    implementation "androidx.window:window:1.0.0-rc01"
    implementation "androidx.window:window-java:1.0.0-rc01"
```

Tbh I have no idea what does it mean. I just found that on this link I googled for: https://issuehint.com/issue/flutter/flutter/110658

**Comment by forceLain** [comment] 2022-09-21 21:13
also faces with this issue

**Comment by MaikuB** [comment] 2022-09-23 03:43
Thanks for the info. This looks like it's not an issue with the plugin itself but looking more like an issue with Flutter itself. May have to update readme to include a link to this issue for those that run into this problem

**Comment by MaikuB** [comment] 2022-10-06 08:17
Updated docs on this so closing the issue as it's outside the control of the plugin

**Closed by MaikuB** 2022-10-06 08:17 UTC

**Comment by muccy** [comment] 2022-10-06 09:49
Thanks. I want only to clarify that my issue wasn't on a foldable device

**Comment by MaikuB** [comment] 2022-10-06 10:07
@muccy thanks do you think you could provide a link to a repository hosting a minimal app that can reproduce the issue then? This could help track down further on where the problem lies that seems to be within Flutter as I know of others in the community had used a pre-release version of this plugin for quite some time but hadn't run into this issue
