### ISSUE TITLE
No signature of method: build_5nxhnhqml698dvgvz8nuzpv1k.android() is applicable for argument types: (build_5nxhnhqml698dvgvz8nuzpv1k$_run_closure2) values: [build_5nxhnhqml698dvgvz8nuzpv1k$_run_closure2@5b12714]

### ISSUE THREAD

**Issue by Zarar089** [MaikuB/flutter_local_notifications#1756] opened 2022-10-14 10:26 UTC
After adding the flutter_local_notifications library, I keep getting this error when I try to run my app.  
The gradle console tells me that the error is on line 24
`Build file '............./flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-12.0.0/android/build.gradle' line: 24`

I have checked the aforementioned build.gradle file but I am not being able to detect any errors yet.

**Comment by MaikuB** [comment] 2022-10-15 07:08
You'll need to provide a link to a repository hosting a minimal app that can reproduce the issue. Agreed that this looks odd as gradle file issues should lead to compilation issues in general but has been working when checking the automated builds for the plugin and haven't seen anyone else report this issue either. The line it refers to as well doesn't make sense either.

**Comment by Timu5** [comment] 2022-10-18 07:54
I have same issue. Might be related to proguard and Firebase auth: https://stackoverflow.com/questions/52428973/how-to-minify-a-flutter-app-with-proguard/70268820#70268820

**Comment by Cyril85** [comment] 2022-10-29 19:46
I have the same issue too.

**Comment by fyredave** [comment] 2022-11-11 22:15
Ran into this issue when upgrading an existing but older project to the latest version 12.0.3 as well as flutter 3.3.0. 

Was previously on v9.0.0.

Turns out I just needed to go back and read the installation steps https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#-android-setup

Once I followed the steps and added the missing lines and build tool versions the error was resolved with a clean and rebuild.

**Comment by MaikuB** [comment] 2023-03-12 08:28
As there's been no further information on how to reproduce this issue, I'll be closing this. Recently, I had seen someone else report something similar and this was to not installing appropriate Android SDK. Could well be the same issue here and is similar to what @fyredave reported

**Closed by MaikuB** 2023-03-12 08:28 UTC
