### ISSUE TITLE
onSelectNotification fired when app state is AppLifecycleState.inactive not AppLifecycleState.resumed

### ISSUE THREAD

**Issue by theideasaler** [MaikuB/flutter_local_notifications#1575] opened 2022-04-26 12:46 UTC
Hi,

Thank you for the great work of this plugin! It works great but I have noticed something which I am not too sure if it was designed in that way on purpose.

**Describe the bug**

If you use `WidgetsBindingObserver` with the example app, you could see the `AppLifecycleState` of the app lifecycle. When the app resumes from tapping a **scheduled notification**, the app state will go through `AppLifecycleState.inactive`, and `AppLifecycleState.resumed`. 

I thought the callback `onSelectNotification()` should be called after the state turned `AppLifecycleState.resumed`, but it seems the callback will be fired at the first stage - when the state is `AppLifecycleState.inactive`. While in other package like `firebase_dynamic_links`, its callback `onLink()` only gets called when the app state turns to `AppLifecycleState.resumed`.

![image](https://user-images.githubusercontent.com/17869748/165302865-7dcec73c-faef-46cb-898b-a4cbd89a0a9c.png)

**To Reproduce**

1. Add `WidgetsBindingObserver`, and print the `AppLifecycleState`
2. Schedule a notification 10 seconds later, and leave the app running in background
3. Tap the scheduled notification
4. `onSelectNotification()` gets called **before** the app state turns into `AppLifecycleState.resumed`

**Expected behavior**

`onSelectNotification()` gets called only **after** the app state turns into `AppLifecycleState.resumed`

**Sample code to reproduce the problem**

```
class _HomePageState extends State<HomePage> with WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance?.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance?.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    debugPrint('App state change detected: ${state.toString()}');
  }

 ...

}
```

```
  await flutterLocalNotificationsPlugin.initialize(
    initializationSettings,
    onSelectNotification: (String? payload) async {
      debugPrint('onTap callback fired: $payload');
    },
  );
```

Minimum working code sample repo: https://github.com/theideasaler/flutter-local-notification-sample

**Comment by MaikuB** [comment] 2022-05-05 11:18
Thanks for raising this and providing information on how to reproduce the issue. This does look odd but there's nothing particularly intentional on this and from what I could tell, there's nothing there can be done on this either. If you happen to know otherwise then please do submit a PR. Both plugins make use of similar mechanics so it's quite likely you see a difference for `firebase_dynamic_links` with it taking a while longer to process. If anything, I would say it's odd that Flutter is reporting that the app has resumed later.  I checked the example of `firebase_messaging`, made changes so that the push notification is sent whilst app is on the background, tapped on the notification and it shows the same behaviour you're describing too i.e. `onMessageOpenedApp` is triggeed

**Comment by MaikuB** [comment] 2022-05-06 11:23
Upon looking into this further, the resumed state indicates that the app is visible and responding to input. `firebase_dynamic_links` does more processing and from trying the plugin's example app, it's almost as though the app "restarts" so it's visible before deciding where to go in response to the deep link. Both notification plugins however have callbacks that would still be working in the background. They are responding to the interaction before the app is completely visible so would be why you're seeing this. IMO, this is how it should be as otherwise there'd be delays introduced. I'd expect to see similar behaviour on Android as processing a notification tap may trigger an intent to start or resume an activity. Closing this as I would say this behaving as intended. If you want to delay this for your own purposes then you'd need to look into a fork

**Closed by MaikuB** 2022-05-06 11:23 UTC
