### ISSUE TITLE
Notification with sound MissingPluginException

### ISSUE THREAD

**Issue by mayankjanmejay** [MaikuB/flutter_local_notifications#1150] opened 2021-05-01 00:26 UTC
**Describe the bug**
Hello, 
I seem to be having some trouble initiating Notification with sound. It gives me an error. Below is my code and the error that shows up

```
Future<void> _showOngoingNotification(String callerName, ) async {
final String alarmUri = await platform.invokeMethod<String>('getAlarmUri');
    final UriAndroidNotificationSound uriSound =
        UriAndroidNotificationSound(alarmUri);
    
     AndroidNotificationDetails androidPlatformChannelSpecifics =
        AndroidNotificationDetails(
            'imedical', 'Invictus Medical', 'Invictus Medical',
            importance: Importance.max,
            priority: Priority.high,
            ongoing: true,
            sound: uriSound,
            autoCancel: true);
     NotificationDetails platformChannelSpecifics =
        NotificationDetails(android: androidPlatformChannelSpecifics);
    await flutterLocalNotificationsPlugin.show(0, 'Incoming call from $callerName',
        'Open app to answer', platformChannelSpecifics);
  }
```

`E/flutter ( 6112): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getAlarmUri on channel dexterx.dev/flutter_local_notifications_example)`

**Comment by MaikuB** [comment] 2021-05-02 05:24
This isn't a bug with the plugin and is something you need to fix in your own app as the part that is failing isn't an API from the plugin even. You'll need to look more into the Flutter APIs you're trying to making use of, particularly around [platform channels](https://flutter.dev/docs/development/platform-integration/platform-channels).

As the issue isn't to do with an API from the plugin, I'll be closing this. If you're still having issues after reading the Flutter docs then please use sites/apps like Slack, Discord etc mentioned [https://flutter.dev/community]

**Closed by MaikuB** 2021-05-02 05:24 UTC
