### ISSUE TITLE
Version 6.1.0 crashes "flutter test" on Linux-systems

### ISSUE THREAD

**Issue by boldt** [MaikuB/flutter_local_notifications#1244] opened 2021-07-27 09:06 UTC
Hello,

unfortunately, the current version 6.1.0 crashes our `flutter test`on Linux-system, which were working before.

## Bug

See the following exception:

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK
╞════════════════════════════════════════════════════
The following _CastError was thrown running a test:
Null check operator used on a null value

When the exception was thrown, this was the stack:
#0      FlutterLocalNotificationsPlugin.initialize (package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:151:52)
#1      ...
```

## Reason

Our app is a mobile app, thus we initialize your plugin as follows:

```dart
var initializationSettings = InitializationSettings(
  android: initializationSettingsAndroid,
  iOS: initializationSettingsIOS,
);
await _plugin.initialize(initializationSettings).then(...)
```

Running `flutter test` on a Linux system with v6.1.0 causes the app to use the following new part of your code:

![grafik](https://user-images.githubusercontent.com/750793/127125891-4aaae8f0-1754-40c4-a3c1-b2e54d8f173c.png)

Thus, it crashes with the above null error, since the `InitializationSettings` does not contain a linux parameter, which was not required before.

## Observation

* The `flutter test` did not fail on Linux before, since the init returned `true`
* The `flutter test` still works on Windows, since the init still returns `true`
* Your version bump to 6.1.0 was not a minor patch wrt. semantic versioning

## Workaround

We added a linux-parameter to `InitializationSettings` and our tests are not failing anymore.

**Comment by MaikuB** [comment] 2021-07-27 09:48
Thanks the info. With regard to the semantic versioning, I assume your point is more to do with the behaviour you've observed with the tests? When running this normally on Android or iOS, this behaviour wouldn't occur so replicating this behaviour from a test environment perspective would trying to run the tests with the target platform.

Note I'm not saying this to dismiss issue, rather I'm trying to figure out what's the appropriate approach in having the tests mirror how an app would run. I would imagine a lot more others would run into your issue so I potentially need to consider reverting the changes in 6.1.0 and have it be part of another major release instead

**Comment by MaikuB** [comment] 2021-07-27 09:51
Forgot I'll copy in @proninyaroslav in case they have a suggestion

**Comment by MaikuB** [comment] 2021-07-27 10:56
@boldt would you be able to include info on what kind of test this was as well?

**Comment by proninyaroslav** [comment] 2021-07-27 11:59
I have not looked at the code yet, but in theory this error is notmal, because if you, for example, delete `AndroidInitializationSettings` and try to run this code on Android, you will also get a crash, since this parameter is required and in the code you see the `!` operator. The same goes for other platform-specific initial settings.

**Comment by proninyaroslav** [comment] 2021-07-27 12:03
In fact, this problem was originally present in the plugin, but only manifested itself when Linux support appeared.  When running tests on Linux, we are using the Linux part of the plugin, and then we need to specify `LinuxInitializationSettings`. This is the original logic of the plugin.

**Comment by proninyaroslav** [comment] 2021-07-27 12:07
Probably the solution is to make the platform-specific initial settings optional.

**Comment by y1337x** [comment] 2021-07-27 13:11
> @boldt would you be able to include info on what kind of test this was as well?

I'm working with @boldt on the code. The test is a widget test `testWidgets(...)` from Flutters test package `import 'package:flutter_test/flutter_test.dart';`

The test looks for specific widgets and taps one of them. This executes a `runApp(...)` with a widget which instantiates your plugin `LocalNotifications.init();`.

We never thought of providing `LinuxInitializationSettings` because we're just building a mobile app. And our test and build pipeline never complained about the missing settings because the Linux platform support was not available before. Now, with some Linux platform support enabled, the pipeline crashes as mentioned from @boldt. So the update to 6.1.0 kinda breaks old code in tests when they are done on Linux. Windows works fine. So apps won't stop working, but testing is affected.

I think making the settings optional as @proninyaroslav mentioned would be a good approach.  Be that as well, fixing this problem for people who are using your package and are testing their apps is no problem and done in two lines of code. So it is not too bad at all. Maybe mention it in the README?

**Comment by MaikuB** [comment] 2021-07-27 13:53
@y1337x thanks I get what you mean. With regards to making settings optional, yes it would fix this issue you've run into but this won't address the root cause as the target platform is being derived from the environment your test is run on. Also, the reason why I asked how the test is being run though is that from a testing perspective, I believe it's more appropriate to be using the real plugin in an integration test. From a unit testing perspective (a widget test is essentially a unit test) the plugin is treated as a dependency so in those situations, testing is about verifying a call is made to external dependency. This is typically done via a mock. 

Should one still choose to use an actual implementation of the plugin for their tests, one of the approaches I've seen adopted within the community, which also originally came from the first-party plugins, is they can make use of a different constructor that is visible for testing purposes. An example of this is https://github.com/fluttercommunity/plus_plugins/blob/43d90772365d7a14a4a72cca2c5c97bbee6b3076/packages/android_intent_plus/lib/android_intent.dart#L49. This takes in a parameter that allows you to override the target platform for unit testing purposes through the use of the `platform` package.  A similar constructor also available within the plugin https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/FlutterLocalNotificationsPlugin/FlutterLocalNotificationsPlugin.private.html. If you were to make sure of that in your tests and specify one of the target platforms your app actually supports then I would expect this to solve the issue. It would also be closer to mimicking the actual behaviour of what your app does when run the same platform. 

Another approach is to make use of https://api.flutter.dev/flutter/foundation/debugDefaultTargetPlatformOverride.html. This allows you to override the target platform as part of your test setup. It enables writing tests that also checks for platform-specific widget behaviour but currently the way the plugin is written doesn't check the platform via https://api.flutter.dev/flutter/foundation/defaultTargetPlatform.html. I believe this is the better solution and upon taking a look at the first-party plugins, seems to be the way they moving towards. Makes sense IMO as it makes writing platform-specific tests more easier and removes the need for an additional constructor

**Comment by MaikuB** [comment] 2021-07-27 14:15
No worries. I'll leave this open at the moment in case others run into similar issues and as a reminder to look into changing how the target platform is detected as part of the next major release and updating the testing section (note: the info I provided on the named constructor is already in the readme under the testing section)

**Comment by ltdangkhoa** [comment] 2021-07-28 07:33
Hi,

I'm still stuck in this case.

At first, I run test on MacOS and failed. Then I added 

```
InitializationSettings(
...
macOS: MacOSInitializationSettings(),
}
```
...run test again on MacOS and all tests passed.

However, when I pushed code and run service test on Linux (ubuntu 18.04), I got the failed at the same point as boldt's comment above. Then, I made a changed as 
```
InitializationSettings(
...
macOS: MacOSInitializationSettings(),
linux: LinuxInitializationSettings(defaultActionName: 'test'),
}
```

The test lead to another exception point

```
2021-07-28T06:48:11.4965570Z ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
2021-07-28T06:48:11.4966619Z The following LateError was thrown running a test:
2021-07-28T06:48:11.4968264Z LateInitializationError: Field '_initializationSettings@1076229121' has already been initialized.
2021-07-28T06:48:11.4969475Z 
2021-07-28T06:48:11.4970340Z When the exception was thrown, this was the stack:
2021-07-28T06:48:11.4971837Z #0      LateError._throwFieldAlreadyInitialized (dart:_internal-patch/internal_patch.dart:211:5)
2021-07-28T06:48:11.4973541Z #1      LinuxNotificationManager._initializationSettings= (package:flutter_local_notifications_linux/src/notifications_manager.dart:46:42)
2021-07-28T06:48:11.4984915Z #2      LinuxNotificationManager.initialize (package:flutter_local_notifications_linux/src/notifications_manager.dart:56:5)
2021-07-28T06:48:11.4987438Z #3      LinuxFlutterLocalNotificationsPlugin.initialize (package:flutter_local_notifications_linux/src/flutter_local_notifications.dart:35:20)
2021-07-28T06:48:11.4990039Z #4      FlutterLocalNotificationsPlugin.initialize (package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:151:13)
```

Do you have any idea @MaikuB ?

**Comment by proninyaroslav** [comment] 2021-07-28 07:37
@MaikuB 
This is probably due to double initialization? I think it's worth adding a flag or checking? 
https://github.com/MaikuB/flutter_local_notifications/blob/63e2f27d1d9fea218ebe5122cb3a05d93ee72d8f/flutter_local_notifications_linux/lib/src/notifications_manager.dart#L46

**Comment by MaikuB** [comment] 2021-07-28 14:13
Closing this as Linux support ended up needing to remove to solve https://github.com/MaikuB/flutter_local_notifications/issues/1247 as well. This should solve the initialisation issue although like @proninyaroslav said, this is likely because initialisation was being done twice and is implied by the error

**Closed by MaikuB** 2021-07-28 14:13 UTC

**Comment by proninyaroslav** [comment] 2021-07-28 15:29
This is the fix for the latest error (https://github.com/MaikuB/flutter_local_notifications/issues/1244#issuecomment-888084423): https://github.com/MaikuB/flutter_local_notifications/pull/1250
