### ISSUE TITLE
Flutter local notification not shown in native

### ISSUE THREAD

**Issue by okiwicaksono** [MaikuB/flutter_local_notifications#602] opened 2020-04-27 09:11 UTC
I'm having trouble with local notifications on flutter. I have a flutter application that was added to the native Android application. Notifications can appear when I run the flutter application, but do not appear when I run the flutter application with native Android.

This is the local notification class that I use.

    class _NotificationKeys {
      static const channelId = "notification.channel.id";
      static const channelName = "notification.channel.name";
      static const channelDescription = "notification.channel.desc";
    }
    
    class LocalNotification {
      LocalNotification._privateConstructor() {
        var initializationSettingsAndroid =
            new AndroidInitializationSettings('@mipmap/ic_launcher');
        var initializationSettingsIOS = new IOSInitializationSettings();
        var initializationSettings = new InitializationSettings(
            initializationSettingsAndroid, initializationSettingsIOS);
        _flutterLocalNotificationsPlugin = new FlutterLocalNotificationsPlugin();
        _flutterLocalNotificationsPlugin.initialize(initializationSettings,
            onSelectNotification: _onSelectNotification);
      }
    
      static final LocalNotification instance =
          LocalNotification._privateConstructor();
    
      FlutterLocalNotificationsPlugin _flutterLocalNotificationsPlugin;
    
      List<Function(String payload)> _listeners = [];
    
      void addListener(Function(String payload) function) {
        _listeners.add(function);
      }
    
      Future _onSelectNotification(String payload) async {
        _listeners.forEach((function) {
          function(payload);
        });
      }
    
      Future showNotificationWithDefaultSound(
          int id, String title, String body, String payload) async {
        var androidPlatformChannelSpecifics = new AndroidNotificationDetails(
            _NotificationKeys.channelId,
            _NotificationKeys.channelName,
            _NotificationKeys.channelDescription,
            importance: Importance.Max,
            priority: Priority.High);
        var iOSPlatformChannelSpecifics = new IOSNotificationDetails();
        var platformChannelSpecifics = new NotificationDetails(
            androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
        await _flutterLocalNotificationsPlugin.show(
          id,
          title,
          body,
          platformChannelSpecifics,
          payload: payload,
        );
      }
    }

This is the error I got after `_flutterLocalNotificationsPlugin.show` invoked.

    Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference

This is the stack trace.

    StandardMethodCodec.decodeEnvelope (message_codecs.dart:569)
    MethodChannel._invokeMethod (platform_channel.dart:156)
    <asynchronous gap>
    MethodChannel.invokeMethod (platform_channel.dart:329)
    AndroidFlutterLocalNotificationsPlugin.show (platform_flutter_local_notifications.dart:137)
    FlutterLocalNotificationsPlugin.show (flutter_local_notifications_plugin.dart:136)
    LocalNotification.showNotificationWithDefaultSound (local_notification.dart:49)

I have searched for this issue but have not found any results. If you find a solution to this problem, please enlighten me. Thank you.

**Comment by MaikuB** [comment] 2020-04-27 09:35
I don't know what your issue to give a solution, you might want to see if using a proper drawable resource as the icon will solve your issue. Failing that, you'll likely need to debug the app and step through the Java code of the plugin to see what might be causing the issue you see

**Comment by MaikuB** [comment] 2020-05-08 13:26
I'm not sure if you found out what the issue is but one thing I forgot to point out [`initialize`](https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/FlutterLocalNotificationsPlugin/initialize.html) is an asynchronous method that you should be awaiting to make sure it's done before using the plugin further yet you're invoking as part of a class' constructor.

I'm going to close this as I can't investigate further unless you can provide a minimal sample app that can reproduce the issue. If you're able to do so, feel free to re-open this with a link to a repository that hosts this app

**Closed by MaikuB** 2020-05-08 13:26 UTC
