### ISSUE TITLE
Notification limit

### ISSUE THREAD

**Issue by stx** [MaikuB/flutter_local_notifications#200] opened 2019-04-05 15:39 UTC
There appears to be a limit of 64 scheduled notifications, at least on iOS, that then overrides other notifications. When I schedule number 65, number 1 will not fire.

**Comment by MaikuB** [comment] 2019-04-05 21:12
Yep from what I've gathered, there appears to be a limit applied on iOS. This isn't due to the plugin but a limit Apple appears to have put in. The behaviour you've described also appears to be what's "expected" on iOS when that limit is reached. I would suggest you take a look at some of the solutions around on the web that others have taken to get around that issue e.g. look at using push notifications instead

**Comment by jonahgreenthal** [comment] 2019-04-05 23:25
To the best of our knowledge and belief, is there any such limit on Android?

**Comment by MaikuB** [comment] 2019-04-05 23:48
Not as far as I know but have come across info that Samsung may have a limit https://stackoverflow.com/questions/29344971/java-lang-securityexception-too-many-alarms-500-registered-from-pid-10790-u

**Comment by b-stud** [comment] 2019-05-10 00:05
Is there a way to repeat the same notification at different times? 
For example the same notification daily at random times (computed in advance) for 365 days.
I don't know how the notification manager is built but if it would count for only 1 notification it could then be a way to cross this annoying limit of 64 scheduled notifications.

**Comment by MaikuB** [comment] 2019-05-10 09:53
No you can't. The native APIs only support having them repeat at a fixed time/interval and those count as a single notification. If you need something like, then you'd need to look into either push notifications or write native code (i.e. Objective-C or Swift) to schedule a notification that has info on the next times it should fire, catch when it appears, extract the info on when it should be shown next, schedule it again using that info, repeat etc. Due to some limitations, it's not possible to have this done on the Flutter side at this point in time (e.g. if the plugin exposed an event on when a notification is shown).

On a related note, I should probably state in case it wasn't clear given that the original reported issue here is a limit imposed by the OS and is the same behaviour if you were to do the same thing in iOS via Objective-C or Swift, I've no plans to change something in the plugin so that it mirrors what is the expected behaviour. I will however, look at including info in the readme file.

**Comment by MaikuB** [comment] 2019-05-15 22:11
Will close this as the readme has been updated with a note so other devs aware of OS limits

**Closed by MaikuB** 2019-05-15 22:11 UTC
