### ISSUE TITLE
onDidReceiveNotificationResponse not working on iOS

### ISSUE THREAD

**Issue by apripuppey** [MaikuB/flutter_local_notifications#1877] opened 2023-01-27 08:06 UTC
I want to make the app navigate to specific chat page whenever user click on the notification

i use `onDidReceiveNotificationResponse` it's working well on Android, but on iOS it's not. When the user tap the notification from foreground it does nothing. When tapping the notification on background, it only open the app to the previous state it was.

Here is my code :

> class LocalNotificationService extends GetConnect {
>   String serverKey =
>       'xxxxxxxxxxx';
>   static final FlutterLocalNotificationsPlugin _flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();
> 
>   Future<void> initialize() async {
>     const DarwinInitializationSettings initializationSettingsDarwin = DarwinInitializationSettings(
>       requestSoundPermission: false,
>       requestBadgePermission: false,
>       requestAlertPermission: false,
>     );
> 
>     const InitializationSettings initializationSettings = InitializationSettings(
>       android: AndroidInitializationSettings("@mipmap/ic_launcher"),
>       iOS: initializationSettingsDarwin,
>     );
> 
>     print('Initializing Flutter Local Notification Plugin...');
>     await _flutterLocalNotificationsPlugin.initialize(
>       initializationSettings,
>       onDidReceiveNotificationResponse: onReceiveNotificationResponse,
>       onDidReceiveBackgroundNotificationResponse: onReceiveNotificationResponse,
>     );
>     print('Flutter Local Notification Plugin Initialized');
> 
>     final NotificationAppLaunchDetails? notificationAppLaunchDetails = await _flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails();
>   }
> 
>   void display(RemoteMessage message) async {
>     final box = GetStorage();
>     var currentDeviceUserUuid = box.read('userUuid');
> 
>     if (GlobalController == null) {
>       GlobalController globalC = Get.put(GlobalController());
>     }
>     GlobalController globalC = Get.find<GlobalController>();
> 
>     try {
>       String? title = message.data['title'] ?? '';
>       String? messageText = message.data['message'] ?? '';
>       String? action = message.data['action'] ?? '';
>       String? uniqueId = message.data['uniqueId'] ?? '';
>       String? jobId = message.data['jobId'];
>       String? chatId = message.data['chatId'] ?? '';
>       String? isSetAsGroupSummary = message.data['isSetAsGroupSummary'] ?? '';
>       String? receiverUuid = message.data['receiverUuid'] ?? ''; // bisa diganti dengan id user
>       String? channelId = message.data['channelId'] ?? '';
>       String? channelName = message.data['channelName'] ?? '';
>       String? channelDesc = message.data['channelDesc'] ?? '';
>       int id = DateTime.now().microsecondsSinceEpoch ~/ 1000000;
>       bool setAsGroupSummary = isSetAsGroupSummary?.toLowerCase() == 'true';
> 
>       Map<String, dynamic> listPayload = {
>         'action': action,
>         'uniqueId': uniqueId,
>         'chatId': chatId,
>         'jobId': jobId,
>       };
> 
>       if (currentDeviceUserUuid == receiverUuid && globalC.currentActiveChatWindow.value != chatId) {
>         print('validated');
>         NotificationDetails notificationDetails = NotificationDetails(
>           android: AndroidNotificationDetails(
>             channelId ?? 'my channel id',
>             channelName ?? 'my channel name',
>             channelDescription: channelDesc,
>             groupKey: uniqueId,
>             importance: Importance.max,
>             priority: Priority.high,
>             setAsGroupSummary: setAsGroupSummary,
>           ),
>           iOS: const DarwinNotificationDetails(
>             presentAlert: true,
>             presentBadge: true,
>             presentSound: true,
>           ),
>         );
> 
>         await _flutterLocalNotificationsPlugin.show(
>           id,
>           title,
>           messageText,
>           notificationDetails,
>           payload: json.encode(listPayload),
>         );
>       }
>     } on Exception catch (e) {
>       print('Error>>>$e');
>     }
>   }
> 
>   void displayBackground(RemoteMessage message) async {
>     final box = GetStorage();
>     var currentDeviceUserUuid = box.read('userUuid');
> 
>     //initialize();
> 
>     try {
>       String? title = message.data['title'] ?? '';
>       String? messageText = message.data['message'] ?? '';
>       String? action = message.data['action'] ?? '';
>       String? uniqueId = message.data['uniqueId'] ?? '';
>       String? chatId = message.data['chatId'] ?? '';
>       String? jobId = message.data['jobId'] ?? '';
>       String? isSetAsGroupSummary = message.data['isSetAsGroupSummary'] ?? '';
>       String? receiverUuid = message.data['receiverUuid'] ?? ''; // bisa diganti dengan id user
>       String? channelId = message.data['channelId'] ?? '';
>       String? channelName = message.data['channelName'] ?? '';
>       String? channelDesc = message.data['channelDesc'] ?? '';
>       int id = DateTime.now().microsecondsSinceEpoch ~/ 1000000;
>       bool setAsGroupSummary = isSetAsGroupSummary?.toLowerCase() == 'true';
> 
>       Map<String, dynamic> listPayload = {
>         'action': action,
>         'uniqueId': uniqueId,
>         'chatId': chatId,
>         'jobId': jobId,
>       };
>       print('currentDeviceUserUuid $currentDeviceUserUuid');
>       print('receiverUuid $receiverUuid');
>       if (currentDeviceUserUuid == receiverUuid) {
>         NotificationDetails notificationDetails = NotificationDetails(
>           android: AndroidNotificationDetails(
>             channelId ?? 'my channel id',
>             channelName ?? 'my channel name',
>             channelDescription: channelDesc,
>             groupKey: uniqueId,
>             importance: Importance.max,
>             priority: Priority.high,
>             setAsGroupSummary: setAsGroupSummary,
>           ),
>           iOS: const DarwinNotificationDetails(
>             presentAlert: true,
>             presentBadge: true,
>             presentSound: true,
>           ),
>         );
> 
>         await _flutterLocalNotificationsPlugin.show(
>           id,
>           title,
>           messageText,
>           notificationDetails,
>           payload: json.encode(listPayload),
>         );
>       }
>     } on Exception catch (e) {
>       print('Error>>>$e');
>     }
>   }
> 
>   
>   static void onReceiveNotificationIos(RemoteMessage message) async {
>     var action = message.data['action'];
>     var chatId = message.data['chatId'];
>     var jobId = message.data['jobId'];
> 
>     print('onReceiveNotificationIos');
>     if (action == "homecare_chat") {
>       print('go to homecare_chat');
>       // print('chatId $chatId');
>       // print('jobId $jobId');
>       // print('current route: ${Get.currentRoute}');
>       if (Get.currentRoute == '/home-care-chat') {
>         Get.offAndToNamed('/');
>       }
> 
>       print('chatId $chatId');
>       HomecareChatController().goToChatRoom(chatId ?? '', int.parse(jobId ?? ''), isFromNotification: true);
>     }
>   }
> }
> 
> @pragma('vm:entry-point')
> void onReceiveNotificationResponse(NotificationResponse notificationResponse) async {
>   /* contoh payload 
>   
>   */
> 
>   print('payload ${notificationResponse.payload}');
>   String? payload = notificationResponse.payload;
>   String? action = '';
>   String? chatId = '';
>   String? jobId = '';
> 
>   if (payload == null) {
>     print('payload empty');
>     return;
>   }
> 
>   Map splitPayload = json.decode(payload);
>   action = splitPayload["action"];
>   chatId = splitPayload["chatId"];
>   jobId = splitPayload["jobId"];
> 
>   if (action == "homecare_chat") {
>     print('go to homecare_chat');
>     if (Get.currentRoute == '/home-care-chat') {
>       Get.offAndToNamed('/');
>     }
> 
>     print('chatId $chatId');
>     HomecareChatController().goToChatRoom(chatId ?? '', int.parse(jobId ?? ''), isFromNotification: true);
>   }
> }
> 
> void onDidReceiveLocalNotificationIos(int id, String? title, String? body, String? payload) async {
>   /* TODO: Disini belum dihandle untuk masalah notifikasi iOS, namun hanya disiapkan fungsi saja in case nanti terpakai */
>   print('id : $id');
>   print('title : $title');
>   print('body : $body');
>   print('payload : $payload');
> }

i initialize the flutter local notification on my Main.dart

here's the code:

> `void main() async {
>   await GetStorage.init();
>   WidgetsFlutterBinding.ensureInitialized();
>   await Firebase.initializeApp(
>     options: DefaultFirebaseOptions.currentPlatform,
>   );
> 
>   LocalNotificationService localNotificationService = LocalNotificationService();
>   await localNotificationService.initialize();
>   final FirebaseMessaging fcmInstance = FirebaseMessaging.instance;
>   // Setup FCM on the background
>   FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
> 
>   ConnectivityResult connectivityResult = ConnectivityResult.none;
>   final Connectivity connectivity = Connectivity();
>   connectivityResult = await connectivity.checkConnectivity();
> 
>   if (connectivityResult == ConnectivityResult.wifi || connectivityResult == ConnectivityResult.mobile) {
>     GlobalController globalC = Get.put(GlobalController());
>     // Start FCM
>     final fcmToken = await FirebaseMessaging.instance.getToken();
>     globalC.fcmToken.value = fcmToken ?? ''; //set global fcm Token
> 
>     NotificationSettings settings = await fcmInstance.requestPermission(
>       alert: true,
>       announcement: true,
>       badge: true,
>       carPlay: false,
>       criticalAlert: false,
>       provisional: false,
>       sound: true,
>     );
> 
>     settings.authorizationStatus == AuthorizationStatus.authorized ? print('User granted permission') : print('User declined or has not accepted permission');
> 
>     await FirebaseMessaging.instance.setForegroundNotificationPresentationOptions(
>       alert: true,
>       badge: true,
>       sound: true,
>     );
> 
>     FirebaseMessaging.onMessage.listen((event) {
>       print('ada foreground message');
>       localNotificationService.display(event); //display message ketika ada fcm masuk
>     });
> 
>     fcmInstance.onTokenRefresh.listen((fcmToken) {
>       // TODO: If necessary send token to application server.
>       // Note: This callback is fired at each app startup and whenever a new
>       // token is generated.
>     }).onError((err) {
>       // Error getting token.
>     });
>     // End FCM
>   }
> 
>   FirebaseAnalytics analytics = FirebaseAnalytics.instance;
> 
>   Config.setEnvironment(urlList.isProduction ? environmentConfig.Prod : environmentConfig.Local);
> 
>   runApp(MyApp());
> }`

can you help me which step i did wrong? Thank you

**Comment by MaikuB** [comment] 2023-02-01 06:53
Not something I can help with. You'll need to reach out to the wider community for help with your specific app

**Comment by apripuppey** [comment] 2023-02-01 07:06
> Not something I can help with. You'll need to reach out to the wider community for help with your specific app

Did you see anything wrong with my code? maybe some thing is not right on the flutter_local_notifications initialization. Pardon me for the bad formatting on the code above, i tried many times but it couldn't wrapped the right way.

**Comment by danieljiwonkang98** [comment] 2023-02-01 20:12
IOSNotificationAction does not exists anymore. How do we set up action?
@MaikuB

**Comment by MaikuB** [comment] 2023-02-05 03:02
@apripuppey from what I can see no though I have mentioned in the docs that there are steps that need to be done at https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#general-setup. You should check to see if you've done this. Note I barely use this plugin myself that others in the community are better placed to help resolve your issues

@danieljiwonkang98 that's a mistake in the docs and will be fixed. If you look at the code snippet, it would've shown the the actual class to use, which is `DarwinNotificationActionOption`. A reminder that the plugin also has an example app as well

**Comment by nbergemann** [comment] 2023-02-22 06:54
Hi, 

I had a similar behavior and found this is a solution. Add this to your main just before the runApp call.
```
final NotificationAppLaunchDetails? notificationAppLaunchDetails =
      await flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails();
  if (notificationAppLaunchDetails?.didNotificationLaunchApp == true &&
      notificationAppLaunchDetails?.notificationResponse != null) {
    localNotificationActionBackground(notificationAppLaunchDetails!.notificationResponse!); // handle / navigate
  }
  runApp(
    UncontrolledProviderScope(
      container: container,
      child: const MyApp(),
    ),
  );
```

**Comment by subhangiP** [comment] 2023-02-22 07:15
@MaikuB facing the same issue, I followed all the points in [Readme](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications) . 

- How can we handle redirection on notification tap in termination mode both in android and iOS? 
- Getting error - **unable to establish connection on channel flutter firebase** when the following code is added in AppDelegate.swift 

> import UIKit
import Flutter
// This is required for calling FlutterLocalNotificationsPlugin.setPluginRegistrantCallback method.
import flutter_local_notifications

@UIApplicationMain
override func application(
  _ application: UIApplication,
  didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
  // This is required to make any communication available in the action isolate.
  FlutterLocalNotificationsPlugin.setPluginRegistrantCallback { (registry) in
    GeneratedPluginRegistrant.register(with: registry)
  }

  ...
  return super.application(application, didFinishLaunchingWithOptions: launchOptions)
}

**Comment by matheushw** [comment] 2023-04-18 15:56
I'm facing the same issue. Even after performing the iOS setup, the `onDidReceiveNotificationResponse` callback is not being called when the notification is opened.

**Comment by MaikuB** [comment] 2023-04-26 09:31
If you believe there's a bug, please provide a link to a repository hosting a minimal app that can reproduce the issue and do so in a new issue as your scenarios may be different to what was raised by the OP. With that in mind, I'll be closing this issue  as well as the OP hasn't provided this either

**Closed by MaikuB** 2023-04-26 09:31 UTC

**Comment by FullstackWEB-developer** [comment] 2024-08-29 08:06
@apripuppey I got same issue for iOS
Did you solve this issue?

**Comment by Jonny1987** [comment] 2024-09-06 00:08
Same issue

**Comment by akhilesh-sharma-GSY** [comment] 2024-09-11 11:33
We need to reopen this. I am also facing the same issue.

**Comment by innocent-greats** [comment] 2024-09-19 13:52
Same issue, has anyone manage to work around it or resolve?

**Comment by joshuajylin** [comment] 2024-10-09 06:45
Same issue

**Comment by iastemesem** [comment] 2024-12-17 17:35
Same issue, the onDidReceiveNotificationResponse is not triggered on iOS but it works fine on Android

**Comment by Levi-Lesches** [comment] 2024-12-17 21:14
Guys please read the comment on why this was closed -- If you're having the same problem, please open a _new_ issue with details about your setup, device, and a link to your repository that has this issue if possible.

**Comment by Erfa** [comment] 2025-02-01 15:07
In case this helps anyone else - this wasn't working for me because I hadn't added this part from [the setup](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#general-setup) to AppDelegate.swift:
```swift
if #available(iOS 10.0, *) {
  UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
}
```
Anything else I did with local notifications worked great, but not receiving the tap callback.

**Comment by lukepighetti** [comment] 2025-02-06 20:39
Haven't been able to get this to work on iOS unfortunately. Quite a big blocker. Not sure if I'm missing some setup or if it's not working.

**Comment by lukepighetti** [comment] 2025-02-06 21:48
was able to get this working

![Image](https://github.com/user-attachments/assets/3854d8e1-a689-411d-b8e0-dfb154376a13)
![Image](https://github.com/user-attachments/assets/3e7115ec-9df5-4665-80ff-d3c0cbdd8209)
