### ISSUE TITLE
Issue on iOS when using OneSignal plugin

### ISSUE THREAD

**Issue by Mapk26** [MaikuB/flutter_local_notifications#440] opened 2020-01-14 16:25 UTC
**Describe the bug**
The flutter_local_notification for iOS does not trigger the local notification when the app is in the foreground. When the app is in background the notification is fired correctly but after clicking on it, the app opens but the onSelectNotification is not called.

This happens when the onesignal_flutter plugin is also included.
[https://pub.dev/packages/onesignal_flutter](url)

iOS version 12.4.4

**To Reproduce**
1. Create a new flutter project (with Swift support in my case)
2. Add flutter_local_notification
3. Add onesignal_flutter
4. Test for scheduled local notification. It will not appear when app is in the foregorund, while if in the background the onSelectNotification will not be called.
5. Remove onesignal_flutter, all now works fine.

I don't know if it's an issue you can try to fix on your side or you can suggest a workaround.

Thanks for you support.

**Comment by MaikuB** [comment] 2020-01-14 19:24
I don't believe there's anything I can do, nor do I have a workaround to suggest. It's most likely a similar problem to the compatibility issue with firebase_messaging (https://github.com/MaikuB/flutter_local_notifications/issues/111). I would suggest you ask the OneSignal team for ideas. Note I don't have access to OneSignal or much familiarity with it either so if there was indeed something that could be done on this end, it would likely need contribution from community.

**Comment by Mapk26** [comment] 2020-01-15 09:07
Thanks for your answer. 
I will try opening an issue on OneSignal as well.

I will update here once I'll have some news.
Any help from iOS native devs would be appreciated :)

**Comment by MaikuB** [comment] 2020-01-18 11:19
Note that there are quite a few different services and corresponding SDKs out for push notifications. Changing this plugin so it can work with every single SDK is highly unlikely as it's sustainable to keep doing so and may not be possible to do so either as each SDK may handle doing things differently.  The main focus of this plugin is for local notifications to work on their own as well.

Therefore, I would suggest that you be prepared in implementing local notifications yourself. As the code for the plugin is open-source, you can fork it, use as a reference etc

**Comment by MaikuB** [comment] 2020-03-04 08:52
Closing this as this is more of a OneSignal issue to resolve as I had already made changes to accommodate for how multiple notification plugins can be used together based on how it should be done for Flutter. If OneSignal won't make changes to follow suit,  you may need to look at implementing the local notifications yourself as per my previous post

**Closed by MaikuB** 2020-03-04 08:52 UTC

**Comment by iamdecoder** [comment] 2020-07-27 14:31
> Closing this as this is more of a OneSignal issue to resolve as I had already made changes to accommodate for how multiple notification plugins can be used together based on how it should be done for Flutter. If OneSignal won't make changes to follow suit, you may need to look at implementing the local notifications yourself as per my previous post

Can you explain how to do that, I mean how to use multiple notification plugins?

**Comment by MaikuB** [comment] 2021-03-30 23:45
@emawby 

> I know that the change to not do this was to support Firebase, but I am not sure if it is still necessary.

I'd need to check but besides it being for Firebase, I believe the general change done within the Flutter engine wouldn't require plugins to do this so there's no need to deal with method swizzling (note: this admittedly isn't something I'm familiar with). Flutter would forward the calls. It looks like the FCM plugin has lately changed how things are done though. From memory, the way to get both plugins to work were to disable swizzling on FCM side and the FCM plugin didn't need to register as delegate (I have a fork with the old code at https://github.com/MaikuB/flutterfire/tree/master/packages/firebase_messaging)

>  Would it be possible to make setting vs not setting this package as the UNUserNotificationCenterDelegate configurable? Or to expose the appropriate methods so that apps can call them from their own implementation of UNUserNotificationCenterDelegate

Perhaps but I have a few concerns
-  I remember looking at a method but it had issues as a notification scheduled to appear between the time when the app launches and calls the method won't show as the delegate wouldn't have been registered yet
- If the plugin registers itself as a delegate, this may solve the issue for OneSignal but this could conflict with other plugins to register themselves as well. I believe this is the cause of one issue I saw where another dev used this plugin with another plugin for handling voip
- I don't have OneSignal setup for doing any compatibility testing at the moment. I'm hoping this would be easy to setup. Do you perhaps have an example app that integrates both that could be used for this and I could just make changes to point it to my own instance?

I know the question has been asked to have changes done in this plugin but is it possible that there are changes that could be done within OneSignal as well? I suspect that regardless of the approach used, this would probably need help from your team due to my lack of familiarity with OneSignal and this being something I maintain in spare time

**Comment by emawby** [comment] 2021-04-02 18:36
Hello @MaikuB I believe I have found the issue and the solution does not require code changes for either project! If the application is subclassing FlutterAppDelegate (probably most common) the apps simply need to implement the UNUserNotificationCenter protocol, set itself as the UNUserNotificationCenterDelegate and in the method implementations call Super. This calls the FlutterAppDelegate version of these methods.
```
- (void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler {
    [super userNotificationCenter:center willPresentNotification:notification withCompletionHandler:completionHandler];
}

- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)(void))completionHandler {
    [super userNotificationCenter:center didReceiveNotificationResponse:response withCompletionHandler:completionHandler];
}

```
If the Application is not subclassing FlutterAppDelegate as described in the [Flutter doc here](https://flutter.dev/docs/development/add-to-app/ios/add-flutter-screen#using-the-flutterappdelegate) the app will do something similar but will call the method directly on the `_lifeCycleDelegate` instead of Super.
```
- (void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler {
    [_lifeCycleDelegate userNotificationCenter:center willPresentNotification:notification withCompletionHandler:completionHandler];
}

- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)(void))completionHandler {
    [_lifeCycleDelegate userNotificationCenter:center didReceiveNotificationResponse:response withCompletionHandler:completionHandler];
}
```

**Comment by ben-xD** [comment] 2022-05-13 20:58
That additional code didn't work for me. Those 2 methods are never called - with or without OneSignal installed.

The swift version of @emawby's code is:
```
    override func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
        super.userNotificationCenter(center, willPresent: notification, withCompletionHandler: completionHandler)
    }
    
    override func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void) {
        super.userNotificationCenter(center, didReceive: response, withCompletionHandler: completionHandler)
    }
```

The docs for those delegate methods are:
- https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/1649518-usernotificationcenter
- https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/1649501-usernotificationcenter
