### ISSUE TITLE
RuntimeException when show notification

### ISSUE THREAD

**Issue by Lima21** [MaikuB/flutter_local_notifications#628] opened 2020-05-16 07:42 UTC
Hey, thank you for the amazing package :)
I'm not able to reproduce this bug, this only happens to my clients,  I keep receiving these errors:

`Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
`

`Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setupNotificationChannel(:46)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(:4)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification()
       at com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive(:77)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3392)`

I already update to the latest version of the package(1.4.3), but the issue persists

**Comment by MaikuB** [comment] 2020-05-16 08:05
Sorry but without a way to reproduce this I won't be able to find a fix for it. The only thing that comes to mind is perhaps you haven't done all of the setup that's mentioned in the release build configuration or missed doing this for a period when it was required

**Comment by MaikuB** [comment] 2020-05-16 08:15
Note a similar issue had been reported before in https://github.com/MaikuB/flutter_local_notifications/issues/506 and it looked like one person there actually didn't do all of the configuration. There's more details in that thread but summary is it's likely going to fix the issue for users with existing scheduled notifications. It's something are suppose to have done in the first place as it impacts how scheduled notifications are saved

**Comment by MaikuB** [comment] 2020-05-23 22:52
Closing due to lack of info to reproduce this and I suspect it's happened from not having done all of the configuration

**Closed by MaikuB** 2020-05-23 22:52 UTC

**Comment by Lima21** [comment] 2020-05-30 09:25
Hi @MaikuB 
I've checked the README and I think that I've done the full configuration
`class LocalNotificationsManager {
  FlutterLocalNotificationsPlugin _flutterLocalNotificationsPlugin;
  SharedPreferencesManager _sharedPreferencesManager;

  LocalNotificationsManager(this._sharedPreferencesManager) {
    this._flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();
    this._initializeNotifications();
  }

  _initializeNotifications() async {
    var initializationSettingsAndroid =
        AndroidInitializationSettings('app_icon');
    var initializationSettingsIOS = IOSInitializationSettings(
        onDidReceiveLocalNotification: onDidReceiveLocalNotification);
    var initializationSettings = InitializationSettings(
        initializationSettingsAndroid, initializationSettingsIOS);
    _flutterLocalNotificationsPlugin.initialize(initializationSettings,
        onSelectNotification: onSelectNotification);

    List<PendingNotificationRequest> p =
        await _flutterLocalNotificationsPlugin.pendingNotificationRequests();
    
    if (p.length == 0 && _sharedPreferencesManager.getNotificationKey()) {
      _showDailyAtTime();
    }
  }

  Future<void> _showDailyAtTime() async {
    var title = "Title";
    var desc = "Descriptions";
    var time = _sharedPreferencesManager.getNotificationTime();
    var androidPlatformChannelSpecifics = AndroidNotificationDetails(
        'id', 'name', 'appname');
    var iOSPlatformChannelSpecifics = IOSNotificationDetails();
    var platformChannelSpecifics = NotificationDetails(
        androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
    await _flutterLocalNotificationsPlugin.showDailyAtTime(
        0, title, desc, time, platformChannelSpecifics);
  }
}`

I've more than 1k active users per day, and in the past 7 days, this happens to 24 users, so I guess isn't because bad configuration, do you believe this can be related to permissions?

**Comment by MaikuB** [comment] 2020-05-30 09:44
> I've checked the README and I think that I've done the full configuration

I noticed you said "think" so I would encourage you thoroughly check again. There's an example app that can be used as reference as well.An important thing to note here is when you're testing is that you should test in release mode if you haven't been doing so. 

To elaborate more on what I meant. A _possible_ scenario is that at some point you had missed some steps and the app got into the hands of your users which would have had problems and later an update where all the steps were. I don't know if that's the case but it's only something you will know. If that's what happened then I can't do much about it because it can mean your app saved malformed JSON data that represents which notifications have been scheduled and that's not something that can be repaired

If there's an issue with permissions then it's something you can reproduce to confirm. Right now there are only guesses and nothing to reproduce this for further investigation. Right now, you're the one best positioned to look into this and the code is open source for you to debug and investigate further.
