### ISSUE TITLE
Notification Panel problem in Xiaomi devices

### ISSUE THREAD

**Issue by KhayyamA47** [MaikuB/flutter_local_notifications#802] opened 2020-09-15 20:51 UTC
![b23298cb-c80e-4e42-9889-8e43b2bb08d7](https://user-images.githubusercontent.com/54634944/93263362-b7530000-f7b6-11ea-95d1-a201f10de792.jpeg)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sample code to reproduce the problem**

**Comment by KhayyamA47** [comment] 2020-09-15 22:16
I use local push notification and firebase messaging together.Everything is ok but Mi Mix 2 and other Xiomi devices not show notification panel when notification coming.Only icon show in satatus bar.But in Samsung s9 everything is ok

**Comment by MaikuB** [comment] 2020-09-19 07:39
If you looked at the bug report closely, you should see that I mention that all bug reports must include a minimal sample app to reproduce any reported bugs. Currently, nothing is included so unless you're going to include I'll be closing this issue soon. It also needs to demonstrate the issue using only this plugin. For all I know, your issue could be with push notifications and nothing to do with this plugin.

If this is to do with local notifications, make sure you go through the readme properly on heads-up notifications as covered in https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#displaying-a-notification.

So to reiterate, provide a complete minimal sample app (include a link to a repository) or use the included example app in this repository to demonstrate the problem or this will be closed

**Comment by MaikuB** [comment] 2020-09-25 22:08
Closing since there's been no updates to provide a minimal app the demonstrates a bug to do with this plugin

**Closed by MaikuB** 2020-09-25 22:08 UTC
