### ISSUE TITLE
All  expired notifications are showing once with the actual scheduled application. (Only for Android)

### ISSUE THREAD

**Issue by TharinduKetipe** [MaikuB/flutter_local_notifications#665] opened 2020-06-11 11:52 UTC
Hi! 
I'm scheduling reminders for medical doses in my app.I have scheduled local notifications for upcoming few days at once using this plugin. User can change the reminder times for the doses (such as breakfast , lunch and dinner) using the application. Once user changed the time, I'm removing all the scheduled notifications and reschedule all for the adjusted time.  For the iOS application, it's working fine without any problem. But in android application, when I change the scheduled time, the notifications I have scheduled before that time are show with the actual notification. Let's say I have changed the time of dinner dose, with that dinner reminder notification, breakfast and lunch reminders are also showing. About 6-7 expired notifications are showing with the actual notification. This issue is only happening for android devices. For iOS this function is working fine. My android configurations are also correct. I have checked those several times. Can anyone help me on this?
Thanks!

**Comment by MaikuB** [comment] 2020-06-11 23:03
Hard to say without having code or an app to reproduce this. Can you provide a minimal sample app to reproduce this or fork the repository and update the example to include code that would reproduce the issue?

**Comment by MaikuB** [comment] 2020-06-26 04:11
Closing due to lack of further info

**Closed by MaikuB** 2020-06-26 04:11 UTC
