### ISSUE TITLE
my app terminates due to NoSuchFieldException when alarm is recived or canceled on some device

### ISSUE THREAD

**Issue by NeoMindStd** [MaikuB/flutter_local_notifications#326] opened 2019-09-22 14:55 UTC
**Describe the bug**
Platform: Android
the app terminates due to NoSuchFieldException when alarm is recived or canceled on some device

I don't know why it is occurred.
below is the environment 
OS version: 7~9

Log:

java.lang.NoSuchFieldException
at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.b (FlutterLocalNotificationsPlugin.java:32)
  at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.applyGrouping (FlutterLocalNotificationsPlugin.java)
  or                     .buildGson (FlutterLocalNotificationsPlugin.java)
  or                     .buildPerson (FlutterLocalNotificationsPlugin.java)
  or                     .cancel (FlutterLocalNotificationsPlugin.java)
  or                     .cancelNotification (FlutterLocalNotificationsPlugin.java)
  or                     .createMessage (FlutterLocalNotificationsPlugin.java)
  or                     .createNotification (FlutterLocalNotificationsPlugin.java)
  or                     .extractNotificationDetails (FlutterLocalNotificationsPlugin.java)
  or                     .fromHtml (FlutterLocalNotificationsPlugin.java)
  or                     .getBitmapFromSource (FlutterLocalNotificationsPlugin.java)
  or                     .getDrawableResourceId (FlutterLocalNotificationsPlugin.java)
  or                     .getIconFromSource (FlutterLocalNotificationsPlugin.java)
  or                     .hasInvalidLargeIcon (FlutterLocalNotificationsPlugin.java)
  or                     .hasInvalidLedDetails (FlutterLocalNotificationsPlugin.java)
  or                     .hasInvalidSound (FlutterLocalNotificationsPlugin.java)
  or                     .isValidDrawableResource (FlutterLocalNotificationsPlugin.java)
  or                     .pendingNotificationRequests (FlutterLocalNotificationsPlugin.java)
  or                     .registerWith (FlutterLocalNotificationsPlugin.java)
  or                     .removeNotificationFromCache (FlutterLocalNotificationsPlugin.java)
  or                     .rescheduleNotifications (FlutterLocalNotificationsPlugin.java)
  or                     .saveScheduledNotifications (FlutterLocalNotificationsPlugin.java)
  or                     .scheduleNotification (FlutterLocalNotificationsPlugin.java)
  or                     .sendNotificationPayloadMessage (FlutterLocalNotificationsPlugin.java)
  or                     .setSmallIcon (FlutterLocalNotificationsPlugin.java)
  at com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver.onReceive (ScheduledNotificationBootReceiver.java:21)

![error_log](https://github.com/NeoMindStd/flutter_local_notifications/blob/master/error/error_report.png)

**Comment by MaikuB** [comment] 2019-09-24 00:16
Can you provide a sample app that can reproduce the problem? Does this happen whilst debugging or only on a release build submitted to the store? If it's the latter and you have Proguard turned on, have you added the Proguard rules mentioned in the readme?

**Comment by AndreHaueisen** [comment] 2019-09-27 17:13
Got the same problem.
Here is my code

```
void main() async {
  flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();
}

MyApp() {
    flutterLocalNotificationsPlugin?.cancelAll()?.then((_) {
      _showEngagementNotification();
    });
}

Future<void> _showEngagementNotification() async {
    var initializationSettingsAndroid = AndroidInitializationSettings('app_icon');
    var initializationSettingsIOS = IOSInitializationSettings();
    var initializationSettings = InitializationSettings(initializationSettingsAndroid, initializationSettingsIOS);
    flutterLocalNotificationsPlugin.initialize(
      initializationSettings,
      onSelectNotification: (_) async {
        MaterialPageRoute(
          builder: (buildContext) {
            return MainVideoScreen();
          },
        );
      },
    );

    var androidPlatformChannelSpecifics = new AndroidNotificationDetails('com.fun_hub.ah', 'daily user engagement', 'show daily engagement',
        color: primaryColor, style: AndroidNotificationStyle.BigText);
    var iOSPlatformChannelSpecifics = new IOSNotificationDetails(presentAlert: true, presentBadge: true, presentSound: true);
    var platformChannelSpecifics = new NotificationDetails(androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);

    await flutterLocalNotificationsPlugin.periodicallyShow(
        0, 'Are you bored?', 'Check out these awesome videos we have for you', RepeatInterval.Daily, platformChannelSpecifics);
}

```

**Comment by mtallenca** [comment] 2019-09-27 22:10
I see this error with a release build in the dev channel (1.10.6).  Looks like minify is now enabled by default for release builds.  

Add the following proguard rule for Gson

-keepclassmembers enum * {*;}

see https://github.com/google/gson/issues/1456

**Comment by MaikuB** [comment] 2019-09-28 01:50
@mtallenca what version of the Gradle plugin was your app using and what rules do you have now? I haven't tried it on dev yet but with minify enabled, the following rules worked for me on an app created from stable channel (1.9.1+hotfix.2) with Gradle plugin version 3.5

```
## Flutter wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-dontwarn io.flutter.embedding.**

## Preserve classes from flutter_local_notifications library
-keep class com.dexterous.** { *; }
```

The last rule was mentioned in the readme file as well so not sure if you already had that

**Comment by mtallenca** [comment] 2019-09-28 14:53
I'm using Gradle plugin version 3.5 as well.  When building with flutter 1.9 - I had not added "minify true" and there were no release build issue.  We're doing app+web and moved to 1.10 a couple of weeks ago and that's when release build no longer worked.  Seems the move from 1.9 to 1.10 - minify is enabled on release builds by default (our app was noticeably smaller) and the flutter proguard rules are added.   

Did some debugging in the plugin and the exception is thrown on line 234 of FlutterLocalNotificationsPlugin.java: 

        String notificationDetailsJson = gson.toJson(notificationDetails);

Which led me to the previously mentioned thread.  My proguard-rules.pro file now contains a single line

        -keepclassmembers enum * {*;}

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.10.6, on Mac OS X 10.14.6 18G95, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
[✓] VS Code (version 1.38.1)
[✓] Connected device (2 available)

• No issues found!

**Comment by MaikuB** [comment] 2019-10-01 00:24
Closing this since @NeoMindStd hasn't provided more info. Feel free to re-open the issue if you can do so. I've only seen the exception you've mentioned when the Proguard rules haven't been configured

**Closed by MaikuB** 2019-10-01 00:24 UTC
