### ISSUE TITLE
How to set notification ongoing

### ISSUE THREAD

**Issue by mpannu03** [MaikuB/flutter_local_notifications#197] opened 2019-03-31 11:36 UTC
I am using this package to show my notification in my flutter app.
My question is: How can I set my notification ongoing i.e. it cannot be dismissed by the user.

**Comment by ened** [comment] 2019-04-02 05:25
Duplicate of
https://github.com/MaikuB/flutter_local_notifications/issues/76

**Comment by MaikuB** [comment] 2019-04-04 07:27
As @ened highlighted, your question has been asked and answered before. Please check the info there. I'll be closing this as it's a duplicate but feel free to reopen if there's still issue

**Closed by MaikuB** 2019-04-04 07:27 UTC
