### ISSUE TITLE
Payload is not reset when I click on notification message.

### ISSUE THREAD

**Issue by hirunsr** [MaikuB/flutter_local_notifications#930] opened 2020-11-26 09:13 UTC
How can I reset payload to null or empty string when I've already click on notification message? Please advice.

**Comment by MaikuB** [comment] 2020-11-26 09:20
Not sure what you mean here by reset since the payload is associated with a notification. Please clarify what you mean and try to include a link to a repository with an minimal app that can reproduce what you're describing if you can.

Currently, I've no idea what your application is doing. I can only guess that you are receiving a callback multiple times. This happens if you're calling `initialize` multiple times in your application when it should only be done once

**Comment by hirunsr** [comment] 2020-11-28 02:15
1.	I tried writing a program on the first screen that contains the floating button and when I click the button it will show the notification message and send a payload value and onSelectNotification  will check if the payload is not null or empty then the program will redirect to the second screen.
2.	So, when I tried to click the notification message , the program will redirect to the second screen.
3.	The problem is when I reload the application and go to the first screen again, the program automatically redirect to the second page because the payload is still have the same value.

**Comment by MaikuB** [comment] 2020-11-28 20:23
Calling `initialize` again is what will cause this behaviour (e.g. via hot reload) and is why I mention only call it once in the readme. I may see if this can addressed in a future update but this is something you'll need to work around when using the plugin

**Closed by MaikuB** 2020-11-28 20:23 UTC
