### ISSUE TITLE
NullPointerException in setSmallIcon

### ISSUE THREAD

**Issue by kinex** [MaikuB/flutter_local_notifications#298] opened 2019-08-23 06:37 UTC
This is probably caused by not providing correct icon name on init, but anyway it should not crash.

E/AndroidRuntime( 4210): java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/AndroidRuntime( 4210): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3399)
E/AndroidRuntime( 4210): 	at android.app.ActivityThread.-wrap18(Unknown Source:0)
E/AndroidRuntime( 4210): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
E/AndroidRuntime( 4210): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime( 4210): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime( 4210): 	at android.app.ActivityThread.main(ActivityThread.java:6944)
E/AndroidRuntime( 4210): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4210): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/AndroidRuntime( 4210): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
E/AndroidRuntime( 4210): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/AndroidRuntime( 4210): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setSmallIcon(FlutterLocalNotificationsPlugin.java:156)
E/AndroidRuntime( 4210): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:131)
E/AndroidRuntime( 4210): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:598)
E/AndroidRuntime( 4210): 	at com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive(ScheduledNotificationReceiver.java:45)
E/AndroidRuntime( 4210): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3392)
E/AndroidRuntime( 4210): 	... 8 more

**Comment by duge86** [comment] 2019-08-23 07:08
We are getting the same error

**Comment by MaikuB** [comment] 2019-08-23 12:53
> This is probably caused by not providing correct icon name on init, but anyway it should not crash.

I understand where that is coming but the alternative as far as I can tell is that this gets swallowed, which would make it misleading for those using the plugin thinking everything is working and makes it hard to debug for those using the plugin and for me if there's an issue. From what I've seen, the official plugins throw exceptions back as well

@duge86 please provide a sample that reproduces the problem

**Comment by duge86** [comment] 2019-08-23 13:23
@MaikuB Actually most of the devices don't give this error, however at some android devices mostly android 9 devices give the crash report belove. We could't reproduce the error on our devices and emulators. The icon is generated using image asset studio.

java.lang.RuntimeException: 
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3612)
  at android.app.ActivityThread.access$1300 (ActivityThread.java:237)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1796)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7050)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)
Caused by: java.lang.NullPointerException: 
  at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setSmallIcon (FlutterLocalNotificationsPlugin.java:156)
  at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification (FlutterLocalNotificationsPlugin.java:131)
  at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification (FlutterLocalNotificationsPlugin.java:598)
  at com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive (ScheduledNotificationReceiver.java:45)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3603)

**Comment by kinex** [comment] 2019-08-23 14:05
Possible enhancement is to make FlutterLocalNotificationsPlugin.initialize report an error if provided icon name is invalid. I think now it fails silently (PlatformException is thrown internally by the plugin but it is not thrown to Flutter) and the whole app will crash later when you try to show a notification. But not a big deal, as it seems to work if you provide a valid icon name. 

@duge86 Did you try using https://romannurik.github.io/AndroidAssetStudio/index.html. Is it possible that some of the drawable icons are missing from your project (there are 5 icons), maybe they are all required?

**Comment by duge86** [comment] 2019-08-23 14:14
@kinex We made the icon now with the website you mentioned and uploaded that version of app. I will write the results when available.

**Comment by MaikuB** [comment] 2019-08-23 14:18
@kinex Hmm from memory (it's late here) , platform exceptions did go over to the flutter side and have seen cases where they can be caught too. Your case seems to be slightly different because it looks like you're scheduling a notification so it can't be propagated.

I suspect I'll have to update the types of exceptions returned at some point as I recall there being some discussion on one of the main Flutter repositories around developing plugins and what exceptions to use

**Comment by duge86** [comment] 2019-08-24 18:53
Although we used romannurik github to create icon, at some devices we get the error

**Comment by MaikuB** [comment] 2019-08-24 23:58
can't really help you here unless you can provide something that can reproduce the problem. there was one other similar post [here](https://github.com/MaikuB/flutter_local_notifications/issues/220). don't know if it'll help though. i'm closing this since the OP (@kinex) has been able to resolve their issue

**Closed by MaikuB** 2019-08-24 23:58 UTC
