### ISSUE TITLE
Android - Crash on ScheduledNotificationBootReceiver

### ISSUE THREAD

**Issue by Donerkebap13** [MaikuB/flutter_local_notifications#382] opened 2019-11-30 11:33 UTC
First, thanks for the awesome job!

I discovered this crash in Production. Couldn't reproduce it on my test environment. It seems to happen when loading scheduled notifications.

**Stacktrace**
```
Fatal Exception: java.lang.RuntimeException
Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver: java.lang.RuntimeException: Missing type parameter.

android.app.ActivityThread.handleReceiver (ActivityThread.java:3399)
android.app.ActivityThread.-wrap18 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1780)
android.os.Handler.dispatchMessage (Handler.java:105)
android.os.Looper.loop (Looper.java:164)
android.app.ActivityThread.main (ActivityThread.java:6942)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)
```
```
Caused by java.lang.RuntimeException
Missing type parameter.

com.google.gson.reflect.TypeToken.getSuperclassTypeParameter (TypeToken.java:26)
com.google.gson.reflect.TypeToken.<init> (TypeToken.java:7)
>> com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin$1.<init> (FlutterLocalNotificationsPlugin.java)
com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.loadScheduledNotifications (FlutterLocalNotificationsPlugin.java:25)
com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.rescheduleNotifications (FlutterLocalNotificationsPlugin.java)
com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver.onReceive (ScheduledNotificationBootReceiver.java:21)
android.app.ActivityThread.handleReceiver (ActivityThread.java:3392)
android.app.ActivityThread.-wrap18 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1780)
android.os.Handler.dispatchMessage (Handler.java:105)
android.os.Looper.loop (Looper.java:164)
android.app.ActivityThread.main (ActivityThread.java:6942)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)
```
**AndroidManifest.xml**
```
<receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />
        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"></action>
            </intent-filter>
        </receiver>
...
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
```

**Initialization**
```
flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();
      flutterLocalNotificationsPlugin.initialize(InitializationSettings(
          AndroidInitializationSettings('notification_icon'),
          IOSInitializationSettings()));
```

**Usage**
```
Future<void> scheduleDailyNotification(
      WeekDays day,
      DateTime time,
      int index,
      String channelId,
      String channelName,
      String channelDescription,
      String title,
      String message) async {
      var androidPlatformChannelSpecifics =
      AndroidNotificationDetails(channelId, channelName, channelDescription);
      var iOSPlatformChannelSpecifics = IOSNotificationDetails();
      var platformChannelSpecifics = NotificationDetails(
          androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
      await flutterLocalNotificationsPlugin?.showWeeklyAtDayAndTime(
          index,
          title,
          message,
          _weekdayToDay(day),
          _dateTimeToTime(time),
          platformChannelSpecifics);
      print("Scheduled notification for $day at $time");
  }
```

Thank you!

**Comment by MaikuB** [comment] 2019-11-30 11:39
What do you mean by test environment in this case? Does it still result in a release build with code shrinking enabled? Have you configured the Proguard rules as well?

**Comment by Donerkebap13** [comment] 2019-11-30 12:25
Yes. I've tried a release version installed through Google Play Alpha channel in a couple of Android devices and it doesn't seem to fail. Proguard rules are updated too `-keep class com.dexterous.** { *; }`.

**Comment by MaikuB** [comment] 2019-11-30 12:29
Can you try adding the rules mentioned in [here]( https://github.com/google/gson/blob/master/examples/android-proguard-example/proguard.cfg) as well? I don't recall needing these in the past but suspect they'll be needed and will give it a spin soon. Leave out the rule that's for the classes specific to that example app.

**Comment by pedromassango** [comment] 2019-12-01 07:14
Thanks @MaikuB I will do that and once I have more information I will leave it here

**Comment by MaikuB** [comment] 2019-12-01 07:26
@Donerkebap13 haven't been able to get this happen myself, if you can try adding the ProGuard rules for GSON and let me know how that goes then that would be much appreciated

**Comment by Donerkebap13** [comment] 2019-12-06 09:49
I'm so sorry but I couldn't risk to release another broken build to production if the rules are still wrong. What I've done is to release with ProGuard deactivated, so no obfuscation at all, and it works. Zero crashes. That means the problem has to do with ProGuard for sure. When I have the time I'll try again to reproduce it in local and play with the rules to see if I discover something new.

**Comment by MaikuB** [comment] 2019-12-06 10:10
Understandable. Let me know how it goes

**Comment by macfleid** [comment] 2019-12-18 08:38
Hi,
having same issue with shrinkResources enabled 

`[ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.AssertionError: java.lang.NoSuchFieldException: Drawable
12-18 09:26:00.720  8999  8999 E flutter :      at c.c.e.b.a.ja$a.<init>(:12)
12-18 09:26:00.720  8999  8999 E flutter :      at c.c.e.b.a.V.a(:5)
12-18 09:26:00.720  8999  8999 E flutter :      at c.c.e.q.a(:18)
12-18 09:26:00.720  8999  8999 E flutter :      at c.c.e.b.a.p.a(:21)
12-18 09:26:00.720  8999  8999 E flutter :      at c.c.e.b.a.p.a(:37)
12-18 09:26:00.720  8999  8999 E flutter :      at c.c.e.b.a.p.a(:17)
12-18 09:26:00.720  8999  8999 E flutter :      at c.c.e.q.a(:18)
12-18 09:26:00.720  8999  8999 E flutter :      at c.c.e.q.a(:40)
12-18 09:26:00.720  8999  8999 E flutter :      at c.c.e.q.a(:38)
12-18 09:26:00.720  8999  8999 E flutter :      at c.c.e.q.a(:35)
12-18 09:26:00.720  8999  8999 E flutter :      at c.c.e.q.a(:33)
12-18 09:26:00.720  8999  8999 E flutter :      at com.dexterous.flutterlocalnotifications.d.a(:59)
12-18 09:26:00.720  8999  8999 E flutter :      at com.dexterous.flutterlocalnotifications.d.c(:41)
12-18 09:26:00.720  8999  8999 E flutter :      at com.dexterous.flutterlocalnotifications.d.onMethodCall(:6)
12-18 09:26:00.720  8999  8999 E flutter :      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(:2)
12-18 09:26:00.720  8999  8999 E flutter :      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(:5)
12-18 09:26:00.720  8999  8999 E flutter :      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(:2)
12-18 09:26:00.720  8999  8999 E flutter :      at android.os.MessageQueue.nativePollOnce(Native Method)
12-18 09:26:00.720  8999  8999 E flutter :      at android.os.MessageQueue.next(MessageQueue.java:326)
12-18 09:26:00.720  8999  8999 E flutter :      at android.os.Looper.loop(Looper.java:160)
12-18 09:26:00.720  8999  8999 E flutter :      at android.app.ActivityThread.main(ActivityThread.java:6898)
12-18 09:26:00.720  8999  8999 E flutter :      at java.lang.reflect.Method.invoke(Native Method)
12-18 09:26:00.720  8999  8999 E flutter :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
12-18 09:26:00.720  8999  8999 E flutter :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
12-18 09:26:00.720  8999  8999 E flutter : Caused by: java.lang.NoSuchFieldException: Drawable
12-18 09:26:00.720  8999  8999 E flutter :      at java.lang.Class.getField(Class.java:1601)
12-18 09:26:00.720  8999  8999 E flutter :      at c.c.e.b.a.ja$a.<init>(:6)
12-18 09:26:00.720  8999  8999 E flutter :      ... 23 more
`

It's doing it on initiating regular notifications 
`var androidPlatformChannelSpecifics = new AndroidNotificationDetails(
      '17977', 'XX', 'XX notification channel 3',
      importance: Importance.Max, priority: Priority.High);
    var iOSPlatformChannelSpecifics = new IOSNotificationDetails();
    var platformChannelSpecifics = new NotificationDetails(
      androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
    return flutterLocalNotificationsPlugin.showWeeklyAtDayAndTime(
      NOTIF_ID_SUNDAY,
      'Une nouvelle semaine commence',
      'our message',
      Day.Sunday,
      new Time(21,0,0),
      platformChannelSpecifics
    );`

with shrinkResources false there is no error

**Comment by MaikuB** [comment] 2019-12-18 08:40
I suspect you need to follow the steps here around configuring the resources to keep https://developer.android.com/studio/build/shrink-code

Are you able to try that and let me know how it goes?

**Comment by macfleid** [comment] 2019-12-18 08:45
yes i'm trying

**Comment by macfleid** [comment] 2019-12-18 08:55
Okay, adding proguard rules seems having solves this. 
Big excuse and thank you @MaikuB 
```
-keep class com.dexterous.** { *; }
```

**Comment by MaikuB** [comment] 2019-12-18 11:25
I've updated the readme with more info on configuring Proguard/R8 and included a sample file for the example app as well. I believe those should help others address the issue so will close this. Feel free to re-open if this is still an issue

**Closed by MaikuB** 2019-12-18 11:25 UTC

**Comment by ubitechparth** [comment] 2022-11-30 11:57
after add proguard file it work fine thanks@MaikuB
