### ISSUE TITLE
sound is stopped when scoroll down status bar

### ISSUE THREAD

**Issue by KianuPark** [MaikuB/flutter_local_notifications#957] opened 2020-12-25 12:18 UTC
schedule notification is well performed, but i'm making alarm stuff using this plugin
problem is when notification hover, scroll down android status bar then sound is stopped
clicking hover window doesn't terminate sound though 
so is this bug? , is there a way to playing sound ongoing when scrolling down status bar?
or  I don't want to display a normal hovering notification, and on a user action, open an activity. I want to display an full-intent activity in foreground without asking any user action like current basic alarm app. is this possible in this plugin?

my Details code( tzdate is unfriend to me so use date format)

void scheduleAlarm(DateTime scheduledNotificationDateTime) async {
  var androidPlatformChannelSpecifics = AndroidNotificationDetails(
    'alarm_notif',
    'alarm_notif',
    'Channel for Alarm notification',
    importance: Importance.max,
    priority: Priority.high,
    ongoing: true,
    autoCancel: false,
    icon: 'clock', //codex_logo
    sound: RawResourceAndroidNotificationSound('guitar'),
    largeIcon: DrawableResourceAndroidBitmap('clock'),
    fullScreenIntent: true,
    enableLights: true,
  );

**Comment by MaikuB** [comment] 2020-12-26 12:39
The way the sound behaves is as intended as it's an Android behaviour and not to do with plugin functionality. Please refer to readme and example app in the repo as support for full screen intent is there

**Comment by KianuPark** [comment] 2020-12-27 23:48
> The way the sound behaves is as intended as it's an Android behaviour and not to do with plugin functionality. Please refer to readme and example app in the repo as support for full screen intent is there

it means there is no bug right? I have to search more information though thanks

**Comment by MaikuB** [comment] 2020-12-27 23:52
Correct, no bug here. The plugin is just a wrapper for calling native APIs so you would run into the same behaviour if you wrote the calls yourself

**Comment by MaikuB** [comment] 2020-12-30 14:03
Closing this as there's no bug

**Closed by MaikuB** 2020-12-30 14:03 UTC
