### ISSUE TITLE
Notification in Ios is getting dismissed on trayed down or trayed up.

### ISSUE THREAD

**Issue by jaiswalshubham84** [MaikuB/flutter_local_notifications#134] opened 2018-12-11 13:47 UTC
![transition](https://user-images.githubusercontent.com/32263293/49804731-5ee90600-fd79-11e8-8da7-975a4faf0418.gif)

**Comment by MaikuB** [comment] 2018-12-11 20:48
can't reproduce what you've shown there. perhaps you've made some changes that is causing that to happen as the notification from the original example app still seems to stay as per the capture you've shown.

**Comment by MaikuB** [comment] 2019-01-10 08:06
Closing this since it couldn't be reproduced. If you have more details on how to do so then feel free to reopen

**Closed by MaikuB** 2019-01-10 08:06 UTC

**Comment by jaiswalshubham84** [comment] 2019-05-13 08:30
this was happening because of firebase_messaging,
after removing it, it stops occurring, 
but now i need firebase_messaging. Can this issue can be fixes somehow.

**Comment by MaikuB** [comment] 2019-05-13 09:53
Hard to say as I don't know exactly what is causing the issue. Perhaps it's something to do with firebase. There are known issues with integrating firebase as well. In the animation you've shown it looked like the notification that disappears is the one that is coming from firebase (correct me if I'm wrong). It doesn't look like the local notification is the one that got dismissed.

**Comment by jaiswalshubham84** [comment] 2019-05-13 10:08
No, the notification which is disappeared was In-app notification from flutter_local_notifications package.
firebase messaging alert are working fine as usual.

**Comment by edisonpagtakhan** [comment] 2020-02-06 07:24
@MaikuB I'm also experiencing the same issue. The notification disappears when I try to open the notification center while the app is in foreground.

**Comment by MaikuB** [comment] 2020-02-06 07:43
Please generate a minimal app that can reproduce the problem then and provide a link to the repository

**Comment by edisonpagtakhan** [comment] 2020-02-06 10:34
https://github.com/edisonpagtakhan/local_notifications please use this repo. It seems like it has something to do with `firebase_messaging`. I already used your fork for this library. I didn't configure android since I'm just having issues with ios

**Comment by edisonpagtakhan** [comment] 2020-02-06 10:46
![ezgif com-optimize](https://user-images.githubusercontent.com/9381939/73930069-e942e080-4910-11ea-94d4-c348d8140d5e.gif)

**Comment by MaikuB** [comment] 2020-02-08 01:34
Thanks but this is an issue with the `firebase_messaging` plugin. I'd suggest raising it on their repository https://github.com/FirebaseExtended/flutterfire

**Comment by MaikuB** [comment] 2020-02-08 03:03
Looks like there is an issue related to this already https://github.com/FirebaseExtended/flutterfire/issues/114

**Comment by nemoryoliver** [comment] 2020-09-23 05:58
Following for updates...
