### ISSUE TITLE
iOS: getNotificationAppLaunchDetails() swallows launch notification and conflicts with firebase_messaging getInitialMessage()

### ISSUE THREAD

**Issue by acoutts** [MaikuB/flutter_local_notifications#1147] opened 2021-04-29 15:57 UTC
**Describe the bug**

If you include the latest `firebase_messaging` with `flutter_local_notifications`, and try to call `getInitialMessage()` from firebase messaging, then it always returns null.

But if you also call `FlutterLocalNotificationsPlugin().getNotificationAppLaunchDetails()` after calling `getInitialMessage()`, then the firebase lib is able to see the launch notification.

What's strange is now if I remove the `getNotificationAppLaunchDetails`, firebase's `getInitialMessage` is working again. I'm not sure how to break it again now.

**To Reproduce**

1. Add `firebase_messaging` and `flutter_local_notifications` to your app
2. Receive a push notification
3. Force close the app
4. Launch the app by tapping on a notification

**Expected behavior**

These 2 libs should be able to exist together.

**Sample code to reproduce the problem**

**Comment by MaikuB** [comment] 2021-05-02 04:39
What platform do you see this behaviour on and did this use to work for you before? I would guess you're seeing this on iOS and from memory, this all use to work as I submitted the initial PR to get both plugins to work together on iOS. There's been no changes in this plugin around this area so if you're seeing things break now, you may have to open an issue on the repository where firebase_messaging is hosted. At a glance, it seems like they've changed how things work on the iOS side. I don't know the reasons why but if the result is that this plugin needs further changes then note that I don't have the knowledge make further changes for both plugins to work together.

**Comment by MaikuB** [comment] 2021-05-24 10:34
As I've not received further details on this, I'll be closing the issue. Furthermore I've tried reproducing this myself using the latest plugin versions and didn't run into the problem described so perhaps there's an issue with how you've configured the app. It is difficult to tell given there's no link to a minimal app that can reproduce the problem. I have noticed the example app in the `firebase_messaging` repository didn't have the changes to assign the notification centre delegate as described in this plugin's readme. Not sure if you happened to followed that and ended up with the issue you've described. Feel free to re-open you can provide a minimal app that can reproduce the issue

**Closed by MaikuB** 2021-05-24 10:34 UTC
