### ISSUE TITLE
XCode Build Error, Module 'flutter_local_notifications' not found

### ISSUE THREAD

**Issue by apegeek** [MaikuB/flutter_local_notifications#406] opened 2019-12-26 03:24 UTC

**Comment by MaikuB** [comment] 2019-12-26 06:56
Will need more info on how to reproduce the problem, which version of Flutter you're using and version of the plugin, particularly when there's been no reports on this before. Have you tried cleaning your build? I created a brand new app, pulled down the plugin and it built successfully

**Comment by MaikuB** [comment] 2019-12-31 22:32
Closing due to lack of further information and response

**Closed by MaikuB** 2019-12-31 22:32 UTC
