### ISSUE TITLE
Android 12 no notification display

### ISSUE THREAD

**Issue by Babwenbiber** [MaikuB/flutter_local_notifications#1497] opened 2022-02-19 12:37 UTC
**Describe the bug**

Notifications get received correctly. But on Android 12 the notifications get not displayed correctly when the app is in background or in foreground. When the display is off, then I can see the notification in the locked screen and I can always see the notifications in the native messages screen.
I figured out that there were some new guidelines for Android 12 regarding notification displays (https://developer.android.com/about/versions/12/behavior-changes-12).

**To Reproduce**

1. Use android 12 smartphone
2. Checkout example repo
3. Schedule or show notification
4. Smartphone vibrates, but doesn't display the notification

**Expected behavior**
Smartphone vibrates and displays the notification as for other android versions or ios.

**Comment by MaikuB** [comment] 2022-02-21 07:40
Those Android 12 changes don't relate to what you've described and I don't have the issue you've described on Android 12 devices (note I have a Pixel 6). You'll need to provide more info on exactly what the issue is and how it can be reproduced. Have you tried with an Android 12 emulator to check the behaviour on stock Android? This is something you should check and if possible, provide a recording for.

**Comment by Babwenbiber** [comment] 2022-02-25 13:57
Sorry for the sloppy description.
I already described the steps to reproduce.
Here are my environment specific infos:

```
flutter doctor -v             
[✓] Flutter (Channel stable, 2.10.1, on macOS 11.6.2 20G314 darwin-x64, locale de-DE)
    • Flutter version 2.10.1 at /Users/xxx/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (2 weeks ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • Pixel 6 (mobile) • 18161FDF6001RL • android-arm64  • Android 12 (API 31)
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 98.0.4758.109

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

Here is a record as well. 
What you don't see in this clip is that the phone indeed vibrates on the notifications, but I don't see its display. Same behavior on scheduling and then putting app in background.

Other non flutter apps with notifications like whatsapp work as expected.

Let me know if you need more infos.

https://user-images.githubusercontent.com/15171332/155727195-21146e87-d832-4075-97e8-719121a8ae4d.mp4

**Comment by MaikuB** [comment] 2022-02-25 14:14
This isn't a bug. It's behaving as instructed so will be closing this issue. I know what you're referring to and you'll need to do further reading. See https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#displaying-a-notification. This plugin is intended to provide access to native APIs so understanding how they work is essential

**Closed by MaikuB** 2022-02-25 14:14 UTC
