### ISSUE TITLE
Receive notification twice when schedule for all weekdays

### ISSUE THREAD

**Issue by bigbang489** [MaikuB/flutter_local_notifications#1293] opened 2021-08-21 09:09 UTC
I set the reminders for all weekdays, each days with different message
my code:

```
for (int i = 0; i < 7; i++) {
      scheduledDateTime = scheduledDateTime.add(Duration(days: i));
      String quote = quotes.isEmpty ? '' : quotes[i % quotes.length];
      await scheduleNotification(
        id: msgId++,
        title: translator.dontForgetToAddTodaysTransactions,
        body: quote,
        time: scheduledDateTime,
        matchDateTimeComponents: DateTimeComponents.dayOfWeekAndTime,
      );
    }

.....
static Future scheduleNotification(
      {required int id,
      required String title,
      required String body,
      required DateTime time,
      DateTimeComponents? matchDateTimeComponents}) {
    return notificationService.zonedSchedule(id, title, body,
        tz.TZDateTime.from(time, tz.local), generalNotificationDetails,
        uiLocalNotificationDateInterpretation:
            UILocalNotificationDateInterpretation.absoluteTime,
        androidAllowWhileIdle: true,
        matchDateTimeComponents: matchDateTimeComponents);
  }
```

**Expected behavior**
Receive one notification each day

**Actual behavior**
In the first day, I receive 2 notifications, the first message and the last message.

**Comment by MaikuB** [comment] 2021-08-30 09:58
Tried reproducing this by modifying the example app by updating the daily 10 am notification example with the following code

```
  Future<void> _scheduleDailyTenAMNotification() async {
    var next = tz.TZDateTime.now(tz.local).add(const Duration(seconds: 5));
    for (int i = 0; i < 7; i++) {
      var x = next.add(Duration(days: i));
      await flutterLocalNotificationsPlugin.zonedSchedule(
          i,
          'daily scheduled notification title $i',
          'daily scheduled notification body $i',
          x,
          const NotificationDetails(
            android: AndroidNotificationDetails(
                'daily notification channel id',
                'daily notification channel name',
                'daily notification description'),
          ),
          androidAllowWhileIdle: true,
          uiLocalNotificationDateInterpretation:
              UILocalNotificationDateInterpretation.absoluteTime,
          matchDateTimeComponents: DateTimeComponents.dayOfWeekAndTime);
    }
  }
```

Was not able to reproduce the problem described so will be closing this. Feel free to re-open if you can provide a link to a minimal app that can reproduce the issue and the dates passed to the plugin are as expected

**Closed by MaikuB** 2021-08-30 09:58 UTC
