### ISSUE TITLE
Crash on FlutterLocalNotificationsPlugin.java line 392

### ISSUE THREAD

**Issue by rtokun** [MaikuB/flutter_local_notifications#1685] opened 2022-08-31 10:07 UTC
Facing crashes on android devices in the boot receiver, during rescheduling of the notifications. Looks like the `id` is null.

Plugin version: `9.7.0`
Affected android versions: `10/11/12`
Stacktrace:
```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4238)
       at android.app.ActivityThread.access$1700(ActivityThread.java:274)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2113)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.scheduleNotification(FlutterLocalNotificationsPlugin.java:392)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.rescheduleNotifications(FlutterLocalNotificationsPlugin.java:168)
       at com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver.onReceive(ScheduledNotificationBootReceiver.java:19)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4229)
       at android.app.ActivityThread.access$1700(ActivityThread.java:274)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2113)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by MaikuB** [comment] 2022-09-03 10:18
It's not the id itself but the notification that is null. This error is typically indicative of running a release build of the app but the release build configuration steps required by the plugin haven't been done. Have you checked that you've done so? Please see https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration for what I mean. If you have done so but still have the issue then please include a link to a repo hosting a minimal app that can reproduce the issue. Note that when I say minimal, I don't mean a copy of the exact app you're welcome on but an app where the minimal amount of steps have been done to reproduce the issue. These steps should also include the setup steps required by the plugin that have been documented

**Comment by MaikuB** [comment] 2022-12-03 00:31
Closing due to lack of further response with more information that was requested

**Closed by MaikuB** 2022-12-03 00:31 UTC
