### ISSUE TITLE
iOS: notification disappear from system tray after 1 second

### ISSUE THREAD

**Issue by dprophete** [MaikuB/flutter_local_notifications#641] opened 2020-05-26 22:09 UTC
On iOS, when you receive a local notification and the user doesn't click on it, it goes into the system tray (which is expected). The problem is when you pull down the system tray to see the existing notifications, the local notification goes away after less than a second without any user interaction.

I am using the code from the example in the repo to fire my notification:
```
          var androidPlatformChannelSpecifics = AndroidNotificationDetails(
              'your channel id',
              'your channel name',
              'your channel description',
              importance: Importance.Max,
              priority: Priority.High,
              ticker: 'ticker');
          var iOSPlatformChannelSpecifics = IOSNotificationDetails();
          var platformChannelSpecifics = NotificationDetails(
              androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
          await _flutterLocalNotificationsPlugin.show(
              1, title, body, platformChannelSpecifics,
              payload: url);
```

And I am seeing this:
![disappearing-notification](https://user-images.githubusercontent.com/518393/82954879-e77b5680-9fad-11ea-9492-07b8734280dc.gif)

As you can see, the notification shows up properly within the app, then goes away (as expected). But when I pull down system tray, it goes away without me doing anything.

note1: this is a recording of the simu, but I see the exact same behavior on the device (iphone 10)
note2: this works properly on android (it stays in the system tray)

**Comment by MaikuB** [comment] 2020-05-26 22:21
There was an issue reported on this before https://github.com/MaikuB/flutter_local_notifications/issues/134

It's not mentioned in your post but are you using the `firebase_messaging` plugin as well? There's an issue on that plugin around that.

**Comment by dprophete** [comment] 2020-05-27 07:56
Ah yes, sorry @MaikuB, I should have mentioned that.

I am indeed using `firebase_messaging`. The idea being that when I want notifications received when the app is in the foreground to behave like when the app is in the background. So as soon as firebase received a foreground notification, I am sending it back with `flutter_local_notifications`. 

I'll follow up on #134 to see if I can get a working solution there.

Thanks a bunch.

**Comment by MaikuB** [comment] 2020-05-27 07:59
The problem is with `firebase_messaging` so changes need to be done there. They are clearing out badges/notifications when the app returns to the foreground. You'll need to follow the issue filed against `firebase_messaging` for updates.  With the lack of a fix for `firebase_messaging`, you may need to consider using a fork. This isn't something that can be resolved in `flutter_local_notifications` so I'm going to close this

**Closed by MaikuB** 2020-05-27 07:59 UTC
