### ISSUE TITLE
Android not showing Heads-Up-Notification, only dot 

### ISSUE THREAD

**Issue by DieGlueckswurst** [MaikuB/flutter_local_notifications#1145] opened 2021-04-28 10:32 UTC
**Describe the bug**

Notifications on Android only show the Dot and not a Heads-Up-Notification, even though 'importance' and 'priority' is set.

**To Reproduce**

1. Init like in the Documentation
2. sent an instant notification with `.show` 
3. works fine on iOS, but no Heads-Up on Android

**Expected behavior**
Heads-Up-Notification should appear on Android

**Sample code to reproduce the problem**
```
Future initialize() async {
    tz.initializeTimeZones();
    FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
        FlutterLocalNotificationsPlugin();

    AndroidInitializationSettings androidInitializationSettings =
        AndroidInitializationSettings('app_icon');

    IOSInitializationSettings iosInitializationSettings =
        IOSInitializationSettings();

    final InitializationSettings initializationSettings =
        InitializationSettings(
            android: androidInitializationSettings,
            iOS: iosInitializationSettings);

    await flutterLocalNotificationsPlugin.initialize(
      initializationSettings,
    );



  //Instant Notifications
  Future instantNofitication() async {
    var android = AndroidNotificationDetails(
        'id', 'chanel', 'description',
        importance: Importance.high, 
        priority: Priority.high,);

    var ios = IOSNotificationDetails();

    var platform = new NotificationDetails(android: android, iOS: ios);

    await _flutterLocalNotificationsPlugin.show(
      0,
      'Medikamentenerinnerung',
      'Aspirin',
      platform,
      payload: 'Welcome to demo app',
    );
  }
```

**Comment by MaikuB** [comment] 2021-05-02 05:00
1. Can you include the details of the device (including the Android version) you used?
2. What is the output of running `flutter doctor -v`
3. Have you tried reproducing this problem in another app such as by forking/modifying/running the example app?

There are certain conditions mentioned in the official docs for heads-up notification to appear (see https://developer.android.com/guide/topics/ui/notifiers/notifications#Heads-up) so you'll need to ensure that the app is meeting those conditions to do so. Importance is also tied to notification channels so if at one point and generally, the details of a notification channel cannot change once set.  The default importance level for a channel *isn't* high so if at one point you left it at the defaults with the same notification channel id etc but then changed the importance level, you won't see any changes

**Comment by DieGlueckswurst** [comment] 2021-05-02 21:57
That might actually be it. I will try it in the next couple of days and let you know. Thanks for your help!

**Comment by MaikuB** [comment] 2021-05-10 13:13
Any updates? I'll be closing this soon if there aren't any updates. If you suspect you've run into a bug then I'll need a link to repository that has a minimal app that can reproduce the issue

**Comment by hyouuu** [comment] 2021-05-16 19:05
Hi @MaikuB I'm facing the same issue, but it seems to be caused by the Banners notification setting for the app is turned off by default. I have:
```
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.ACCESS_NOTIFICATION_POLICY" />
```
in `AndroidManifest` - do you know if I need other permissions to turn on the banner?

**Comment by hyouuu** [comment] 2021-05-16 19:14
Actually found that although I scheduled notification using Importance.HIGH, I didn't add it when initializing the plugin - now problem solved. Thanks for explaining the details!

**Comment by MaikuB** [comment] 2021-05-21 09:15
Closing due to lack of response from OP and issue was most likely due to a configuration issue

**Closed by MaikuB** 2021-05-21 09:15 UTC

**Comment by DieGlueckswurst** [comment] 2021-05-25 15:54
@hyouuu Hi, how is it working for you? What do you mean by 'I didn't add it when initializing the plugin' ?

**Comment by DieGlueckswurst** [comment] 2021-05-25 15:55
@MaikuB I deinstalled the app, changed the Channel name, but the Notification is still only showing the dot.

**Comment by hyouuu** [comment] 2021-05-25 18:32
@DieGlueckswurst when you init the channel for the first time before scheduling notifications, you also need to provide the importance param

**Comment by DieGlueckswurst** [comment] 2021-05-25 21:12
@hyouuu  but what do you need by "init"? have a look at my code sample. What do I need to change?
