### ISSUE TITLE
Conflicts when using plugin from both background isolate and foreground

### ISSUE THREAD

**Issue by athornz** [MaikuB/flutter_local_notifications#278] opened 2019-07-30 09:49 UTC
I'm using a headless flutter view to run dart code in the background. I've found when registering this plugin on the background runner, trying to use it in the foreground no longer works.

One of the reasons for this seems to be that a lot of the plugins state variables are static rather than instance variables.

**Comment by MaikuB** [comment] 2019-07-30 10:26
Which state are you referring to that is static that you think is causing the issue? Unless I've missed something, the majority of the static members are just constants and don't actually carry state. If you have a solution for the problem then a PR is welcome though I'm wondering if you're running into the issue I've mentioned here. Bit of a different case as I was attempting headless execution but that also uses a different isolate

https://github.com/flutter/flutter/issues/23904

Perhaps you'll need to look at messaging passing as well though it's not something I've really looked into

**Comment by athornz** [comment] 2019-07-30 20:04
These variables are the ones I'm referring to:

```
FlutterMethodChannel* channel;
bool appResumingFromBackground;
bool displayAlert;
bool playSound;
bool updateBadge;
bool initialized;
NSUserDefaults *persistentState;
NSObject<FlutterPluginRegistrar> *_registrar;
```

In particular, the channel will get overwritten as soon as this plugin is registered with a different registrar.

**Comment by MaikuB** [comment] 2019-07-30 20:54
Thanks will try to look at your PR later. Just checking though, it solves the problem you're having?

**Comment by athornz** [comment] 2019-07-30 20:59
Not completely, I think the remaining issues will be solved once the Flutter PR you mentioned is merged.

**Comment by MaikuB** [comment] 2019-07-30 21:05
The PR I mentioned before (in a PR you tried to submit) is around delegates though so seems separate from the issue you're having. Did you mean to refer to the issue I've linked around dealing with platform channels and isolates?

**Comment by athornz** [comment] 2019-07-30 21:18
Yes the delegate PR: https://github.com/flutter/engine/pull/9864

So basically, this PR fixes my issue with registering FlutterLocalNotifications in a background isolate preventing the foreground isolate from working.

It's not a complete fix though as FlutterLocalNotifications can't be used from the background isolate. 

It can be registered (via GeneratedPluginRegistrant), but not used. 

If `initialize` is called on the background isolate, the UNNotificationCenter delegate gets set to the background instance of FlutterLocalNotifications, and the foreground instance will no longer work.

Once the Flutter PR is merged though, multiple plugins should be able to be delegates for UNNotificationCenter and this should solve the issue.

Does that sound right?

**Comment by MaikuB** [comment] 2019-07-31 09:44
Ah I see what you mean now, didn't make the connection between the difference instances and how they're assigned as the delegate before

**Comment by Henry-Keys** [comment] 2019-09-20 12:34
Now i do understand why, thanks @MaikuB.
Just got to wait until Flutter team solves it.

**Comment by MaikuB** [comment] 2019-09-20 12:51
You may want to try running off a fork where the plugin doesn't register itself as a `UNUserNotificationCenterDelegate` and try the steps mentioned in https://github.com/flutter/flutter/issues/22099#issuecomment-532884756 as this may actually work on stable based on my own findings that I posted as a reply (see https://github.com/flutter/flutter/issues/22099#issuecomment-533189179. The only thing is you might get callbacks triggered more than once

**Comment by MaikuB** [comment] 2019-11-17 08:38
@athornz any chance you'll be able to try out my https://github.com/MaikuB/flutter_local_notifications/tree/0.9.0 to see if the problem is still there? You may need to switch to dev for it to work. It relies on the changes around the `UNUserNotificationCenterDelegate` that have made to other channels. With the changes done by the Flutter team, you'll need to modify your iOS code to register the `UNUserNotificationCenterDelegate` as the plugin will no longer do this.

**Comment by MaikuB** [comment] 2019-12-18 11:27
I've pushed out a new release that now requires developers update their app to register the `UNUserNotificationCenterDelegate`. As such I don't believe this problem exists anymore. Will close this but feel free to re-open if this is still an issue

**Closed by MaikuB** 2019-12-18 11:27 UTC
