### ISSUE TITLE
issue in relase build

### ISSUE THREAD

**Issue by imbryan1999** [MaikuB/flutter_local_notifications#1982] opened 2023-05-04 05:07 UTC
in release build the notification click action is not working. when we click the notification it just opens the app not the particuler screen according to its click action path and when i run it on device directly through android studio then everything is working

**Comment by MaikuB** [comment] 2023-05-05 09:13
My guess is you didn't add the annotation mentioned in https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#notification-actions

**Comment by MaikuB** [comment] 2023-06-09 12:20
Closing due to lack of further response. If you believe there's a bug then you can re-open the issue but please ensure you provide a link to a repository with a minimal app that can reproduce the issue

**Closed by MaikuB** 2023-06-09 12:20 UTC
