### ISSUE TITLE
Cannot run on Flutter 1.22 

### ISSUE THREAD

**Issue by markathomas** [MaikuB/flutter_local_notifications#854] opened 2020-10-16 06:52 UTC
**Describe the bug**
After upgrade to Flutter 1.22 and plugin 2.0.1 code does not run

**To Reproduce**
1. Update Flutter to 1.22
2. Update plugin to 2.0.1
3. Fix any compilation errors for new version

**Expected behavior**
App runs normally

```
E/flutter ( 5997): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel dexterous.com/flutter/local_notifications)
E/flutter ( 5997): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter ( 5997): <asynchronous suspension>
E/flutter ( 5997): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 5997): #2      AndroidFlutterLocalNotificationsPlugin.initialize (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:80:27)
E/flutter ( 5997): #3      FlutterLocalNotificationsPlugin.initialize (package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:122:13)
E/flutter ( 5997): #4      NotificationHelper.initNotifications (package:boxview_mobile_flutter/services/notification_helper.dart:21:37)
E/flutter ( 5997): #5      new Routes (package:boxview_mobile_flutter/routes.dart:49:26)
E/flutter ( 5997): #6      main (package:boxview_mobile_flutter/main.dart:4:7)
E/flutter ( 5997): #7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
E/flutter ( 5997): #8      _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 5997): #9      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 5997): #10     _runZoned (dart:async/zone.dart:1630:10)
E/flutter ( 5997): #11     runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter ( 5997): #12     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
E/flutter ( 5997): #13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter ( 5997): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by MaikuB** [comment] 2020-10-16 07:01
Please provide a minimal sample app that reproduces the problem as requested in the bug report template. I've been running the example app on Flutter 1.22 and don't see the issue you're reporting. Note that I've seen reports of this that isn't specific to this plugin where it gets solved after like running `flutter clean` and then rebuild the app. Have you tried that yet?

**Comment by markathomas** [comment] 2020-10-16 07:17
Yes I have numerous times.  It appears to be an issue with platform_flutter_local_notifications.dart lines 63-69

```
Future<bool> initialize(AndroidInitializationSettings initializationSettings,
      {SelectNotificationCallback onSelectNotification}) async {
    _onSelectNotification = onSelectNotification;
    _channel.setMethodCallHandler(_handleMethod);
    return await _channel.invokeMethod(
        'initialize', initializationSettings.toMap());
  }
```

where you're calling initialize on the _channel yet there is no switch statement for this method name

**Comment by MaikuB** [comment] 2020-10-16 07:22
No, it is there and there are others that have already updated to use the latest version without issues for example, https://github.com/jesusrp98/spacex-go uses 2.0.0+1 though shouldn't matter for this issue.

You're going to need to post a link to repo to reproduce this issue. For all I know, the error is more to do with other changes specific to how you use the plugin in your app after you updated flutter

**Comment by markathomas** [comment] 2020-10-16 23:11
I think you're right as after deferring initialization of this plugin all sorts of others failed in the same way.  Do you have any idea what might cause this?  I ran a flutter clean, did a fresh flutter install, removed my pub cache, etc. and nothing.

**Comment by MaikuB** [comment] 2020-10-18 03:07
I was going to say I've seen case where the pub cache was corrupted and fixing it solved the issue for others but you've already done so and given you still haven't provided an app to reproduce the issue then I don't know. The only other thing that comes to mind if your app was trying to run code that uses plugins in the background. There use to be steps involved for that though I'm not sure if that's still the case with the v2 Android embedding changes nor do I know what's involved. If that is indeed what your app is doing then you go one of the other places listed at https://flutter.dev/community to get more help.

Closing this since no minimal app has been provided and if its indeed to do with background execution then it's not something I can help with as others in the community would know more

**Closed by MaikuB** 2020-10-18 03:07 UTC
