### ISSUE TITLE
Upcoming Restrictions on USE_FULL_SCREEN_INTENT permission

### ISSUE THREAD

**Issue by kunaldigi** [MaikuB/flutter_local_notifications#2342] opened 2024-06-13 05:13 UTC
You are receiving this email because you are using the USE_FULL_SCREEN_INTENT permission in your app and there are upcoming platform changes you should be prepared for. To prevent ad spam and credential phishing, only apps that have calling or alarm functionalities will have the permission enabled by default. Otherwise, you must get user permission to use the USE_FULL_SCREEN_INTENT permission.

The use of full-screen intent notifications is intended to share high-priority messages that require the user's immediate attention. All developers using this permission are required to complete the Play Console declaration starting May 31, 2024, to indicate if your app has a permitted core functionality and qualifies for default enablement of the USE_FULL_SCREEN_INTENT permission. Starting October 31, 2024, all apps that did not complete the declaration or have not been approved for default enablement, will need to surface a prompt to users to grant permission on new installs on devices running Android 14 or above,and adjust the app experience gracefully if permission is denied.

So what can do??

**Comment by cristian1980** [comment] 2024-06-17 09:58
This is probably a duplicate of #2335

**Comment by MaikuB** [comment] 2024-06-19 12:16
@cristian1980 it's potentially a duplicate

@kunaldigi does your app actually need to use full screen intents and what version of the plugin are you using? Asking in case this is more of an issue that your app doesn't need to use the permission and it's more of a problem where you haven't updated to a later version of the plugin and make the appropriate changes in your app

**Comment by bagusandrewijaya** [comment] 2024-07-16 02:56
same problem i will try dependency latest version flutter_local_notifications: ^17.2.1+2

**Comment by MaikuB** [comment] 2024-08-10 05:43
Closing due to lack of response from OP and issue is most likely from not having updated to a newer version of the plugin. Feel free to reopen if that is not the case but if you do so, please include a link to a repo hosting a minimal app that can reproduce the problem

**Closed by MaikuB** 2024-08-10 05:43 UTC
