### ISSUE TITLE
INVALID_ICON

### ISSUE THREAD

**Issue by shinewanna** [MaikuB/flutter_local_notifications#1134] opened 2021-04-23 05:41 UTC
I want to show network image in local notification. So i save the network image to device first and pass the saved path in icon parameter. It's throw INVALID_ICON error.

<details><summary>
logs</summary>
PlatformException(INVALID_ICON, The resource /data/user/0/com.chocholay.zay/app_flutter/693519178 could not be found. Please make sure it has been added as a drawable resource to your Android head project., null, null)</details>

**Sample code to reproduce the problem**
```dart
Future<String> saveImage(BuildContext context, Image image) {
  final completer = Completer<String>();

  image.image
      .resolve(ImageConfiguration())
      .addListener(ImageStreamListener((imageInfo, _) async {
    final byteData =
        await imageInfo.image.toByteData(format: ImageByteFormat.png);
    final pngBytes = byteData.buffer.asUint8List();
    final fileName = pngBytes.hashCode;
    final directory = await getApplicationDocumentsDirectory();
    final filePath = '${directory.path}/$fileName';
    final file = File(filePath);
    await file.writeAsBytes(pngBytes);

    completer.complete(filePath);
  }));

  return completer.future;
}

showNotification(RemoteMessage message, {context, icon}) async {
  var androidPlatformChannelSpecifics;
  if (icon != null) {
    final iconPath = await saveImage(context, icon);
    androidPlatformChannelSpecifics = AndroidNotificationDetails(
      'your channel id',
      'your channel name',
      'your channel description',
      importance: Importance.max,
      priority: Priority.high,
      icon: iconPath,
    );
  } else {
    androidPlatformChannelSpecifics = AndroidNotificationDetails(
      'your channel id',
      'your channel name',
      'your channel description',
      importance: Importance.max,
      priority: Priority.high,
    );
  }

  var iOSPlatformChannelSpecifics = IOSNotificationDetails();
  var platformChannelSpecifics = NotificationDetails(
      android: androidPlatformChannelSpecifics,
      iOS: iOSPlatformChannelSpecifics);
  String userName, body, id;
  if (message.data.isEmpty) {
    id = "1000";
  } else {
    id = message.data['uid'];
  }

  userName = message.notification.title;
  body = message.notification.body;

  await flutterLocalNotificationsPlugin.show(
      int.tryParse(id) ?? 1, userName, body, platformChannelSpecifics,
      payload: jsonEncode(message.data));
}
```

**Comment by MaikuB** [comment] 2021-04-25 00:31
As covered in the readme and error itself, the icon needs to be a Android drawable resource. You cannot use a remote image at all. Android doesn't support this, let alone the plugin.

Closing as this is working as intended

**Closed by MaikuB** 2021-04-25 00:31 UTC
