### ISSUE TITLE
Add action buttons to notification

### ISSUE THREAD

**Issue by rekonvald** [MaikuB/flutter_local_notifications#1071] opened 2021-03-05 22:18 UTC
Hi!

We need to add action buttons to notifications.
Can this functionality be added to local notifications plugin, please

Thank you

**Comment by MaikuB** [comment] 2021-03-07 02:02
Closing as duplicate of https://github.com/MaikuB/flutter_local_notifications/issues/17. It'd be much appreciated if you can look to see if an issue exists before opening a new one

**Closed by MaikuB** 2021-03-07 02:02 UTC
