### ISSUE TITLE
Behavior with Grouped Notifications 

### ISSUE THREAD

**Issue by luisms89** [MaikuB/flutter_local_notifications#260] opened 2019-07-08 10:07 UTC
I am trying to understand how grouped notifications work in this plugin. I dowloaded the example, i run it in my emulator (running Android 9) and it works as expected. But, if I remove the following lines of code, the notifications are not anymore being grouped.

```
// create the summary notification required for older devices that pre-date Android 7.0 (API level 24)
    var lines = List<String>();
    lines.add('Alex Faarborg  Check this out');
    lines.add('Jeff Chang    Launch Party');
    var inboxStyleInformation = InboxStyleInformation(lines,
        contentTitle: '2 messages', summaryText: 'janedoe@example.com');
    var androidPlatformChannelSpecifics = AndroidNotificationDetails(
        groupChannelId, groupChannelName, groupChannelDescription,
        style: AndroidNotificationStyle.Inbox,
        styleInformation: inboxStyleInformation,
        groupKey: groupKey,
        setAsGroupSummary: true);
    var platformChannelSpecifics =
        NotificationDetails(androidPlatformChannelSpecifics, null);
    await flutterLocalNotificationsPlugin.show(
        3, 'Attention', 'Two messages', platformChannelSpecifics);

```

Its weird as if I leave the example as it is, shows the two first notification grouped and not the third notification (the summary one). If I remove the 3th notification (the summary one with id 3), it shows the two first notifications without grouping.

I read that the summary is needed for older devices but my problem is that the notifications are not pushed all at the same time as in the example. Should i create one dummy summary every time I push a notification?

Thanks a lot,

Luis

**Comment by MaikuB** [comment] 2019-07-08 10:24
I think your question is a duplicate of others raised here (e.g. https://github.com/MaikuB/flutter_local_notifications/issues/240) but yes you'll need to create a summary notification

**Comment by luisms89** [comment] 2019-07-08 10:29
Yes, I read that answer. My problem is that I am not creating all the notifications at once. They are schedule to be shown during the day so there is no place (unless I save the notifications that were pushed and not tapped) where I can create a summary notifications. 

So my question is if it is fine to schedule a dummy summary notification every time I schedule a real notification in the same date and time.

Thanks!

Luis

**Comment by MaikuB** [comment] 2019-07-08 10:48
I'd imagine that should work, you're probably in the best position to try it out and see. Not sure what you're trying to display but you may need to consider putting useful content in the summary notification as it could be visible on older Android versions

**Comment by luisms89** [comment] 2019-07-08 10:57
I just tried in my code and it does not work. When I use shcedule instead of show, the notifications are not grouped.

```
static scheduleNotification({
    FlutterLocalNotificationsPlugin plugin,
    DateTime dateTime,
    String unixDateTime,
    String title,
    String body,
    int id,
    String payload,
  }) async {
    var groupKey = 'com.android.example.MYAPP';
    var groupChannelId = 'Reminders channel';
    var groupChannelName = 'Reminders channel';
    var groupChannelDescription = 'All notifications  for Reminders';
    var androidPlatformChannelSpecifics = new AndroidNotificationDetails(
      groupChannelId,
      groupChannelName,
      groupChannelDescription,
      groupKey: groupKey,
      autoCancel: false,
      importance: Importance.High,
      priority: Priority.High,
      sound: 'slow_spring_board',
    );
    NotificationDetails platformChannelSpecifics =
        new NotificationDetails(androidPlatformChannelSpecifics, null);
    await plugin.schedule(id, title, body, dateTime, platformChannelSpecifics);

     var lines = List<String>();
    lines.add('You have pending reminders waiting for confirmation');
    var inboxStyleInformation = InboxStyleInformation(lines,
        contentTitle: 'Pending reminders', summaryText: 'Confirm pending events');
    var androidPlatformChannelSpecificsb = AndroidNotificationDetails(
        groupChannelId, groupChannelName, groupChannelDescription,
        style: AndroidNotificationStyle.Inbox,
        styleInformation: inboxStyleInformation,
        groupKey: groupKey,
        setAsGroupSummary: true);
    var platformChannelSpecificsb =
        NotificationDetails(androidPlatformChannelSpecificsb, null);
    await plugin.schedule(
        0, 'Pending reminders', 'Confirm your pending events', dateTime, platformChannelSpecificsb);
  }

```

I scheduled 4 notifications for 4pm, 5pm, 6pm and 7pm. I moved the clock, hour by hour so the notifications were shown one by one but they were not being grouped.

**Comment by MaikuB** [comment] 2019-07-09 13:50
I've modified the example and it seems to work just fine

```
var groupKey = 'com.android.example.WORK_EMAIL';
    var groupChannelId = 'grouped channel id';
    var groupChannelName = 'grouped channel name';
    var groupChannelDescription = 'grouped channel description';
    // example based on https://developer.android.com/training/notify-user/group.html
    var firstNotificationAndroidSpecifics = AndroidNotificationDetails(
        groupChannelId, groupChannelName, groupChannelDescription,
        importance: Importance.High,
        priority: Priority.High,
        sound: 'slow_spring_board',
        autoCancel: false,
        groupKey: groupKey);
    var firstNotificationPlatformSpecifics =
        NotificationDetails(firstNotificationAndroidSpecifics, null);
    await flutterLocalNotificationsPlugin.schedule(
        1,
        'Alex Faarborg',
        'You will not believe...',
        DateTime.now().add(Duration(seconds: 5)),
        firstNotificationPlatformSpecifics);
    // create the summary notification required for older devices that pre-date Android 7.0 (API level 24)
    var lines = List<String>();
    lines.add('Alex Faarborg  Check this out');
    lines.add('Jeff Chang    Launch Party');
    var inboxStyleInformation = InboxStyleInformation(lines,
        contentTitle: '2 messages', summaryText: 'janedoe@example.com');
    var androidPlatformChannelSpecifics = AndroidNotificationDetails(
        groupChannelId, groupChannelName, groupChannelDescription,
        style: AndroidNotificationStyle.Inbox,
        styleInformation: inboxStyleInformation,
        groupKey: groupKey,
        setAsGroupSummary: true);
    var platformChannelSpecifics =
        NotificationDetails(androidPlatformChannelSpecifics, null);
    await flutterLocalNotificationsPlugin.schedule(
        3,
        'Attention',
        'One message',
        DateTime.now().add(Duration(seconds: 5)),
        platformChannelSpecifics);
    var secondNotificationAndroidSpecifics = AndroidNotificationDetails(
        groupChannelId, groupChannelName, groupChannelDescription,
        importance: Importance.High,
        priority: Priority.High,
        sound: 'slow_spring_board',
        autoCancel: false,
        groupKey: groupKey);
    var secondNotificationPlatformSpecifics =
        NotificationDetails(secondNotificationAndroidSpecifics, null);
    await flutterLocalNotificationsPlugin.schedule(
        2,
        'Jeff Chang',
        'Please join us to celebrate the...',
        DateTime.now().add(Duration(seconds: 10)),
        secondNotificationPlatformSpecifics);

    // create the summary notification required for older devices that pre-date Android 7.0 (API level 24)

    await flutterLocalNotificationsPlugin.schedule(
        3,
        'Attention',
        'Two messages',
        DateTime.now().add(Duration(seconds: 10)),
        platformChannelSpecifics);
```

**Comment by MaikuB** [comment] 2019-07-09 13:51
I've also noticed that you've hardcoded the id of the summary notification. Are you checking to make that no other notification has used the same id?

**Comment by MaikuB** [comment] 2019-08-03 23:04
Closed due since there's been no further response

**Closed by MaikuB** 2019-08-03 23:04 UTC
