### ISSUE TITLE
NullPointerException Attempt to invoke virtual method 'int java.lang.Integer.intValue()

### ISSUE THREAD

**Issue by rtokun** [MaikuB/flutter_local_notifications#1237] opened 2021-07-22 07:38 UTC
We see this crash happens to our Android users. All the crashes happen when the app is in the background.
Plugin version 6.0.0.
Android versions 9-11.

Crash log:
```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4035)
       at android.app.ActivityThread.access$1400(ActivityThread.java:237)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1924)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7664)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.scheduleNotification(FlutterLocalNotificationsPlugin.java:329)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.rescheduleNotifications(FlutterLocalNotificationsPlugin.java:147)
       at com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver.onReceive(ScheduledNotificationBootReceiver.java:21)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4026)
       at android.app.ActivityThread.access$1400(ActivityThread.java:237)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1924)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7664)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by vimalmistry** [comment] 2021-07-25 14:18
Same Issue :(

**Comment by vimalmistry** [comment] 2021-07-25 16:08
[Solved]- Duplicate https://github.com/MaikuB/flutter_local_notifications/issues/220

please pin it.

**Comment by MaikuB** [comment] 2021-07-29 07:54
@rtokun has the release build configuration with Proguard rules etc been done properly?

@vimalmistry that issue you're referring is to do with not having setup the icon properly. There are links in the readme on understanding the Android resource system, statements to say the icon should be a drawable resource and a link to a complete example app to demonstrate

**Comment by uzumaki258** [comment] 2021-10-17 08:46
Same issue here:
But just for a few user
`Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3808)
       at android.app.ActivityThread.-wrap18(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2082)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7523)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setupNotificationChannel(FlutterLocalNotificationsPlugin.java:22)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:14)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java)
       at com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive(ScheduledNotificationReceiver.java:76)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3798)
       at android.app.ActivityThread.-wrap18(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2082)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7523)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)`

**Comment by Omar-Khaium** [comment] 2021-11-09 05:40
make sure you define the notification icon name while showing the notification, inside notification details. I had faced the same and was stuck for hours.
```
notificationsPlugin.show(
      DateTime.now().millisecond,
      message.notification?.title,
      message.notification?.body,
      NotificationDetails(
        android: AndroidNotificationDetails(
          channelId,
          channelName,
          icon: "ic_notification",
          priority: Priority.max,
          importance: Importance.max,
          enableVibration: true,
        ),
      ),
      payload: json.encode(message.data),
    );
```

**Comment by armandojimenez** [comment] 2021-12-11 01:10
I am getting the same error, but just for like 2 or 3 users

**Comment by armandojimenez** [comment] 2022-03-15 21:10
> make sure you define the notification icon name while showing the notification, inside notification details. I had faced the same and was stuck for hours.
> 
> ```
> notificationsPlugin.show(
>       DateTime.now().millisecond,
>       message.notification?.title,
>       message.notification?.body,
>       NotificationDetails(
>         android: AndroidNotificationDetails(
>           channelId,
>           channelName,
>           icon: "ic_notification",
>           priority: Priority.max,
>           importance: Importance.max,
>           enableVibration: true,
>         ),
>       ),
>       payload: json.encode(message.data),
>     );
> ```

Still seeing the same error even with icon param filled.

**Comment by TheMaverickProgrammer** [comment] 2022-09-19 00:32
> 

This solved it for me. Why isn't `android.smallIcon` returning the string for us? Also this should be in the docs or something. Thanks for helping us!

**Comment by TheMaverickProgrammer** [comment] 2022-09-19 00:32
> make sure you define the notification icon name while showing the notification, inside notification details. I had faced the same and was stuck for hours.
> 
> ```
> notificationsPlugin.show(
>       DateTime.now().millisecond,
>       message.notification?.title,
>       message.notification?.body,
>       NotificationDetails(
>         android: AndroidNotificationDetails(
>           channelId,
>           channelName,
>           icon: "ic_notification",
>           priority: Priority.max,
>           importance: Importance.max,
>           enableVibration: true,
>         ),
>       ),
>       payload: json.encode(message.data),
>     );
> ```

This solved it for me. Why isn't `android.smallIcon` returning the string for us? Also this should be in the docs or something. Thanks for helping us!

**Comment by dungnguyentri3110** [comment] 2023-01-04 03:30
> make sure you define the notification icon name while showing the notification, inside notification details. I had faced the same and was stuck for hours.
> 
> ```
> notificationsPlugin.show(
>       DateTime.now().millisecond,
>       message.notification?.title,
>       message.notification?.body,
>       NotificationDetails(
>         android: AndroidNotificationDetails(
>           channelId,
>           channelName,
>           icon: "ic_notification",
>           priority: Priority.max,
>           importance: Importance.max,
>           enableVibration: true,
>         ),
>       ),
>       payload: json.encode(message.data),
>     );
> ```

Thank your help. It work for me. For anyone don't know, you just add your icon on drawable from android/app/src/main/res/drawable/app_icon.png. The "app_icon" name you must put on "icon" params of AndroidNotificationDetails class. Like this AndroidNotificationDetails(icon: 'app_icon')

**Comment by codemicah** [comment] 2023-02-24 17:01
> 

Thank you so much! This saved me after being blocked for days.

**Comment by MaikuB** [comment] 2023-02-25 02:01
Closing this as OP hasn't provided further information and the rest of the messages in this thread here point to not looking into the docs linked in the readme to understand how resources work in Android

**Closed by MaikuB** 2023-02-25 02:01 UTC

**Comment by TheMaverickProgrammer** [comment] 2023-02-25 03:28
MaikuB blaming the people who have read the docs instead of just quietly closing the issue and maybe adding better error checkin in their API.

**Comment by ellet0** [comment] 2023-12-25 10:43
If anyone still facing the bug, all you have to do it is to define `AndroidNotificationDetails`
