### ISSUE TITLE
Using current local time for zonedSchedule()

### ISSUE THREAD

**Issue by DieGlueckswurst** [MaikuB/flutter_local_notifications#1152] opened 2021-05-02 21:55 UTC
**Describe the bug**

I am trying to use `zonedSchedule` inside my app, but I can not figure out how to get the current local time from `TZDateTime`, it is always giving me the `UTC`.  

**To Reproduce**
`final tz.TZDateTime now = tz.TZDateTime.now(tz.local);`

I thought this was supposed to give me the current time. However it is giving me the UTC Time. But I actually need CEST time. 

**Expected behavior**

I thought with `tz.local` I get current devices time ...

**Sample code to reproduce the problem**

`final tz.TZDateTime now = tz.TZDateTime.now(tz.local);`

**Comment by MaikuB** [comment] 2021-05-03 10:30
The APIs you are asking about belong to the [`timezone`](https://pub.dev/packages/timezone) package. The local notifications plugin uses the `timezone` package as it provides APIs for date/time objects in a specific timezone. You'd need to read its readme for details on how it works. It was mentioned readme for the local notifications plugin state [here](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#scheduling-a-notification) that neither package will provide info on the device's timezone and that you'd need to use platform channels or another plugin to do so. 

Closing this as it's not a bug with this plugin

**Closed by MaikuB** 2021-05-03 10:30 UTC
