### ISSUE TITLE
After adding code in AppDelegate.swift notification are not tappable now 

### ISSUE THREAD

**Issue by lalit3102** [MaikuB/flutter_local_notifications#1588] opened 2022-05-05 16:36 UTC
```
if #available(iOS 10.0, *) {
            UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
        }
```

**Comment by MaikuB** [comment] 2022-05-19 03:43
Can you provide a link to a repo with a minimal app that can reproduce the issue?

**Comment by MaikuB** [comment] 2022-06-25 23:01
Closing due to lack of further response

**Closed by MaikuB** 2022-06-25 23:01 UTC
