### ISSUE TITLE
Crash with class java.time.ZoneId not found

### ISSUE THREAD

**Issue by softkot** [MaikuB/flutter_local_notifications#1716] opened 2022-09-23 06:14 UTC
After plugin upgrade up to 11.0.0 found this new very often crash type on firebase reports. 
```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/ZoneId;
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.getNextFireDateMatchingDateTimeComponents(FlutterLocalNotificationsPlugin.java:1196)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedSchedule(FlutterLocalNotificationsPlugin.java:1454)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:1308)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
       at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
       at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java:319)
       at io.flutter.embedding.engine.dart.DartMessenger.$r8$lambda$TsixYUB5E6FpKhMtCSQVHKE89gQ(DartMessenger.java)
       at io.flutter.embedding.engine.dart.DartMessenger$$InternalSyntheticLambda$0$5dd8b6f7959f08bc8717eff7469e77e06ef5aed51cc0cee17f1e13794798223f$0.run(DartMessenger.java)
       at android.os.Handler.handleCallback(Handler.java:761)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6523)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

**Comment by MaikuB** [comment] 2022-09-23 08:39
Did you look at the changelog as you upgraded to a new major version? There were details related to this that were mentioned and requires applications to do more setup on the Android side

**Comment by softkot** [comment] 2022-09-23 08:56
> Did you look at the changelog as you upgraded to a new major version? There were details related to this that were mentioned and requires applications to do more setup on the Android side

Yes. I have. But let me double check if the latest chenges was rolled out to production and that depelndency was specified. 

    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'

I will back soon. Thanks.

**Comment by MaikuB** [comment] 2022-09-23 09:03
In case you missed it given that you've only mentioned pulling the dependency, note that it isn't the only step as there are other things mentioned [here](https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#gradle-setup).

**Comment by MaikuB** [comment] 2022-10-04 10:20
Closing due to lack of updates. If you have an update then feel free to re-open the issue but I'll also need a link to a repository hosting a minimal app that can reproduce the issue

**Closed by MaikuB** 2022-10-04 10:20 UTC

**Comment by jay-benzatine** [comment] 2022-12-28 09:57
Hello @MaikuB 

I'm still Facing the Same Issue

Flutter version 3.0.0
flutter_local_notifications: ^12.0.4

I'm using the above versions and this problem mostly occurs in android 6,7.

![image](https://user-images.githubusercontent.com/77785939/209793933-27cfb33e-127a-4477-99f4-fe0f807e902d.png)

**Comment by bigbang489** [comment] 2024-02-01 03:20
I face the same issue in the version 16.3.2:

`
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/ZoneId;
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.getNextFireDateMatchingDateTimeComponents(SourceFile)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedSchedule(SourceFile)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(SourceFile)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java)
       at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java)
       at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java)
       at android.os.Handler.handleCallback(Handler.java:761)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6617)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
Caused by java.lang.ClassNotFoundException: Didn't find class "java.time.ZoneId" on path: DexPathList[[zip file "/data/app/com.antcorp.moneyflow-2/base.apk", zip file "/data/app/com.antcorp.moneyflow-2/split_config.arm64_v8a.apk", zip file "/data/app/com.antcorp.moneyflow-2/split_config.en.apk", zip file "/data/app/com.antcorp.moneyflow-2/split_config.fr.apk", zip file "/data/app/com.antcorp.moneyflow-2/split_config.tvdpi.apk"],nativeLibraryDirectories=[/data/app/com.antcorp.moneyflow-2/lib/arm64, /data/app/com.antcorp.moneyflow-2/base.apk!/lib/arm64-v8a, /data/app/com.antcorp.moneyflow-2/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/com.antcorp.moneyflow-2/split_config.en.apk!/lib/arm64-v8a, /data/app/com.antcorp.moneyflow-2/split_config.fr.apk!/lib/arm64-v8a, /data/app/com.antcorp.moneyflow-2/split_config.tvdpi.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.getNextFireDateMatchingDateTimeComponents(SourceFile)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedSchedule(SourceFile)
       at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(SourceFile)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java)
       at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java)
       at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java)
       at android.os.Handler.handleCallback(Handler.java:761)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6617)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
`

**Comment by Abhishek01039** [comment] 2024-11-13 14:25
Hello @MaikuB 
I am having the same issue on Android 7

I am using `flutter_local_notifications: ^17.2.2`

<img width="1377" alt="image" src="https://github.com/user-attachments/assets/7876c6ed-a353-43ac-97fa-cc99b9694f0a">
