### ISSUE TITLE
Library is not working on projects with target SDK 31.

### ISSUE THREAD

**Issue by mehdico** [MaikuB/flutter_local_notifications#1304] opened 2021-09-08 08:33 UTC
The main problem is about ScheduledNotificationBootReceiver.SDK 31 need to set android:exported for all the receivers.

I've tried to override the library manifest for the receiver in my project and set android:exported=false and my project get compiled without any problem but there is a runtime error and we need to fix it to work on the new versions of android.

Error:

> D/EGL_emulation(15762): app_time_stats: avg=6082.11ms min=6082.11ms max=6082.11ms count=1
> E/MethodChannel#dexterous.com/flutter/local_notifications(15762): Failed to handle method call
> E/MethodChannel#dexterous.com/flutter/local_notifications(15762): java.lang.IllegalArgumentException: com.example.test: Targeting S+ (version 10000 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
> E/MethodChannel#dexterous.com/flutter/local_notifications(15762): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
> E/MethodChannel#dexterous.com/flutter/local_notifications(15762): 	at android.app.PendingIntent.checkFlags(PendingIntent.java:386)
> E/MethodChannel#dexterous.com/flutter/local_notifications(15762): 	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:470)
> E/MethodChannel#dexterous.com/flutter/local_notifications(15762): 	at android.app.PendingIntent.getActivity(PendingIntent.java:456)
> E/MethodChannel#dexterous.com/flutter/local_notifications(15762): 	at android.app.PendingIntent.getActivity(PendingIntent.java:420)
> E/MethodChannel#dexterous.com/flutter/local_notifications(15762): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:176)
> E/MethodChannel#dexterous.com/flutter/local_notifications(15762): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:820)
> E/MethodChannel#dexterous.com/flutter/local_notifications(15762): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:1089)
> E/MethodChannel#dexterous.com/flutter/local_notifications(15762): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:976)
> E/MethodChannel#dexterous.com/flutter/local_notifications(15762): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
> E/MethodChannel#dexterous.com/flutter/local_notifications(15762): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
> E/MethodChannel#dexterous.com/flutter/local_notifications(15762): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
> E/MethodChannel#dexterous.com/flutter/local_notifications(15762): 	at android.os.MessageQueue.nativePollOnce(Native Method)
> E/MethodChannel#dexterous.com/flutter/local_notifications(15762): 	at android.os.MessageQueue.next(MessageQueue.java:335)
> E/MethodChannel#dexterous.com/flutter/local_notifications(15762): 	at android.os.Looper.loopOnce(Looper.java:161)
> E/MethodChannel#dexterous.com/flutter/local_notifications(15762): 	at android.os.Looper.loop(Looper.java:288)
> E/MethodChannel#dexterous.com/flutter/local_notifications(15762): 	at android.app.ActivityThread.main(ActivityThread.java:7695)
> E/MethodChannel#dexterous.com/flutter/local_notifications(15762): 	at java.lang.reflect.Method.invoke(Native Method)
> E/MethodChannel#dexterous.com/flutter/local_notifications(15762): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> E/MethodChannel#dexterous.com/flutter/local_notifications(15762): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
> I/flutter (15762): PlatformException(error, com.example.test: Targeting S+ (version 10000 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
> I/flutter (15762): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles., null, java.lang.IllegalArgumentException: com.example.test: Targeting S+ (version 10000 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
> I/flutter (15762): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
> I/flutter (15762): 	at android.app.PendingIntent.checkFlags(PendingIntent.java:386)
> I/flutter (15762): 	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:470)
> I/flutter (15762): 	at android.app.PendingIntent.getActivity(PendingIntent.java:456)
> I/flutter (15762): 	at android.app.PendingIntent.getActivity(PendingIntent.java
> D/EGL_emulation(15762): app_time_stats: avg=34.32ms min=7.28ms max=402.72ms count=34

**Comment by MaikuB** [comment] 2021-09-08 08:41
There's a 9.0.0 prerelease for Android 12 support

**Comment by MaikuB** [comment] 2021-09-08 08:47
Closing as this is a duplicate of https://github.com/MaikuB/flutter_local_notifications/issues/1171

**Closed by MaikuB** 2021-09-08 08:47 UTC
