### ISSUE TITLE
Local Notification does not appears on IOS 14 version when app is in Foreground

### ISSUE THREAD

**Issue by ZubairYasin786** [MaikuB/flutter_local_notifications#1196] opened 2021-06-16 13:01 UTC
flutter_local_notifications: ^7.0.0-dev.1
----------------------------------------------------------------------------------------------------------------------------
  FlutterLocalNotificationsPlugin _flnp = FlutterLocalNotificationsPlugin();

    await _flnp.initialize(
      InitializationSettings(
        android: AndroidInitializationSettings('notif_icon_small'),
        iOS: IOSInitializationSettings(
          requestSoundPermission: true,
          requestBadgePermission: true,
          requestAlertPermission: true,
          defaultPresentAlert: true,
          onDidReceiveLocalNotification: (id, title, body, payload) async {
            Utils.myLog(
                'onDidReceiveLocalNotification(): $id, $title, $body, $payload');
          },
        ),
      ),
      onSelectNotification: (payload) async {
      },
    );

    await _flnp.show(
      1,
      'This is notification title',
      'This is the body of the notification',
      NotificationDetails(
        android: _androidNotificationDetails(),
        iOS: IOSNotificationDetails(
          presentAlert: true,
          presentSound: true,
        ),
      ),
      payload: 'this is extra information you can send json data here',
    );

----------------------------------------------------------------------------------------------------------------------------
//AppDelegate.swift
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)

    if #available(iOS 10.0, *) {
      UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
    }
    
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
    
}

**Comment by MaikuB** [comment] 2021-06-20 00:05
Cannot reproduce the issue.  Would need  a link to a repo with minimal app that can reproduce the problem and include the output of running `flutter doctor -v`

**Comment by ZubairYasin786** [comment] 2021-06-20 12:34
> Cannot reproduce the issue. Would need a link to a repo with minimal app that can reproduce the problem and include the output of running `flutter doctor -v`

Please gave me a suitable solution for that problem. I can not understand what are you saying.

**Comment by MaikuB** [comment] 2021-06-20 12:58
I can't explain this further. I wasn't giving your a solution. I was saying I cannot reproduce the issue you say you're having so you would need to provide a link to a repository that has a minimal app that can reproduce the issue.  In addition to that you would need to include the output of running the command `flutter doctor -v`. This provides details of your development environment such as the version of Flutter you're running.

If you still cannot understand what I said then I'm guessing you're not fluent in English and need to find someone else who can explain what I said in your native language

**Comment by MaikuB** [comment] 2021-07-02 08:32
Closing this as no minimal app to reproduce the issue has been provided and there's an issue at https://github.com/MaikuB/flutter_local_notifications/issues/1214 where they mention it works in the foreground for them. Feel free to re-open the issue if you can provide what was requested

**Closed by MaikuB** 2021-07-02 08:32 UTC
