### ISSUE TITLE
Feature request: Notifications don't make sound when phone is on silent mode

### ISSUE THREAD

**Issue by ShruAlekha** [MaikuB/flutter_local_notifications#1369] opened 2021-11-01 11:40 UTC
The notifications work great when the phone is on default mode. However, when I turn on the silent mode/default mode on Android device or emulator, the notifications show up with no sound. I am working on an alarm and app so trying to see if there is an option to override this behavior and have the notifications make the sound irrespective of the phone settings. Would really appreciate if this is something that can be given as an option.

**Comment by MaikuB** [comment] 2021-11-06 08:35
Sounds like this is a duplicate of https://github.com/MaikuB/flutter_local_notifications/issues/1211 so will close this as a duplicate. Note that PRs are welcome

**Closed by MaikuB** 2021-11-06 08:35 UTC
