### ISSUE TITLE
Disable IOS notification permission on first launch

### ISSUE THREAD

**Issue by hadukin** [MaikuB/flutter_local_notifications#2064] opened 2023-08-01 04:11 UTC
every time the application is launched on ios for the first time, a popup with permissions to receive notifications is called up

plugin version: **flutter_local_notifications: ^15.1.0+1**

test on device emulator iOS 16.4

**code example:**

```
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();
  const initializationSettingsAndroid = AndroidInitializationSettings('app_icon');
  final initializationSettingsDarwin = DarwinInitializationSettings(
    requestSoundPermission: false,
    requestBadgePermission: false,
    requestAlertPermission: false,
    defaultPresentAlert: false,
    defaultPresentBadge: false,
    defaultPresentBanner: false,
    defaultPresentList: false,
    defaultPresentSound: false,
    requestCriticalPermission: false,
    requestProvisionalPermission: false,
    onDidReceiveLocalNotification: (_, __, ___, ____) {},
  );

  const initializationSettingsLinux = LinuxInitializationSettings(
    defaultActionName: 'Open notification',
  );

  final initializationSettings = InitializationSettings(
    android: initializationSettingsAndroid,
    iOS: initializationSettingsDarwin,
    macOS: initializationSettingsDarwin,
    linux: initializationSettingsLinux,
  );

  await flutterLocalNotificationsPlugin.initialize(
    initializationSettings,
    onDidReceiveNotificationResponse: (_) {},
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

**Comment by MaikuB** [comment] 2023-08-03 12:11
I've taken your code snippet to apply this to the example app using the same version of the plugin you've mentioned and cannot reproduce the issue. If you believe there's an issue then can you fork the repo based on version 15.1.0+1, update the example app accordingly, see if you can reproduce the issue and if so and share the link here?

**Comment by muezz** [comment] 2023-08-24 10:53
@MaikuB I have also noticed this. Just initializing inside `main` before `runApp` triggers the request for permissions when the app is installed and run on a fresh simulator (I have only tried on iOS).

Here is the code that runs on app start:
```dart
/// Initialize notification
  static void init() async {
    // requestIOSPermissions();
    _configureLocalTimeZone();
    const DarwinInitializationSettings initializationSettingsIOS =
        DarwinInitializationSettings();

    const InitializationSettings initializationSettings =
        InitializationSettings(
      iOS: initializationSettingsIOS,
    );
    await flutterLocalNotificationsPlugin.initialize(initializationSettings);
  }
```

**Comment by MaikuB** [comment] 2023-08-24 10:57
@muezz what you're seeing is expected given the [initialisation settings class](https://pub.dev/documentation/flutter_local_notifications/latest/flutter_local_notifications/DarwinInitializationSettings-class.html)  has values that default to requesting permissions

**Comment by muezz** [comment] 2023-08-24 11:04
Ah! My bad. I did not know that those settings were there.

**Comment by MaikuB** [comment] 2023-08-24 11:06
No worries.

I'm closing this issue as the code snippet from @hadukin who raised this issue originally works as expected

**Closed by MaikuB** 2023-08-24 11:06 UTC
