### ISSUE TITLE
cannot find symbol getNotificationChannels

### ISSUE THREAD

**Issue by bsutton** [MaikuB/flutter_local_notifications#1059] opened 2021-02-25 21:14 UTC
Version: ^4.0.1

After a long hiatus I'm trying to work on an app that uses flutter_local_notificacations.

When I try to launch the app in debug mode using the android emulator I'm getting the following error:

```

Launching lib/main.dart on Android SDK built for x86 in debug mode...
lib/main.dart:1
/home/bsutton/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-4.0.1/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java:1260: error: cannot find symbol
            List<NotificationChannel> channels = notificationManagerCompat.getNotificationChannels();
                                                                          ^
  symbol:   method getNotificationChannels()
  location: variable notificationManagerCompat of type NotificationManagerCompat

1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_local_notifications:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

Probably not directly related but I'm also getting the following warning
```
Note: /home/bsutton/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-4.0.1/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

I'm guessing this is an issue with an sdk version however looking up the doco on notificationManagerCompat does provide details on what sdk version its available on so I suspect it should be available for any recent version.

Any ideas where to start looking?

**Comment by MaikuB** [comment] 2021-02-26 06:57
Does your application define an explicit dependency on `androidx.core:core` on the Android side? If so, that may need to be bumped. This may be one of methods that got added in more later versions of said library but the docs don't indicate which ones unless you go through the change log for it. I'll see if this could be changed to call the method from the `NotificationManager` that is part of the main Android SDK. If not, will make a note of this in the readme

**Comment by tony123S** [comment] 2021-03-05 05:22
facing this issue too...

> Does your application define an explicit dependency on androidx.core:core on the Android side or override the version?

Where to check ? @MaikuB

**Comment by tony123S** [comment] 2021-03-05 15:05
What does this mean ? 
```location: variable notificationManagerCompat of type NotificationManagerCompat```

**Comment by harshapulikollu** [comment] 2021-03-06 13:44
Facing same issue on flutter_local_notifications-5.0.0-nullsafety.0
```
.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-5.0.0-nullsafety.0/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java:1260: error: cannot find symbol
            List<NotificationChannel> channels = notificationManagerCompat.getNotificationChannels();

 symbol:   method getNotificationChannels()
  location: variable notificationManagerCompat of type NotificationManagerCompat
Note: .pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-5.0.0-nullsafety.0/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Comment by MaikuB** [comment] 2021-03-07 00:24
> Where to check ? @MaikuB

Read https://developer.android.com/studio/build/dependencies for info about Android build dependencies

**Comment by bsutton** [comment] 2021-03-07 00:28
I eventually did a flutter clean and upgrade to flutter 2 and some where along the way the problem went away.

**Comment by MaikuB** [comment] 2021-03-07 00:51
Thanks for the update @bsutton. For anyone else with the issue, please check your dependencies and try to run `flutter clean` to see if it solves the issue. This plugin pulls in a version of the AndroidX core library that contains the method being referenced in the messages you're seeing but cannot be found. I'll close this since @bsutton no longer has an issue but if you still experience an issue then please open another one with a link to a repository containing a minimal app that can reproduce the problem.

**Closed by MaikuB** 2021-03-07 00:51 UTC

**Comment by tony123S** [comment] 2021-03-07 09:50
I have upgraded to flutter 2.0 and run `flutter clean`, but still hitting same issue.
```

Note: /home/xxx/Desktop/flutter_linux_2.0.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.0.0/android/src/main/java/io/flutter/plugins/firebase/core/FlutterFirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/home/xxx/Desktop/flutter_linux_2.0.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-4.0.1+2/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java:1260: error: cannot find symbol
            List<NotificationChannel> channels = notificationManagerCompat.getNotificationChannels();
                                                                          ^
  symbol:   method getNotificationChannels()
  location: variable notificationManagerCompat of type NotificationManagerCompat
Note: /home/xxx/Desktop/flutter_linux_2.0.1-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-4.0.1+2/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

```

**Comment by harshapulikollu** [comment] 2021-03-07 13:14
Hi @tony123S,
I was able to resolve the issue in `flutter 2.0` by changing the androidx.core version in android level `build.gradle` 
```
subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'androidx.core' &&
                    !details.requested.name.contains('androidx')) {
                details.useVersion "1.3.2" //earlier it's 1.0.1 and facing issues
            }
        }
    }
}
```
Either you try by adding this in your code if you don't have it earlier or replace the version.

**Comment by tony123S** [comment] 2021-03-08 13:24
@harshapulikollu thanks,it works
