### ISSUE TITLE
[flutter_local_notifications] Null Point Exception on onReceive of 10.0.0 branch

### ISSUE THREAD

**Issue by lucasribolli** [MaikuB/flutter_local_notifications#1654] opened 2022-07-26 13:55 UTC
**Describe the bug**

When updating an application from the old fork (before null-safety) that inserts action buttons to the latest, a Null Point Exception is thrown in `onReceive` method on Android side. 

**To Reproduce**

1. Have an app installed with a local dependency of the pre null safety fork of this plugin that inserts the action button: https://github.com/ened/flutter_local_notifications/tree/c21f8fc0e56477f7053b1bf1b4fa46290f8e5e8b (this is the exact snapshot that makes the error occurs)
2. Schedule a notification with some simple action buttons and make them show, like this:
```dart
actions: [
      AndroidNotificationAction(
           'ACTION_BUTTON_ID',
            'Action Button',
            contextual: false,
            allowGeneratedReplies: false,
            showsUserInterface: false
      ),
]
```
3. Update the app code latest 10.0.0 branch, generate the release APK and install it with `adb install -r app-release.apk`
4. Schedule more notification and make them show with the app updated

**Expected behavior**
The `onReceive` should execute and the notification should appears

**Sample code to reproduce the problem**
It's hard to provide and reproduce since it requires to generate a release APK in pre null safety with the fork dependency in local repository and then update the code and the APK with latest dependencies.

**Log**
<details>
--------- beginning of crash

07-28 09:00:00.479 17536 17536 E AndroidRuntime: FATAL EXCEPTION: main
07-28 09:00:00.479 17536 17536 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
07-28 09:00:00.479 17536 17536 E AndroidRuntime:     at android.app.ActivityThread.handleReceiver(ActivityThread.java:3857)
07-28 09:00:00.479 17536 17536 E AndroidRuntime:     at android.app.ActivityThread.access$1500(ActivityThread.java:226)
07-28 09:00:00.479 17536 17536 E AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1900)
07-28 09:00:00.479 17536 17536 E AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:107)
07-28 09:00:00.479 17536 17536 E AndroidRuntime:     at android.os.Looper.loop(Looper.java:225)
07-28 09:00:00.479 17536 17536 E AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:7564)
07-28 09:00:00.479 17536 17536 E AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
07-28 09:00:00.479 17536 17536 E AndroidRuntime:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
07-28 09:00:00.479 17536 17536 E AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
07-28 09:00:00.479 17536 17536 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
07-28 09:00:00.479 17536 17536 E AndroidRuntime:     at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:292)
07-28 09:00:00.479 17536 17536 E AndroidRuntime:     at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:1124)
07-28 09:00:00.479 17536 17536 E AndroidRuntime:     at com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive(ScheduledNotificationReceiver.java:41)
07-28 09:00:00.479 17536 17536 E AndroidRuntime:     at android.app.ActivityThread.handleReceiver(ActivityThread.java:3848)
07-28 09:00:00.479 17536 17536 E AndroidRuntime:     ... 8 more
</details>

**Comment by MaikuB** [comment] 2022-07-28 13:35
Given the PR you submitted us more around null checks for existing code, I may look into merging this in. However, the issue you described is to do with how you used an early snapshot of a PR prior to it being merged. During this period, authors may choose to make breaking changes. This can also take place during a prerelease phase in general. Therefore it's not a bug with the plugin itself. Wanted to point this out as it's generally not sustainable for maintainers to be supporting backwards compatibility to the point of needing that they need to consider the changes made over the lifetime of a PR. Such forks may end up being deleted after they are merged too. On that note, that the link you posted doesn't work either.

**Closed** 2022-07-31 22:16 UTC
