### ISSUE TITLE
Android error, but iOS fine

### ISSUE THREAD

**Issue by ahmetozcan999** [MaikuB/flutter_local_notifications#1061] opened 2021-02-28 22:04 UTC
My application working fine on iOS.but at android taking given error

my application work on ios succesful but in android i take this errors

`E/flutter (28399): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel dexterous.com/flutter_local_notifications)`

**Comment by MaikuB** [comment] 2021-03-01 09:57
The code to implement this is there so either your pub cache is corrupt or you've made some changes to the code on the Android side that has caused the plugin to not be registered. See https://github.com/MaikuB/flutter_local_notifications/issues/238 an example of the latter where others needed to make more manual changes on

**Comment by ahmetozcan999** [comment] 2021-03-01 18:45
> The code to implement this is there so either your pub cache is corrupt or you've made some changes to the code on the Android side that has caused the plugin to not be registered. See #238 an example of the latter where others needed to make more manual changes on

ty for reply. i only activate multidex. and our android files same with example. i try flutter clean and still same error

**Comment by MaikuB** [comment] 2021-03-01 21:05
Running flutter clean doesn't fix a corrupt pub cache. There are different commands for it, worst case you need to reinstall the Flutter SDK. This would be an issue with your environment, not a bug in the app so there isn't anything that can be done on the plugin side to fix this

**Comment by CosmicPangolin** [comment] 2021-03-10 23:02
@MaikuB 

I've also been blocked by this on Android for a while now, and I've tried quite a lot to fix it - every suggestion from the previous thread (minus registering FCM in MainActivity since we're not using FCM - Flutter also does not seem to construct Application.kt for new projects so that solution seems outdated), reinstalling Flutter SDK, testing on different channels and waiting a few weeks for Flutter SDK updates, porting lib into a newly created flutter project, running on different machines with newly created flutter environments. 

There should be some clear, identifiable reason why this issue pops up on clean framework/project installs for this plugin but not others.  Kinda pulling my hair out over here.

**Comment by MaikuB** [comment] 2021-03-11 09:12
@CosmicPangolin If the issue lied with the plugin, I'd expect to see how this can be reproduce. I've yet to see this info been provided or have come across it on basic app using only this plugin. You mention you're FCM and how you're not using it but as I mentioned in the previous post, even if the error you see is pointing to this plugin, the issue could actually be happening due to other plugins and this is something I've see . Chances are you have a similar issue and is something you would need to track down by stripping out dependencies to find out the culprit. This would also explain why you may not see the actual issue being identified as applications will have different dependencies.

I'm going to close this issue as @ahmetozcan999 has not responded further and I had previously seen one of @ahmetozcan999 reference the `flutter_facebook_login` that has been known to cause issues

**Closed by MaikuB** 2021-03-11 09:12 UTC

**Comment by CosmicPangolin** [comment] 2021-03-11 21:58
@MaikuB Oki, I'll try systematically stripping plugin libraries from my app and see where that gets me.

**Comment by MaikuB** [comment] 2021-03-11 22:11
Another thing to add with the case I saw where other plugins were causing the issue, after I removed all references to this plugin, the same kind of error occurred for another plugin, which from memory, was the first plugin called by the code
