### ISSUE TITLE
When updating the android app part of the pending notification are getting triggered.

### ISSUE THREAD

**Issue by spiderion** [MaikuB/flutter_local_notifications#2205] opened 2024-01-12 09:12 UTC
When updating the android app from google play, part of the pending notifications are getting triggered.

**Comment by MaikuB** [comment] 2024-02-02 09:25
If you're running into this then you'll need to see if this something you can help fix. My understanding is running `adb install -r ...` mimics updating and haven't been able to reproduce this. The other thing is the plugin doesn't have code to fire notifications on an update. It does however, have code on Android that will reschedule notifications after a device has been turned on as turning a device off and on would normally clear out "alarms" (note: using the terminology from Android's API) set. Potentially this is related to your issue but these should be scheduled at the time specified and restarting a device with pending notifications would the way to reproduce this scenario

**Comment by MaikuB** [comment] 2024-11-13 12:22
Closing this due to lack of way to reproduce

**Closed by MaikuB** 2024-11-13 12:22 UTC
