### ISSUE TITLE
FCM onBackgroundMessage - onSelectNotification

### ISSUE THREAD

**Issue by statsss** [MaikuB/flutter_local_notifications#1025] opened 2021-02-03 18:30 UTC
When  receive a push notification in the background, I show it through flutterLocalNotificationsPlugin.show, after the user has clicked on the notification - the application opens in a different isolate starting with main() (onSelectNotification is not processed), how to change the entry point?

**Comment by MaikuB** [comment] 2021-02-09 06:50
Haven't had both of these working together and I'm not sure about the scenario you're referring to. Is the app still running when you tap on the notification or are you tapping on the notification from when the app has been terminated? If it's the latter then would be expected but if it's the former then there's no mechanism for this. Either you'd need to look at submitting a PR or a fork to change the entry point and/or potentially needs changes in the Flutter engine to allow for process-wide isolates that were discussed in https://github.com/flutter/flutter/issues/23904

**Comment by jonbhanson** [comment] 2021-02-11 22:01
@MaikuB thanks for this great package!  I have the same problem, but I am taking a different approach.  I have FCM setup with a background message handler, which is in a separate isolate:
`FirebaseMessaging.onBackgroundMessage(backgroundMessageHandler);`

In my `backgroundMessageHandler`, I initialize FlutterLocalNotificationsPlugin and show a notification.  In this isolate, I can send a message to my app with a named port.  Everything works fine, the app receives the message:

`final port = IsolateNameServer.lookupPortByName(backgroundMessageIsolateName);
  port.send('showing the notification');
  await _flutterLocalNotificationsPlugin.initialize(initializationSettings, onSelectNotification: selectNotification);`

Here is the part I can't figure out.  In my notification select handler, I try to send a message to my app in the same way, but the app never receives the message:

`
Future selectNotification(String payload) async {
  final port = IsolateNameServer.lookupPortByName(backgroundMessageIsolateName);
  port.send('selected the notification');
  return;
}
`

Do you think there is a problem with my message to the app, or is the selectNotification never firing?

Thanks!

**Comment by MaikuB** [comment] 2021-02-12 08:19
Based on my (limited) knowledge about how the isolates work, the callback isn't being invoked as the method invoked by `onBackgroundMessage` is essentially another entry point to the app and that the reason why the plugin needs to be initialised within the isolate is because it runs in isolation. Given the method will only run for a short period and scoped to that method, it will never receive the callback as the objects would be destroyed once the callback has finished. This is where the process-wide isolate could potentially solve the issue as I ran into issues where callbacks using background execution would prevent the regular callbacks from running. I don't know what the Flutter team's plans/priorities are around this and it's been a long time since this was raised/discussed. I had seen a [design document](https://docs.google.com/document/d/1k7OimxbxXzdv3U7-TfB88yG5hIScN3TH6Jcvdcl4izM/edit) that where they were evaluating how background execution works and it sounds like they may potentially not continue with keeping the current model as well

**Comment by jonbhanson** [comment] 2021-02-12 13:04
Thanks for the feedback @MaikuB.  Here's an interesting thing that I just discovered: I made a test in iOS and found that the `selectNotification` callback was called.  So it is only in Android that the callback is not called.

**Comment by jonbhanson** [comment] 2021-02-12 16:32
Here are the steps to reproduce the `selectNotification` callback working in iOS but not working in Android:

1. Create a new flutter project.
2. Add the dependencies to `pubspec.yaml`:
```yaml
  flutter_local_notifications: ^4.0.1
  flutter_isolate: ^1.0.0+14
```
3. Add the following lines to the didFinishLaunchingWithOptions method in the AppDelegate.swift:
```swift
if #available(iOS 10.0, *) {
  UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
}
```
4. Replace the entire main.dart with the following dart code:


```dart
import 'dart:isolate';
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter_isolate/flutter_isolate.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  ReceivePort backgroundMessageport = ReceivePort();
  IsolateNameServer.registerPortWithName(backgroundMessageport.sendPort, backgroundMessageIsolateName);
  backgroundMessageport.listen(print);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Scaffold(
        body: Center(
          child: RaisedButton(
            onPressed: () async => await FlutterIsolate.spawn(backgroundMessageHandler, "hello"),
            child: Text('Display notification through isolate'),
          ),
        ),
      ),
    );
  }
}

void backgroundMessageHandler(dynamic param) async {
  final FlutterLocalNotificationsPlugin _flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();
  // initialise the plugin. app_icon needs to be a added as a drawable resource to the Android head project
  const AndroidInitializationSettings initializationSettingsAndroid = AndroidInitializationSettings('@mipmap/ic_launcher');
  final IOSInitializationSettings initializationSettingsIOS = IOSInitializationSettings();

  final InitializationSettings initializationSettings = InitializationSettings(android: initializationSettingsAndroid, iOS: initializationSettingsIOS);
  final port = IsolateNameServer.lookupPortByName(backgroundMessageIsolateName);

  await _flutterLocalNotificationsPlugin.initialize(initializationSettings, onSelectNotification: selectNotification);

  const AndroidNotificationDetails androidPlatformChannelSpecifics = AndroidNotificationDetails(
      'your channel id', 'your channel name', 'your channel description',
      importance: Importance.max, priority: Priority.high, showWhen: false);
  const NotificationDetails platformChannelSpecifics = NotificationDetails(android: androidPlatformChannelSpecifics);
  port.send('Posting the message');
  await _flutterLocalNotificationsPlugin.show(0, 'title', 'body', platformChannelSpecifics);

  return null;
}

const String backgroundMessageIsolateName = 'flutter_app_isolate_test_key';

Future selectNotification(String payload) async {
  final port = IsolateNameServer.lookupPortByName(backgroundMessageIsolateName);
  port.send('clicked the message!');
  return;
}
```

In iOS, if you show the notification and select the notification, you should see these messages printed:
```
flutter: Posting the message
flutter: clicked the message!
```
In Android, the same actions only print the first message:
```
flutter: Posting the message
```

**Comment by MaikuB** [comment] 2021-02-12 21:04
Didn't realise you were using another plugin for isolates. If you're getting the callback invoked on iOS then the issue may well be to do with that plugin then. There are seem to be others reporting issues using it with other plugins too
https://github.com/rmawatson/flutter_isolate/issues/31

**Comment by jonbhanson** [comment] 2021-02-12 21:41
In my app I am using flutter_local_notifications in an isolate that is from FCM.  In this example, I wanted to leave out FCM because it requires sending notifications from FCM and makes the example a lot more complicated.

When I tried to use flutter_local_notifications in my example, I ran into [this problem](https://stackoverflow.com/questions/57689492/flutter-unhandled-exception-servicesbinding-defaultbinarymessenger-was-accesse/62357178) which is why I added the `flutter_isolate` package.

You may be right that there is a problem in `flutter_isolate`, but since it has the same behavior as my FCM case, I'm not sure.

**Comment by MaikuB** [comment] 2021-02-12 22:27
From the perspective of this plugin though, there's nothing else it can do as both the Android and iOS side use the same mechanism to invoke callbacks. I would suspect you just used FCM with `flutter_isolate` where a notification message is sent to test the callback on when the push notification has been tapped on that it will work fine. So I reckon it's either that plugin or a general issue with the current implementation of isolates (like the one I raised on the GitHub repo).

Using a modified version of your code like below

```dart
import 'dart:isolate';
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter_isolate/flutter_isolate.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

final FlutterLocalNotificationsPlugin _flutterLocalNotificationsPlugin =
    FlutterLocalNotificationsPlugin();
// initialise the plugin. app_icon needs to be a added as a drawable resource to the Android head project

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  ReceivePort backgroundMessageport = ReceivePort();
  IsolateNameServer.registerPortWithName(
      backgroundMessageport.sendPort, backgroundMessageIsolateName);
  backgroundMessageport.listen(print);
  const AndroidInitializationSettings initializationSettingsAndroid =
      AndroidInitializationSettings('@mipmap/ic_launcher');
  final IOSInitializationSettings initializationSettingsIOS =
      IOSInitializationSettings();

  final InitializationSettings initializationSettings = InitializationSettings(
      android: initializationSettingsAndroid, iOS: initializationSettingsIOS);

  await _flutterLocalNotificationsPlugin.initialize(initializationSettings,
      onSelectNotification: (_) async {
    debugPrint('hello');
  });
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Scaffold(
        body: Center(
          child: RaisedButton(
            onPressed: () async =>
                await FlutterIsolate.spawn(backgroundMessageHandler, "hello"),
            child: Text('Display notification through isolate'),
          ),
        ),
      ),
    );
  }
}

void backgroundMessageHandler(dynamic param) async {
  final FlutterLocalNotificationsPlugin _flutterLocalNotificationsPlugin =
      FlutterLocalNotificationsPlugin();
  // initialise the plugin. app_icon needs to be a added as a drawable resource to the Android head project
  const AndroidInitializationSettings initializationSettingsAndroid =
      AndroidInitializationSettings('@mipmap/ic_launcher');
  final IOSInitializationSettings initializationSettingsIOS =
      IOSInitializationSettings();

  final InitializationSettings initializationSettings = InitializationSettings(
      android: initializationSettingsAndroid, iOS: initializationSettingsIOS);
  final port = IsolateNameServer.lookupPortByName(backgroundMessageIsolateName);

  await _flutterLocalNotificationsPlugin.initialize(initializationSettings,
      onSelectNotification: selectNotification);

  const AndroidNotificationDetails androidPlatformChannelSpecifics =
      AndroidNotificationDetails(
          'your channel id', 'your channel name', 'your channel description',
          importance: Importance.max, priority: Priority.high, showWhen: false);
  const NotificationDetails platformChannelSpecifics =
      NotificationDetails(android: androidPlatformChannelSpecifics);
  port.send('Posting the message');
  await _flutterLocalNotificationsPlugin.show(
      0, 'title', 'body', platformChannelSpecifics);

  return null;
}

const String backgroundMessageIsolateName = 'flutter_app_isolate_test_key';

Future selectNotification(String payload) async {
  final port = IsolateNameServer.lookupPortByName(backgroundMessageIsolateName);
  port.send('clicked the message!');
  return;
}
```

It looks as though the callback on the main isolate (i.e. it'll hit `debugPrint('hello`)) will get called on both Android and iOS

**Comment by drikanius** [comment] 2021-02-27 04:37
Hello guys, I have the same issue mentioned by @statsss. It used to work in version 3.0.3 (and if I switch to it it still works), but after I upgraded to 4 the function sent in onSelectionNotification is no longer called in the background.

I don't know if that helps anything.

**Comment by drikanius** [comment] 2021-02-27 05:13
I got what I did wrong.

Reading the changelog (4.0.0):

> Breaking change calling initialize will no longer trigger the onSelectNotification if a notification was tapped on prior to calling initialize. This was done as the getNotificationAppLaunchDetails method already provided a way to handle when an application was launched by a notification. Furthermore, calling initialize multiple times (e.g. on different pages) would have previously caused the onSelectNotification callback multiples times as well. This potentially results in the same notification being processed again

Then I've changed my code to use that piece of code:

```Dart
    final notificationAppLaunchDetails = await flutterLocalNotification.getNotificationAppLaunchDetails();
    if (notificationAppLaunchDetails.didNotificationLaunchApp) {
      final payload = notificationAppLaunchDetails.payload;
      //...
    }
```

Now It is back to the normal behavior.
Sorry for the trouble.

**Comment by fdarsot** [comment] 2021-03-04 03:59
@drikanius can you explain where you added that piece of code? im trying to update my old version to the new version and the new changes, but i am still running into issues.

**Comment by drikanius** [comment] 2021-03-04 05:22
I created a test ([notification_test](https://github.com/drikanius/notification_test)) using flutter_local_notifications: ^5.0.0-nullsafety.0 and maybe you can check if the issue persists.

My intention was to create a quick code and of course, you don't need to use my classes. 

The idea is to call this function on local_message.dart

``` Dart
  Future<void> onLaunchByMessage({required SelectNotificationCallback onSelectNotification}) async {
    final notificationAppLaunchDetails = await _notification.getNotificationAppLaunchDetails();
    if (notificationAppLaunchDetails != null && notificationAppLaunchDetails.didNotificationLaunchApp) {
      final payload = notificationAppLaunchDetails.payload;
      onSelectNotification(payload);
    }
    return Future<void>.value();
  }
```
As you can see on `_MyHomePageState` class (main.dart), this function is called on `initState()`.

Test steps:

1. Open the app;
2. Click on '+' button (it should create a dummy notification);
2.1. If you click on the notification the text will change to "Hello notification {"node" :"value"}";
3. But here the idea is not to click the notification while the app is open. Therefore, you must close the app; and
4. Now you click on the notification. (The result should be the same - "Hello notification {"node" :"value"}").

Removing the `onLaunchByMessage` on `initState()` function will make the sentence "Hello world" not change.

You can take a look at the code, if you have questions I can answer them, no problems.

**Maybe you need to compile using `--no-sound-null-safety` (not sure)**

**Comment by fdarsot** [comment] 2021-03-05 01:32
Hi @drikanius thank you so much for the help. So i tried it your way, however the issue im getting is the app appears to keep "reloading" over and over again.

below is the functions i have used:

// this is in  my initstate function
    _initializeOnTapCallBack(onSelectNotification: onSelectNotification);

//again in my init state function
 notifications.initialize(initializationSettings,
        onSelectNotification: onSelectNotification);

below are the 2 methods

  // for Local notification handling
  Future onSelectNotification(String payload) async {
    print(payload);
    await Navigator.pushReplacementNamed(context,
        '/'); 
    return Future<void>.value();
  }


Future<void> _initializeOnTapCallBack(
      {SelectNotificationCallback onSelectNotification}) async {
    // wait to see if it was triggered
    final NotificationAppLaunchDetails notificationAppLaunchDetails =
        await notifications.getNotificationAppLaunchDetails();
    if (notificationAppLaunchDetails != null &&
        notificationAppLaunchDetails.didNotificationLaunchApp) {
      final payload =      notificationAppLaunchDetails.payload;
      onSelectNotification(payload);
      return Future<void>.value();
    } else {
      final payload =      notificationAppLaunchDetails.payload;
      onSelectNotification(payload);
      return Future<void>.value();
    }
  }

**Comment by fdarsot** [comment] 2021-03-05 01:33
i should add, everything used to work before the 4.0.0 breaking change update.

**Comment by MaikuB** [comment] 2021-03-11 08:47
Closing this as it's not something I can help with. There are others in the community with more experience with isolates so if you still have issues, please try places like Slack, Discord etc as you'd have more reach. Looks like others have found solutions in this thread too

@fdarsot that it was working before 4.0.0 doesn't mean there's an issue with the plugin. The logic you've shown doesn't relate to the original issue raised in this thread. You should debug your app to track down the issue if it's reloading. From what I can see, it seems like you got code that navigates to the same home page after the user taps on a notification. The `initState` method for that page then triggers navigating to the same page again so it's stuck in endless loop. This is an issue with the logic you've written that you need to fix. Please note that the repository has an example app for the plugin that you can use as a reference

**Closed by MaikuB** 2021-03-11 08:47 UTC
