### ISSUE TITLE
flutter_local_notifications and firebase_messaging latest are incompatible again.

### ISSUE THREAD

**Issue by rupa6** [MaikuB/flutter_local_notifications#1606] opened 2022-05-22 07:17 UTC
[flutter_local_notifications](https://github.com/MaikuB/flutter_local_notifications)(9.5.0) and firebase_messaging (11.2.13) conflicts in iOS again for handler. Due to this we can't receive callback in `onMessageOpenedApp`. Removing iOS settings from AppDelegate.m seems to work well for firebase_messaging but then flutter_local_notifications breaks.

**Comment by MaikuB** [comment] 2022-05-22 10:42
Could you include details of the version of Flutter you are using and do you know when this started happening? Curious what has happened and since when given the plugin hasn't made changes in this space

**Comment by rupa6** [comment] 2022-05-25 05:16
environment:
  sdk: ">=2.16.1 <3.0.0"

Not sure when it started happening, I was trying this recently.

**Comment by MaikuB** [comment] 2022-05-25 07:54
Thanks @rupa6 for the reply. What you sent isn't the Flutter version, that specifies what versions of Dart your application supports. To get the Flutter version, please run `flutter doctor -v`

**Comment by pranavo72bex** [comment] 2022-05-26 10:28
I am facing same similar issue... notification work in android but not in ios

**Comment by MaikuB** [comment] 2022-05-26 14:20
Please provide a minimal app that can reproduce the issue. I tried updating an app (https://github.com/MaikuB/flutter_firebase_local_notifications_examples/tree/updateKotlinSwift/kotlin_swift) I use for testing both together was able to receive callbacks from FCM and this plugin. This was tested with Flutter 3.0.0

**Comment by dehypnosis** [comment] 2022-06-12 18:47
Same here

**Comment by MaikuB** [comment] 2022-06-26 09:11
Note I mentioned earlier that this will require a minimal app for reproducing the issue

**Comment by MaikuB** [comment] 2022-12-03 00:29
Closing due as lack of minimal app that can reproduce the issue

**Closed by MaikuB** 2022-12-03 00:29 UTC
