### ISSUE TITLE
Notification payload from getActiveNotifications()

### ISSUE THREAD

**Issue by dronn1kDev** [MaikuB/flutter_local_notifications#1949] opened 2023-04-07 12:12 UTC
**Describe the bug**
Notification payload from `getActiveNotifications()` is always `null`. I sure that a notification have a payload, cause then i tap on it, the `onDidReceiveNotificationResponse` works fine by handling recieved payload.

Android 33 api

**Comment by MaikuB** [comment] 2023-04-10 04:41
Closing as this is a duplicate of https://github.com/MaikuB/flutter_local_notifications/issues/1912. If you read the APIs, it's stated payload is only returned on iOS and macOS

**Closed by MaikuB** 2023-04-10 04:41 UTC
