### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by syleishere** [MaikuB/flutter_local_notifications#1055] opened 2021-02-25 07:13 UTC
Will it work on windows? When using flutter I'd like to make sure it does.
When I;m working with python kivy framework I use: https://plyer.readthedocs.io/en/latest/index.html?highlight=notification#plyer.facades.Notification

But I notice I have to use a different icon for windows to make that work, but works flawlessly on every OS including windows.

I'm just including that link so you can read the python source to see how it interacts with win32 framework to do it quite easily, so would be nice.

**Comment by CodeDoctorDE** [comment] 2021-02-25 17:13
Duplicate of https://github.com/MaikuB/flutter_local_notifications/issues/746

**Comment by MaikuB** [comment] 2021-02-26 06:35
Windows isn't supported and the supported platforms have been documented. Closing as this is a duplicate as mentioned in @CodeDoctorDE's post

**Closed by MaikuB** 2021-02-26 06:35 UTC
