### ISSUE TITLE
cancel method takes only int as id

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [MaikuB/flutter_local_notifications#1182] opened 2021-05-28 09:43 UTC
I am building an app and want to shedule and canel local notifications.
Add notification when user plances an order and cancel it if user cancels an order. However `cancel` method takes only int. This is not very handy because people are using GUID as id's also in their DB's not only int especially for MongoDB.

If `cancel` would take `string` as id i would be able to use orderId as notification id and it would be easy to track what to add what to cancel. Also it would not change anything for people who are using `int`.

Without it I have to add custom logic to tide order id to radom int id. It adds a lot of complexity because scenario I described is very shallow but in reallity it is much more complex.

**Comment by MaikuB** [comment] 2021-06-04 09:26
This is something you'll need to manage in your app. It is that way because of how the native APIs work as plugins are wrappers/abstractions for native APIs. 

Closing as it's not an issue to do with the plugin itself and also a duplicate of https://github.com/MaikuB/flutter_local_notifications/issues/436

**Closed by MaikuB** 2021-06-04 09:26 UTC
