### ISSUE TITLE
Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver

### ISSUE THREAD

**Issue by expertashish** [MaikuB/flutter_local_notifications#489] opened 2020-02-21 05:32 UTC
Hi

I am trying to schedule a notification, its working in iOS but not for Android.
It is giving below exception:

`FATAL EXCEPTION: main
E/AndroidRuntime( 7338): Process: com.haufe.instantfeedback, PID: 7338
E/AndroidRuntime( 7338): java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/AndroidRuntime( 7338): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3797)
E/AndroidRuntime( 7338): 	at android.app.ActivityThread.access$1400(ActivityThread.java:219)
E/AndroidRuntime( 7338): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1870)
E/AndroidRuntime( 7338): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime( 7338): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 7338): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 7338): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7338): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 7338): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime( 7338): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/AndroidRuntime( 7338): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setSmallIcon(FlutterLocalNotificationsPlugin.java:156)
E/AndroidRuntime( 7338): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:131)
E/AndroidRuntime( 7338): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:598)
E/AndroidRuntime( 7338): 	at com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver.onReceive(ScheduledNotificationReceiver.java:45)
E/AndroidRuntime( 7338): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3788)
E/AndroidRuntime( 7338): 	... 8 more`

**Below is the method for scheduling notification**

`Future<void> _scheduleNotification(BuildContext context) async {
    final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();
    var scheduledTime = DateTime.now().second + 10;

    var scheduledNotificationDateTime = DateTime.now().add(Duration(seconds: scheduledTime));
    var vibrationPattern = Int64List(4);
    vibrationPattern[0] = 0;
    vibrationPattern[1] = 1000;
    vibrationPattern[2] = 5000;
    vibrationPattern[3] = 2000;

    String channelId = "if.channel";

    var androidPlatformChannelSpecifics =
        AndroidNotificationDetails(channelId, 'channelId.if', 'My App notification channel',
            importance: Importance.High,
            /*icon: 'R.mipmap/ic_launcher.png',
        sound: 'slow_spring_board.aiff',*/
            largeIconBitmapSource: BitmapSource.Drawable,
            vibrationPattern: vibrationPattern,
            enableLights: true,
            color: const Color.fromARGB(255, 255, 0, 0),
            ledColor: const Color.fromARGB(255, 255, 0, 0),
            ledOnMs: 1000,
            ledOffMs: 500);
    var iOSPlatformChannelSpecifics = IOSNotificationDetails(sound: "slow_spring_board.aiff");
    var platformChannelSpecifics = NotificationDetails(androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
    await flutterLocalNotificationsPlugin.schedule(333, "Local Notification Title", "Notification message comes here.",
        scheduledNotificationDateTime, platformChannelSpecifics);
  }`

**I have used below receivers in Android's manifest file**

`<receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
            </intent-filter>
        </receiver>
        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />`

**I have used below permissions in manifest file**

`  <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.INTERNET" />`

Please check and suggest. Thank You

**Comment by MaikuB** [comment] 2020-02-21 09:54
The stack trace implies there's an issue with the icon you've specified. Please check how you've done that. You can use the example app as reference

**Comment by expertashish** [comment] 2020-02-21 10:46
I have commented the icon and sound parameters. As per the pub doc, it should pic the default. Please confirm.

**Comment by MaikuB** [comment] 2020-02-21 10:50
There's no way for me to tell what your default is given it's up to your configure it. So It's up to you to confirm all of this. I would think if you ran the `show` method using similar details that you would run into a similar issue. . If you're going to continue to ask for help then please provide a link to a repository that can reproduce the problem.

**Comment by MaikuB** [comment] 2020-02-28 09:03
Closing since there's been no further response on this for a while

**Closed by MaikuB** 2020-02-28 09:03 UTC
