### ISSUE TITLE
Incorrect time for notification when DST changes

### ISSUE THREAD

**Issue by andrewpmoore** [MaikuB/flutter_local_notifications#118] opened 2018-10-30 15:43 UTC
Daylight saving times have just changed for us and when this happened all of my notifications have started triggering 1 hour earlier than they should. I'm using the weekly triggers.

It obvious why it happens as the time has changed back 1 hour, but I'm not sure of the best way to resolve it or whether the library should be able to handle this.

**Comment by MaikuB** [comment] 2018-11-03 04:03
It'd be good if the library can handle however I'm not sure that's possible on Android and would need a way to verify it e.g. https://stackoverflow.com/questions/15361936/alarmmanager-repeating-alarms-and-daylight-saving

**Comment by jonahgreenthal** [comment] 2019-03-07 20:41
There is also a similar issue with time zone changes (e.g., if you set a notification while you're in one time zone, then are in a different time zone when the notification is  to fire).  I'm not sure this is the same thing, but it seems like it must be. See also #179

**Comment by eggenstein** [comment] 2019-03-31 12:06
I can confirm it's still an issue, we just switched to summer time.
Could you just schedule an alarm for the next upcoming winter/summer time switch and reschedule the alarms then?

**Comment by MaikuB** [comment] 2019-04-04 07:33
@eggenstein I'm not sure if that reply was meant to be directed to me or not and not sure how that is suppose to work. Nevertheless there is definitely an issue with handling DST but as I've mentioned in #179, I'm not sure there is actually a solution that works across multiple platforms. I may need to consider deprecating the existing schedule method and provide one that accepts the time since epoch instead as that's what gets passed to the native OS over the platform channel. If anyone has an idea on a solution that works across both platforms then feel to contribute

**Comment by mikemaksymowych** [comment] 2020-02-05 16:35
Daylight savings time shouldn't be an issue with AlarmManager on Android. I confirmed that my alarms stayed consistent across daylight savings time change in Pacific time zone at least. My test was this:

- Create a simple app that sets an alarm for March 8, 2020, 3:01am (Pacific).
- Set the emulator time zone to Pacific, date and time to March 8, 2020, 1:55am
- Open the app and let the app run until the daylight savings switch occurs naturally (at 2am)
- The alarm stays set for 3:01am (Pacific) throughout, verified by `dumpsys alarm`

Time zone changes (and general time changes) *will* affect alarms though, but you can detect both of these events by registering for the respective Broadcasts and re-scheduling your alarms (assuming you have the proper information to re-schedule them).

Again my statements only apply to Android.

**Comment by MaikuB** [comment] 2020-02-05 16:44
@mikemaksymowych did you set a single alarm or a repeating one? The issue reported here is with related to repeating alarms

**Comment by mikemaksymowych** [comment] 2020-02-05 17:00
Got it, thanks. The issue would be the `intervalMillis` then, as March 8 2020 only has 23 hours. Seems like an issue on Android then.

**Comment by MaikuB** [comment] 2020-06-01 12:50
I've got a [beta release](https://pub.dev/packages/flutter_local_notifications/versions/1.5.0-beta.1) out with better timezone support that should hopefully resolve the issues with daylight savings. At least it with based on testing I did a spike I did with some native code. May be difficult to get feedback on it but would be much appreciated if you can give it a spin.

**Comment by MaikuB** [comment] 2020-10-04 09:19
Changes from beta release are now in the stable 1.5.0 release so will be closing this now

**Closed by MaikuB** 2020-10-04 09:19 UTC
Labels: help wanted

**Comment by ahmed2hamy** [comment] 2022-02-10 08:54
This issue still happens on iOS using zonedSchedule but not with schedule it works fine.

Steps to reproduce:

- Set location to "Asia/Amman"
- Schedule a zonedSchedule notification in the date of daylight saving change in Amman which is 25Feb2020

Actual: Notification appears one hour early.

**Comment by MaikuB** [comment] 2022-02-10 09:40
This change has been out for a very long time so if there were more issues on this, I would expect there to be more reports and there haven't been . Furthermore, at the time of working on this a long time ago, I had tested this out when Sydney was about to have daylight savings. All had worked as expected.

If you're having issues then I would say you should check the details you are passing in. If your issue is only on IOS versions older than 10, then note that it's documented that old iOS APIs have limited support for timezones. You may need to look into the `uiLocalNotificationDateInterpretation` parameter and refer to the associated iOS docs etc on this on what is appropriate (I believe you should be picking wall clock time). Note that plugin is doing all that is needed to account for timezones and daylight savings. In other words, there's nothing further it can do on this. I noticed you mentioned a date in the past too so that could be the source of your issue.
