### ISSUE TITLE
[Question:Android] How to detect notification dismiss?

### ISSUE THREAD

**Issue by SotnikAP** [MaikuB/flutter_local_notifications#1681] opened 2022-08-22 03:38 UTC
I want to detect if notification was dismissed by user. Is there such functionality? Or some workaround, didn't find anything about this in readme and code.

**Comment by MaikuB** [comment] 2022-08-24 22:10
No this functionality isn't available.

**Comment by Imdavyking** [comment] 2023-03-06 08:21
Please can it be added

**Comment by MaikuB** [comment] 2023-03-20 21:43
Please look at submitting a PR and this is a duplicate of #74 so will be closing this one

**Closed by MaikuB** 2023-03-20 21:43 UTC
