### ISSUE TITLE
[Bug] macOS action show notification in notification center only still shows a push notification

### ISSUE THREAD

**Issue by thaidmfinnick** [MaikuB/flutter_local_notifications#2375] opened 2024-07-16 03:02 UTC
Hi @MaikuB, thank for `flutter_local_notifications`, I have used it a lot in my projects. I find something does not work correctly.
 
I want to show noti in noti center, not push noti. I use action `Show notification in notification centre only`, but it still shows push noti for me. Same as `Show notification with banner but not in notification centre`, it still shows in notification centre. 

It's a bug? I confirm I use Example App with the newest code in repo and test on MacOS Sonoma 14.5.

Hope you can reply. Thank you!

![Screenshot 2024-07-16 at 10 00 01](https://github.com/user-attachments/assets/ae12369d-6cfa-46d8-92bf-8600443cf19b)

**Comment by MaikuB** [comment] 2024-08-10 06:04
The plugin provides the correct details via the API so what you'd seeing is to do with macOS behaving differently. This would be outside the control of the plugin so not a bug. I don't have a way of knowing all the difference Apple's own APIs will behave on each platform either when the notification APIs are the same for iOS and macOS. There was no documentation on this behaving differently on macOS either. Going to close this as there's nothing else the plugin can do

**Closed by MaikuB** 2024-08-10 06:04 UTC
