### ISSUE TITLE
onSelectNotification not called for Android

### ISSUE THREAD

**Issue by emaddoma** [MaikuB/flutter_local_notifications#126] opened 2018-11-13 20:53 UTC
Not sure what information you need to assist.  The changes to the manifest and main activity were made, no compile errors.  I am using Firebase with a MESSAGING_EVENT intent filter, but I'm not sure if that would interfere.  I've even commented out the service entry in my manifest and tested again with no change.

**Comment by tograd** [comment] 2018-11-14 04:45
Which version of the package are you using?

**Comment by Hixie** [comment] 2019-02-08 11:01
I see something similar; using v0.5.0, if the app is already running and in the foreground when the user taps the notification, the callback doesn't get called.

The code I'm using is here:
https://github.com/seamonkeysocial/cruisemonkey/blob/master/lib/src/logic/notifications.dart#L25

**Comment by MaikuB** [comment] 2019-02-08 12:03
@Hixie took the class there and changed the icon to try to reproduce this and saw the text 'User tapped notification with payload: $payload' in the debug console so it seems to be working as expected. Does it get that far for you when you run it?

**Comment by Hixie** [comment] 2019-02-08 20:57
I don't seem to reliably get there, no. I have sometimes received that, but not all the time, and as far as I recall, never while the app was up.

A lot of my problems have stemmed with interactions with android_alarm_manager, maybe that's causing the issue here too?

**Comment by MaikuB** [comment] 2019-02-10 03:37
I spun up a sample app that similar to yours, uses the alarm manager plugin to periodically show a notification (using a copy of that `Notifications` class you've linked) and the same message gets printed on tapping on the notification. This is even whilst the app is running so I doubt the alarm manager plugin is the cause. Happy to upload the sample to GitHub somewhere for you to take a look and see if you it works for you if needed.

Note: I had to use v0.2.3 of the alarm manager plugin and v0.4.5 of the notifications plugin. Seems like there's a problem if I migrate a new app to AndroidX and reference that latest version of the alarm manager plugin as it can't resolve the alarm manager plugin on the Android side. Will create an issue on the main flutter repo.

**Comment by Hixie** [comment] 2019-02-22 07:23
The problem seems to be that the notifications plugin is telling the background isolate about the tap instead of telling the main thread isolate, when you have android_alarm_manager.

**Comment by MaikuB** [comment] 2019-02-22 10:02
Thanks for the info. Looks like the issue with installing the latest android_alarm_manager has been resolved so I've gone and tried to see if I can reproduce it again to no avail. The code I had was basically the following

```
Future main() async {
  await AndroidAlarmManager.initialize();
  await AndroidAlarmManager.periodic(
      const Duration(minutes: 1), 0, _periodicCallback,
      wakeup: true);
  runApp(MyApp());
}


Future<void> _periodicCallback() async {
  print('creating notification');
  var n = await Notifications.instance;
  var threadId = counter.toString();
  var messageId = (counter * 2).toString();
  var subject = 'subject $threadId';
  var message = 'message $threadId';
  n.messageUnread(threadId, messageId, subject, message);
}
```

Perhaps the issue is somehow related what's been resolved by [this PR](https://github.com/MaikuB/flutter_local_notifications/pull/171)

**Comment by robindijkhof** [comment] 2019-03-08 20:27
I'not sure if my issue is related. In my case onSelectNotification not called for Android when the notification is created in an alarmmanager callback. I am on the latest stable flutter and on the notifications master. Here is a reproduction:

https://github.com/robindijkhof/flutter_noti

**Comment by robindijkhof** [comment] 2019-03-18 21:13
@MaikuB did my example do you any good?

**Comment by MaikuB** [comment] 2019-03-19 05:55
@robindijkhof: I've not had a chance to give it a run yet but your issue is similar to what @Hixie had posted above and I think he had put in a solution in his app that involves passing messages as the alarm manager works on a different isolate. Haven't tried yet but perhaps it would also be solved by calling initialize on the main isolate.  Your code seems to construct an instance of the plugin and call initialize on it for every notification and you should only call `initialize` once

**Comment by MaikuB** [comment] 2019-03-19 10:44
tried it out with your example and if you move the initialisation to on the main isolate like i mentioned that it works fine. I did hastily to check by copying all your code so it's in the main.dart file and then the plugin is initialised in the `main()` function

**Comment by robindijkhof** [comment] 2019-04-01 19:48
@MaikuB sorry to bother you again. I followed your suggestions which seem to work. Your suggestions completely make sense. However, I got another problem occurring.

1. I schedule a notification using the alarm manager.
2. I close the app (not a force close, just the back button).
3. I click the notification and the app starts.

Now I schedule a new with the alarm manager. The problem is that this one never fires. Do you have any idea what is causing this?

**Comment by MaikuB** [comment] 2019-05-02 11:53
apologies for the late response but it's best if you provide a sample for the above scenario. might also be best to create a separate issue since this was originally to do with firebase

@emaddoma don't know if you managed to solve your issue but if not it'd be good if you're able to provide some sample code in a repository somewhere as well.

**Comment by MaikuB** [comment] 2019-06-12 10:20
closing this due to lack of further response. feel free to re-open or create another issue if you run into problems

**Closed by MaikuB** 2019-06-12 10:20 UTC
