### ISSUE TITLE
My local MethodChannel stopped working

### ISSUE THREAD

**Issue by mrifni** [MaikuB/flutter_local_notifications#1484] opened 2022-02-13 13:48 UTC
I use the latest flutter_local_notifications: 9.3.1 (issue exists in 9.2 as well) and I've noticed my other MethodChanels stopped working. I have a native call from android to send some data back to dart/flutter UI. Since Ive integrated `flutter_local_notifications` its stopped working.

But If I comment the line `final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();`
 my internal platform specific methodchannles start to work.

do anyone know whats the issue ?

Below is my code in android which calls dart.

```
savedStaticMethodChannel?.invokeMethod("insertHighlight", addHighlightJson(type, highlight), object : MethodChannel.Result {
            override fun success(result: Any?) {
                println("------- insertHighlight success " + result)
            }

            override fun error(s: String?, s1: String?, o: Any?) {
                println("------- error " + s)
                println("------- s1 " + s1)
                println("------- o " + o)
            }

            override fun notImplemented() {
                println("------- notImplemented")
            }
        })
```
notImplemented is getting called everytime instead success.

**Comment by mrifni** [comment] 2022-02-18 19:08
any idea?

**Comment by MaikuB** [comment] 2022-02-21 08:38
No one has reported this issue before and the example app even uses this plugin with other plugins, which uses platform channels behind the scenes. I'm pretty confident the issue is more to do with your app than to do with this plugin. Those that post issues here tend to post more on bugs they have with the plugin that you're not likely to get with issues specific to your app. I'd suggest you take a closer look at what you've implemented and potentially ask your question elsewhere. If I were to take a guess, I would guess that you copied the channel name used by this plugin when you tried to create your own platform channel. If so, you should look more into platform channels work as it's in the official docs that these should be unique

**Comment by MaikuB** [comment] 2022-03-12 23:17
Closing this as this shouldn't be an issue caused by the plugin and lack of evidence to show that it is due to the plugin

**Closed by MaikuB** 2022-03-12 23:17 UTC
