### ISSUE TITLE
Platform exception on flutterLocalNotificationsPlugin.show() method

### ISSUE THREAD

**Issue by msndvlpr** [MaikuB/flutter_local_notifications#679] opened 2020-06-24 15:25 UTC
I get  **PlatformException(error, Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null)** on the line `await flutterLocalNotificationsPlugin.show(0, 'public notification title','public notification body', platformChannelSpecifics,payload: 'item x');` 
What is the reason?

**Comment by Rishi5154** [comment] 2020-06-25 03:44
Agreed, getting the same Platform Exception too, though my exceptions are E/MethodChannel#dexterous.com/flutter/local_notifications(11330): Failed to handle method call & PlatformException(error, null, null). I'm currently developing with Flutter for Android on macOS. I was previously able to display notifications from FCM with local notifications but now all of sudden as of yesterday wasn't able to do so, followed the guidelines to a tee and tried various approaches but none have worked.

**Comment by MaikuB** [comment] 2020-06-25 04:34
There's not enough information to say. Please provide a link to repo with a minimal sample app that can reproduce this problem

**Comment by Rishi5154** [comment] 2020-06-25 11:27
Hi, I don't seem to get the exception anymore, rebooting my com seems to have done the trick. But what I did previously that I think could have resulted in the exception was updating my cloud_firestore dependency from 0.13.6 to 0.13.7 . Nonetheless, unexpectedly a simple restart would do the job. Thanks for the response!

**Comment by MaikuB** [comment] 2020-06-25 11:29
No worries not sure what is the cause behind the issue @msndvlpr. I've a strong suspicion it's about not having done all of the configuration properly

**Comment by MaikuB** [comment] 2020-07-03 13:05
Closing to due lack of further info. There's an example application you can use as reference if needed. If you have found a bug, then feel free to open a new issue using the bug report template and provide all of the information mentioned in it

**Closed by MaikuB** 2020-07-03 13:05 UTC
