### ISSUE TITLE
Show Notification even if app is terminated.

### ISSUE THREAD

**Issue by jawadabbasi923** [MaikuB/flutter_local_notifications#1185] opened 2021-05-31 10:31 UTC
I am using pushers for notification in my app, notifications are working when app is in foreground but i want to show notification even if app is closed. like facebook, insta notification.

**Comment by shuizhuyu1015** [comment] 2021-06-01 09:30
I had the same problem.

**Comment by jawadabbasi923** [comment] 2021-06-02 09:48
@shuizhuyu1015 Please let me know if you have any solution. Thanks

**Comment by outailounni** [comment] 2021-06-03 09:53
Can you share a bit of your code ? 
because it works perfectly for me ( On Android ) but on IOS it always misses the first notification then starts to work.

**Comment by jawadabbasi923** [comment] 2021-06-04 07:46
Initialize Pusher :
Future<void> initPusher() async {
  try {
        await Pusher.init(
            'APP_ID',
            PusherOptions(
              cluster: 'CLUSTER',
            )
        );
      } catch (e) {
        print(e);
      }
      Pusher.connect(onConnectionStateChange: (val) {
        print(val.currentState);
      }, onError: (e) {
        print(e.message);
      });
      _channel = await Pusher.subscribe('NotificationChannel');
      _channel.bind('MyEvent', (onEvent) {
        print(onEvent.data);
        _noti = true;
        update();
        if (jsonDecode(onEvent.data)["action"].toString() == _model.success.user.email) {
          _noti = true;
          if (jsonDecode(onEvent.data)["lead_id"].toString() != null) {
            displayNotification(data : onEvent.data);
          }
          update();
        }
        update();
      });
}

Display Notification :
displayNotification({var data}) async {
    final String lead_id = '${jsonDecode(data)["lead_id"].toString()}';
    final String name = '${jsonDecode(data)["customer_name"].toString()}';
    AndroidNotificationDetails androidPlatformChannelSpecifics =
    AndroidNotificationDetails(
        '$lead_id', '$name', 'DESCRIPTION',
        importance: Importance.max,
        priority: Priority.high,
        showWhen: true);
    NotificationDetails platformChannelSpecifics =
    NotificationDetails(android: androidPlatformChannelSpecifics);
    await flutterLocalNotificationsPlugin.show(
        int.parse(lead_id), '${jsonDecode(data)["source_name"].toString()}', '${jsonDecode(data)["text"].toString()}', platformChannelSpecifics,
        payload: '$data');
  }

an don initState :
{
  const AndroidInitializationSettings initializationSettingsAndroid =
      AndroidInitializationSettings('app_icon');
      final IOSInitializationSettings initializationSettingsIOS =
      IOSInitializationSettings(
          onDidReceiveLocalNotification: onDidReceiveLocalNotification);
      final InitializationSettings initializationSettings = InitializationSettings(
          android: initializationSettingsAndroid,
          iOS: initializationSettingsIOS);
      flutterLocalNotificationsPlugin.initialize(initializationSettings,
          onSelectNotification: onSelectNotification);
      initPusher();
}

I have written native code for IOS in app delegate for now but it is not a good solution :

let pushNotifications = PushNotifications.shared
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    self.pushNotifications.start(instanceId: "INSTANCE_ID")
    self.pushNotifications.registerForRemoteNotifications()
    try? self.pushNotifications.addDeviceInterest(interest: "debug-pushNotify")
    return true
}

override func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
    print(deviceToken)
      self.pushNotifications.registerDeviceToken(deviceToken)
  }

  override  func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any],      fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
    print(userInfo.description)
    self.pushNotifications.handleNotification(userInfo: userInfo)
  }

**Comment by MaikuB** [comment] 2021-06-04 09:32
@jawadabbasi923I'm not familiar with this pusher library that you're referring but the issues you've described would mean the library isn't designed to work when the app is terminated. If you need functionality like Facebook's notifications then you'll need to look into remote/push notifications via things like Firebase Cloud Messaging, OneSignal etc. 

Closing this as it's not an issue with the plugin

**Closed by MaikuB** 2021-06-04 09:32 UTC

**Comment by outailounni** [comment] 2021-06-04 12:13
I think the problem is more with the library and not with "Flutter_local_notifications"
I advise you to try Firebase Cloud Messaging ( the easier one ) or OneSignal.

**Comment by jawadabbasi923** [comment] 2021-06-10 07:57
@outailounni can i subscribe to some channel and event in fcm like in pusher ?
