### ISSUE TITLE
Android: Exception if icon name is not passed when calling show()

### ISSUE THREAD

**Issue by btrautmann** [MaikuB/flutter_local_notifications#400] opened 2019-12-21 15:09 UTC
**Describe the bug**
On Android (emulator, Pixel 2 API 27), calling `show()` without passing an icon name causes an Exception:
```
E/MethodChannel#dexterous.com/flutter/local_notifications( 9258): Failed to handle method call
E/MethodChannel#dexterous.com/flutter/local_notifications( 9258): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/MethodChannel#dexterous.com/flutter/local_notifications( 9258): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setSmallIcon(FlutterLocalNotificationsPlugin.java:157)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9258): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:131)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9258): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:627)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9258): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:719)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9258): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:648)
E/MethodChannel#dexterous.com/flutter/local_notifications( 9258): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
```

However, notification displays fine when it is passed. This is true even when Android settings are initialized with a default icon name (the same name passed to `show()`).

**To Reproduce**
1. Initialize the plugin as in the README and example application. Specifically, pass a drawable to the Android settings:
```
AndroidInitializationSettings("ic_launcher");
```
2. Later, call show without the `icon` parameter and see the Exception above.
3. Now, pass `icon` and restart app, notification will show correctly.

**Expected behavior**
Notification should display fine without a need to pass icon for each call to `show()`.

**Sample code to reproduce the problem**
Unfortunately the repository is private, but here is the code:

Init:
```
void initNotifications(
    FlutterLocalNotificationsPlugin plugin, NotificationsRepo repo) async {
  var initSettingsAndroid = AndroidInitializationSettings("ic_launcher");
  var initSettingsIOS = IOSInitializationSettings(onDidReceiveLocalNotification:
      (int id, String title, String body, String payload) async {
    repo.postNotification(ReceivedNotification(
        id: id, title: title, body: body, payload: payload));
  });
  var initSettings =
      InitializationSettings(initSettingsAndroid, initSettingsIOS);

  await plugin.initialize(initSettings,
      onSelectNotification: (String payload) async {
    if (payload != null) {
      debugPrint('notification payload: ' + payload);
    }
  });
}
```
Show:
```
  void _showNotification() {
    _notificationsRepo.postNotification(ReceivedNotification(
        id: 1, body: "body", title: "title", payload: "payload")); // Ignoring these params for now
  }
```
Repo:
```
  @override
  void postNotification(ReceivedNotification notification) {
    var androidDetails = AndroidNotificationDetails(
        'your channel id', 'your channel name', 'your channel description',
        importance: Importance.Max, priority: Priority.High, ticker: 'ticker'
//      icon: "ic_launcher" <-- Un-commenting this fixes the issue
    );
    var iOSDetails = IOSNotificationDetails();
    var notificationDetails = NotificationDetails(androidDetails, iOSDetails);
    showNotification(notificationDetails);
  }

  void showNotification(NotificationDetails notificationDetails) async {
    await _notificationsPlugin.show(
        0, 'plain title', 'plain body', notificationDetails,
        payload: 'item x');
  }
```

I'd love to open a PR to help fix this but I'm a bit new to Flutter so was unable to follow the code path regarding initializing the Android side. Based on the stack I was able to see where the issue exists in the java portion of code, and it does look like an issue with recognizing the default icon.

**Comment by MaikuB** [comment] 2019-12-22 02:50
There's an example app in this repo and calling `show` works fine. Looking at the example you've given, I think looks more like an problem with using the `ic_launcher` mipmap as opposed to a drawable. Heard of a similar case recently so I think I'll need to remove any mention of using the mipmap

**Comment by btrautmann** [comment] 2019-12-22 02:53
In my project the `ic_launcher` png lives in the drawable directory just like in the example project.

**Comment by btrautmann** [comment] 2019-12-22 02:55
Also if that were the issue, it wouldn't work when passing the name to `show` either.

**Comment by MaikuB** [comment] 2019-12-22 03:00
I think you'll need to create an example repo that reproduces this problem and link to it. I don't anyone in the community to link to their private projects. I wonder if you happen to have a `ic_launcher` mipmap as well that is causing issues with the icon being located

**Comment by MaikuB** [comment] 2019-12-22 08:00
Looking a bit more at the stack trace and the code you've shown, it would seem like the default icon hasn't been set yet. If you're not able to provide an example to reproduce the problem then I'd suggest you debug your code as it would imply that `show` is being called before `initialize` is done. If there was an issue, I would have expected to have been to have been raised a long time ago as this is one of the most basic use cases. I can at least see a code smell where `initialize` is asynchronous but the method you wrote (`initNotification`) is synchronous and thus wouldn't get awaited before calling `show`

**Comment by btrautmann** [comment] 2019-12-22 13:56
That's very possible. Let me take a peek and get back to you. If that is the case I'll close. Thanks!

**Comment by MaikuB** [comment] 2020-01-10 06:37
Closing due to lack of further response. Feel free to reopen if you have more info

**Closed by MaikuB** 2020-01-10 06:37 UTC
