### ISSUE TITLE
Support for Actions button on schedule Notifications

### ISSUE THREAD

**Issue by iCueto** [MaikuB/flutter_local_notifications#274] opened 2019-07-25 02:53 UTC

**Comment by MaikuB** [comment] 2019-07-25 21:06
At a more general level this seems to be a duplicate of https://github.com/MaikuB/flutter_local_notifications/issues/17. As such I'll be closing this unless you're able to add more details since a description hasn't been provided

**Closed by MaikuB** 2019-07-25 21:06 UTC
