### ISSUE TITLE
 FlutterLocalNotificationsPlugin().cancel(id); is not working

### ISSUE THREAD

**Issue by DishitaShah** [MaikuB/flutter_local_notifications#1220] opened 2021-07-02 07:24 UTC
**Describe the bug**

**To Reproduce**
You must include steps to reproduce the problem
1. Send the 2-3 chat notification to a particular user (A) with say id = 100
2. Send 1-2 notifications to another user (B) with say id = 200
3. Now click on the notification of user A. It should cancel all the other notifications of user A. But id does not do that it android.
4. It removes all the notifications of user (A) and (B) in iOS
Note:  Recieved the notifications when the app is in background / killed.

**Expected behavior**
It should clear all the notifications of user **A** with id = 100 with  FlutterLocalNotificationsPlugin().cancel(id) when clicked on user **A** notification 

It should not clear all the notifications of user **B** with id = 200 with  FlutterLocalNotificationsPlugin().cancel(100) when clicked on user **A** notification 
**Sample code to reproduce the problem**

flutterLocalNotificationsPlugin.show(
      id,
      title,
      body,
      platformChannelSpecifics,
      payload: payload,
    );

 FlutterLocalNotificationsPlugin().cancel(id);

**Comment by MaikuB** [comment] 2021-07-02 08:25
Can you include a link to a repository containing a minimal app that can reproduce the bug? You could fork the repository and modify the example app as a way of doing so and provide a link to the appropriate branch in your fork

**Comment by MaikuB** [comment] 2021-07-17 23:14
Closing due to lack of further response with a minimal app that can reproduce the reported issue. Feel free to reopen if can provide it

**Closed by MaikuB** 2021-07-17 23:14 UTC

**Comment by xwanlion** [comment] 2022-07-15 08:31
NOTE：
os: android 11 (emulated device)
IDE: android studio
flutter_local_notification version：^9.1.5

**Comment by xwanlion** [comment] 2022-07-15 08:34
CODE:

static Future<bool> cancel(int id) async {
    await _notifications.cancel(id);
    return true;
  }
  

  static Future<void> notify(int id, String title, String content, DateTime at, DateTimeComponents interval) async {
    NotificationDetails platform = _getDetails();
    var zTime = DateTimeUtils.toTime(at);
    await _notifications.zonedSchedule(
        id, title, content, zTime, platform,
        uiLocalNotificationDateInterpretation: UILocalNotificationDateInterpretation.absoluteTime,
        androidAllowWhileIdle: true,
        payload: _payload,
        matchDateTimeComponents: interval);
  }

  static NotificationDetails _getDetails() {
    const android = AndroidNotificationDetails(_channelId, _channelName);
    const iOS = IOSNotificationDetails();
    const linux = LinuxNotificationDetails();
    const mac = MacOSNotificationDetails();
    return const NotificationDetails(android: android, iOS: iOS, linux: linux, macOS: mac);
  }


  static Future<void> init() async {
    _notifications = FlutterLocalNotificationsPlugin();
    var android = const AndroidInitializationSettings('@mipmap/ic_launcher');
    var iOS = const IOSInitializationSettings();
    var linux = const LinuxInitializationSettings(defaultActionName: "TodoLine++");
    var mac = const MacOSInitializationSettings();
    var settings = InitializationSettings(android: android, iOS: iOS, macOS: mac, linux: linux);
    await _notifications.initialize(settings, onSelectNotification: onSelectNotification);

  }

**Comment by xwanlion** [comment] 2022-07-15 09:11
sorry sir, I add notification twice

**Comment by xwanlion** [comment] 2022-07-15 09:12
sorry sir, I add notification twice
