### ISSUE TITLE
Possible daylight saving issue.

### ISSUE THREAD

**Issue by bzsolt0402** [MaikuB/flutter_local_notifications#1100] opened 2021-03-23 16:38 UTC
Hi,

I have recently found an issue while getting closer to daylight saving which will occur sunday in my timezone. 
The problem is the following: if it's 3:30 PM now and I set a notification to 2:31 PM, the notification will fire at 3:31 PM. It only affect the days before today and the current day. Every notification on the rest of the weekdays are set correctly. As I logged it out, it happens here
`while (scheduledDate.weekday != DateTime.monday) {
      scheduledDate = scheduledDate.add(const Duration(days: 1));
}`
For more specific representation:
Today I set the alarm for sunday, tuesday, thursday and friday to 2:31 PM and currently it's 3:30 PM. It will set sunday and tuesday to 3:31 PM and thursday and friday to 2:31 PM.

My question is that is in an issue or am I missing something?
Thank you for your response.

**Comment by MaikuB** [comment] 2021-03-24 12:12
Hopefully, you're using  the `zonedSchedule` method not the deprecated methods as the former should respect the timezone even if daylight savings occurs. The only other thing I can think of a logic issue within your application as if there issues with daylight savings, and there were in the past, then it would be at the time it occurs. No one has reported issues similar to what you've described either.

If you are indeed using the `zonedSchedule` method then should be possible to create a minimal app that can reproduce the problem whilst specifying the timezone you were using

**Comment by bzsolt0402** [comment] 2021-03-24 14:36
I am configuring the current timezone in the following way
```
Future<void> configureLocalTimeZone() async {
    tz.initializeTimeZones();
    final String currentTimeZone = await platform.invokeMethod('getTimeZoneName');
    tz.setLocalLocation(tz.getLocation(currentTimeZone));
}
```
This sets the timezone to `Europe/Budapest` which is correct.

Then I follow the steps shown in the example app:

```
tz.TZDateTime _nextInstanceOfTime(int hour, int minute) {
    final tz.TZDateTime now = tz.TZDateTime.now(tz.local);
    tz.TZDateTime scheduledDate = tz.TZDateTime.local(now.year, now.month, now.day, hour, minute);
    if (scheduledDate.isBefore(now)) {
      scheduledDate = scheduledDate.add(const Duration(days: 1));
    }
    return scheduledDate;
}
```
The parameter `day` here represents the days of the week (1 = Monday, 2 = Tuesday and so on..).
```
 tz.TZDateTime _nextInstanceOfDay(int day, int hour, int minute) {
    tz.TZDateTime scheduledDate = _nextInstanceOfTime(hour, minute);
    while (scheduledDate.weekday != day) {
      scheduledDate = scheduledDate.add(const Duration(days: 1));
    }
    return scheduledDate;
}
```
The problem I ran into is that if I set a notification for 3 PM to the days before today (I'm currently in UTC+1), it will set it to 4 PM, because next week it will be UTC+2 here. But I don't want my app to notify at 4 PM if it is set for 3 PM. Is there a way to use the device's current time to fire the notification, no matter which timezone I'm in?

**Comment by bzsolt0402** [comment] 2021-03-24 17:42
I found a possible workaround.
In this loop, instead of adding a day, which is not always represents exactly a day due to DST, I do a following.
Can you confirm that this is a solution to my problem?
```
while (scheduledDate.weekday != correctedDay) {
      // scheduledDate = scheduledDate.add(const Duration(days: 1));
      scheduledDate = tz.TZDateTime(tz.local, scheduledDate.year, scheduledDate.month, scheduledDate.day+1, scheduledDate.hour, scheduledDate.minute);
}
```

**Comment by MaikuB** [comment] 2021-03-25 09:28
I can't confirm with 100% certainty but looks like it should work. Did you debug the dates that were actually passed to the plugin? I would suspect the values match the times the notifications occur. Though, if daylight savings hasn't occurred yet then I don't how this is related to daylight savings. Based on your earlier implementation, it looks like the issue was you relied on adding a duration of a day. Dart will always treated this as as 24 hours and won't take into account daylight savings and is mentioned in the API docs [here](https://api.dart.dev/stable/2.10.5/dart-core/Duration-class.html). The new approach where the time components are specified would be more correct.

**Comment by bzsolt0402** [comment] 2021-03-25 21:17
Yes I did debugged it. And the problem is indeed adding a duration of a day. If I create a DateTime object of the current time and add like 7 days to it, when the date hits the day when the daylight saving occurs, the hours afterwards won't be the same. I think what could happen in my case is mentioned [here](https://api.dart.dev/stable/2.10.5/dart-core/DateTime/add.html).

**Comment by MaikuB** [comment] 2021-03-27 20:07
Closing this then since you've found the issue and solution

**Closed by MaikuB** 2021-03-27 20:07 UTC
