### ISSUE TITLE
Multiple entries with same notification ID in pending notifications

### ISSUE THREAD

**Issue by jongkb** [MaikuB/flutter_local_notifications#898] opened 2020-11-12 04:12 UTC
**Describe the bug**

**To Reproduce**

1. Schedule a repeating notification (e.g. matching time component i.e. daily notification) with an id 200, few minutes into the future.
2. Wait till notification is fired.
3. Two entries with notification ids 200 were returned when get pending notification requests is called.

Other observation (could be related?):
After a few days of notification firings, on rebooting, multiple notifications were fired at once. Also happens on package update.

Issue does not happen when either one of this is true: 
1. Notification id is smaller than 128
2. One-shot notification.

**Expected behavior**

1. Only one pending notification with id 200 should be returned.
2. No side effect i.e. no multiple notification firings at once on reboot/update after several notification firings.

**Plugin code causing the problem**

https://github.com/MaikuB/flutter_local_notifications/blob/4111de48bdbedab632f65ac2892159ba1d22543a/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java#L412

Suspected improper Integer equality test of notification id before saving to preferences.

**Suggested fix**

To use equals() method for Integer equality test instead.

**Comment by MaikuB** [comment] 2020-11-12 06:53
Thanks for finding this and providing the info as I was able to use this to reproduce the problem. Your suspicion is correct and I have a PR for this #899. The side effect you're seeing is due to old notifications being rescheduled and the behaviour of Android's `AlarmManager` for old scheduled work is to have them appear immediately. This should be fixed by a check that I'll add to make sure only future notifications are shown. From my testing with the example app, the PR should fix the issue. Do you think you can try out the PR/branch and let me know if it fixes the issue for you as well before I merge this in?

**Comment by jongkb** [comment] 2020-11-12 07:55
I've tested the PR/branch with my app. Works as expected now. Thank you so much for looking into this.

**Closed** 2020-11-12 08:56 UTC

**Comment by MaikuB** [comment] 2020-11-15 00:05
FYI that I'll need to revert the check for future notifications within the Android native code. There's a scenario where might be possible for a device to be off whilst the notification should appear and it should show up when the device turns on again

**Comment by jongkb** [comment] 2020-11-15 01:38
Noted on that. Thanks.
