### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.RuntimeException: Missing type parameter.

### ISSUE THREAD

**Issue by dikshantrawal** [MaikuB/flutter_local_notifications#1490] opened 2022-02-16 11:34 UTC
When I have updated the flutter version and this library version from 8.1.1 to 9.3.2. And the application is crashing only in release mode in debug mode app is not crashing.

Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver: java.lang.RuntimeException: Missing type parameter.
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3858)
       at android.app.ActivityThread.access$1500(ActivityThread.java:227)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1901)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7592)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by MaikuB** [comment] 2022-02-16 12:44
As mentioned [here](https://github.com/MaikuB/flutter_local_notifications/issues/408#issuecomment-1041454035), make sure you've done the release build configuration. If you have done so and still have an issue, please provide a link to a repository with a minimal app that can reproduce the issue

**Comment by MaikuB** [comment] 2022-03-12 23:18
Closing due to lack of further response. If you have done all the release build configuration and still have an issue, please use the bug report template and include a link to a repository that has an minimal app that can reproduce the issue

**Closed by MaikuB** 2022-03-12 23:18 UTC

**Comment by SrivastavaShubham99** [comment] 2022-07-08 11:40
I also getting this error .

================.    MANIFST FILE =========================
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.leapfrog">
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.SYSTEM_OVERLAY_WINDOW" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.ACCESS_DOWNLOAD_MANAGER" />
    <uses-permission android:name="android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" />
    <uses-permission android:name="android.permission.DISABLE_KEYGUARD" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/>
    <uses-permission android:name="android.permission.WRITE_CALENDAR" />
    <uses-permission android:name="android.permission.READ_CALENDAR" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera.autofocus" />

    <uses-permission android:name="android.permission.GET_ACCOUNTS" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
   <application
        android:label="LeapFrog Baby Care"
        android:icon="@mipmap/ic_launcher">

        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:requestLegacyExternalStorage="true"
            android:allowBackup="false"
            android:fullBackupContent="false"
            android:usesCleartextTraffic="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

       <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />
       <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">
           <intent-filter>
               <action android:name="android.intent.action.BOOT_COMPLETED"></action>
           </intent-filter>
       </receiver>
        
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />

    </application>
</manifest>




==============NOTIFICATION SERVICE=====================

import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:timezone/data/latest.dart' as tz;
import 'package:timezone/timezone.dart' as tz;


class LocalNotificationService {
  //Singleton pattern
  static final LocalNotificationService _notificationService =
  LocalNotificationService._internal();
  factory LocalNotificationService() {
    return _notificationService;
  }
  LocalNotificationService._internal();

  //instance of FlutterLocalNotificationsPlugin
  final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
  FlutterLocalNotificationsPlugin();


  Future<void> init() async {

    //Initialization Settings for Android
    const AndroidInitializationSettings initializationSettingsAndroid =
    AndroidInitializationSettings('@mipmap/ic_launcher');

    //Initialization Settings for iOS
    const IOSInitializationSettings initializationSettingsIOS =
    IOSInitializationSettings(
      requestSoundPermission: false,
      requestBadgePermission: false,
      requestAlertPermission: false,
    );

    //InitializationSettings for initializing settings for both platforms (Android & iOS)
    const InitializationSettings initializationSettings =
    InitializationSettings(
        android: initializationSettingsAndroid,
        iOS: initializationSettingsIOS);

    tz.initializeTimeZones();

    await flutterLocalNotificationsPlugin.initialize(
      initializationSettings,
    );
  }

  final AndroidNotificationDetails _androidNotificationDetails =
  const AndroidNotificationDetails(
    'channel ID',
    'channel name',
    icon: '@mipmap/ic_launcher',
    playSound: true,
    priority: Priority.high,
    importance: Importance.high,
  );

  Future<void> scheduleNotifications() async {
    await flutterLocalNotificationsPlugin.zonedSchedule(
        0,
        "Notification Title",
        "This is the Notification Body!",
        tz.TZDateTime.now(tz.local).add(const Duration(seconds: 5)),
        NotificationDetails(android: _androidNotificationDetails),
        androidAllowWhileIdle: true,
        uiLocalNotificationDateInterpretation:
        UILocalNotificationDateInterpretation.absoluteTime);
  }
}

**Comment by ubitechparth** [comment] 2022-11-28 12:21
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(error, Missing type parameter., null, java.lang.RuntimeException: Mis
sing type parameter.
E/flutter ( 1704):      at d.e.c.T.a.<init>(:3)
E/flutter ( 1704):      at com.dexterous.flutterlocalnotifications.c.<init>(Unknown Source:0)
E/flutter ( 1704):      at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.loadScheduledNotifications(Unknown Source:25)
E/flutter ( 1704):      at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.saveScheduledNotification(Unknown Source:0)
E/flutter ( 1704):      at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedScheduleNotification(Unknown Source:80)
E/flutter ( 1704):      at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.zonedSchedule(:2)
E/flutter ( 1704):      at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(Unknown Source:361)
E/flutter ( 1704):      at h.a.e.a.z.a(Unknown Source:17)
E/flutter ( 1704):      at io.flutter.embedding.engine.n.q.j(Unknown Source:11)
E/flutter ( 1704):      at io.flutter.embedding.engine.n.q.k(:1)
E/flutter ( 1704):      at io.flutter.embedding.engine.n.c.run(Unknown Source:12)
E/flutter ( 1704):      at android.os.Handler.handleCallback(Handler.java:938)
E/flutter ( 1704):      at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 1704):      at android.os.Looper.loop(Looper.java:246)
E/flutter ( 1704):      at android.app.ActivityThread.main(ActivityThread.java:8633)
E/flutter ( 1704):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 1704):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/flutter ( 1704):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/flutter ( 1704): )
E/flutter ( 1704): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607)
E/flutter ( 1704): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167)
E/flutter ( 1704): <asynchronous suspension>
E/flutter ( 1704): #2      AndroidFlutterLocalNotificationsPlugin.zonedSchedule (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:214)     
E/flutter ( 1704): <asynchronous suspension>
