### ISSUE TITLE
Schedule non recurring notification

### ISSUE THREAD

**Issue by Panthro** [MaikuB/flutter_local_notifications#87] opened 2018-08-07 11:52 UTC
HI

Right now when you schedule a notification for a specific date time it repeats every day.

I'd like to have an option to schedule a single notification, is that possible?

I'm using: 

```yaml
  flutter_local_notifications: ^0.3.6
```

**Comment by MaikuB** [comment] 2018-08-07 12:02
the `schedule` method should only show the notification at a particular date time once

**Comment by Panthro** [comment] 2018-08-07 13:42
well, that's not what's happening in my case.

It's showing every day at the same time, here's my code:

```
var scheduledNotificationDateTime = new DateTime.now().add(new Duration(hours: 1)); //TODO make it configurable
      await flutterLocalNotificationsPlugin.schedule(
          TIMER_WARN_NOTIFICATION_ID, title, body, scheduledNotificationDateTime, platformChannelSpecifics);
```

**Comment by Panthro** [comment] 2018-08-07 13:42
I'll make more tests to see if it's something on my side

**Comment by MaikuB** [comment] 2018-08-07 13:44
Are you seeing this on Android and/or iOS (include the version if you can)?

**Comment by Panthro** [comment] 2018-08-07 14:13
Android 8, haven't tried on iOS yet.

**Comment by MaikuB** [comment] 2018-08-07 22:27
I'll run another test to double check but yeah definitely have a look at your code again to see what might be going on as Android API relies on calling (this)[https://developer.android.com/reference/android/app/AlarmManager#set(int,%20long,%20android.app.PendingIntent] which will only happen once

**Comment by MaikuB** [comment] 2018-08-08 23:56
Just an update, i haven't been able to reproduce this on project app that on my Android phone. So yeah, if you could check what logic you have surrounding it then that would be good since I hadn't heard of this issue before

**Comment by MaikuB** [comment] 2018-11-10 01:30
Closing this due to lack of an update. If you still experience an issue then feel free to reopen but with your findings.

**Closed by MaikuB** 2018-11-10 01:30 UTC
