### ISSUE TITLE
Custom sound not work on Android

### ISSUE THREAD

**Issue by rrifafauzikomara** [MaikuB/flutter_local_notifications#1330] opened 2021-10-09 19:24 UTC
**Describe the bug**
I already follow the documentation but when run on Android real device / Emulator, custom sound does not work. But when run on iOS, it works.

**Expected behavior**
I already try to fix with following:
1. Uninstall and reinstall the app
2. Googling
3. Stackoverflow
4. See from your library issue about "custom sound does not work on Android"

But still does not work on Android real devices and Emulator. Even I download from (https://github.com/MaikuB/flutter_local_notifications.git) and open it (**flutter_local_notifications/flutter_local_notifications/**) in Android Studio and run it. Still does not work. Also default sound does not work on Android.

Detail:
```
Librari: flutter_local_notifications: ^9.0.0
Flutter SDK: 2.5.0
Dart SDK: 2.14.0
Emulator: Android SDK built for x86, emulator-5554, android-x86, Android 10 (API 29)
Android Real Device: Samsung Galaxy A6, Android 10 (API 29)
```

**My Code**
```dart
  Future<void> showNotification(
    DateTime dateTime,
  ) async {
    var channelId = "1";
    var channelName = "channel_01";
    var channelDescription = "alarm app channel";
    const sound = 'custom_ringtone.wav';

    var androidPlatformChannelSpecifics = AndroidNotificationDetails(
      channelId,
      channelName,
      importance: Importance.max,
      channelDescription: channelDescription,
      playSound: true,
      sound: RawResourceAndroidNotificationSound(sound.split('.').first),
      styleInformation: const DefaultStyleInformation(true, true),
    );

    var iOSPlatformChannelSpecifics = const IOSNotificationDetails(
      sound: sound,
    );

    var platformChannelSpecifics = NotificationDetails(
      android: androidPlatformChannelSpecifics,
      iOS: iOSPlatformChannelSpecifics,
    );

    final format = DateFormat('hh:mm a');
    final timeFormatted = format.format(dateTime);

    var titleNotification = "<b>Alarm</b>";
    var titleNews = 'Alarm Fire at $timeFormatted';

    await _flutterLocalNotificationsPlugin.zonedSchedule(
      0,
      titleNotification,
      titleNews,
      tz.TZDateTime.from(dateTime, tz.local),
      platformChannelSpecifics,
      androidAllowWhileIdle: true,
      uiLocalNotificationDateInterpretation:
          UILocalNotificationDateInterpretation.absoluteTime,
      payload: '1'
    );
  }
```
**My Sound Path**
```
Android: alarm_app/android/app/src/main/res/raw/custom_ringtone.wav
iOS: alarm_app/ios/Resources/custom_ringtone.wav
```

**Comment by ralphvmo** [comment] 2021-10-10 07:42
I also faced it. Don't know why

**Comment by adrianprawira** [comment] 2021-11-03 09:53
I also facing this issue, while running released version app.

**Comment by MaikuB** [comment] 2021-11-03 10:35
@adrianprawira make sure you've done the release build configuration mentioned in the readme. I tend see others not so what's mentioned in the second paragraph

https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications#release-build-configuration

**Comment by MaikuB** [comment] 2021-11-13 01:43
Closing due to lack of updates and lack of minimal example app to reproduce the problem. Please make sure to check your settings and note that there's an example app in this repository that works as expected. If you have issues with that example app even then it's indicator that you need to check your device's settings or you may even have an issue with your Android SDK installation

**Closed by MaikuB** 2021-11-13 01:43 UTC
