### ISSUE TITLE
Scheduled notifications are immediately notified on the iOS 9.3.5 device

### ISSUE THREAD

**Issue by ganessaa** [MaikuB/flutter_local_notifications#140] opened 2018-12-19 02:37 UTC
We appreciate this wonderful plug-in.

But we have one problem.

When we register scheduled notifications on iOS 9.3.5 devices, they are notified immediately without waiting for the registration date and time.

Is this a specification?

We checked the following documents.
https://pub.dartlang.org/packages/flutter_local_notifications

We copied and pasted didReceiveLocalNotification and didFinishLaunchingWithOptions code into AppDelegate.m, but these problems were not solved.

Are we doing something wrong?
We intend to check all documents.
But since we are not English native speakers.
We may be missing something.

```
$ flutter doctor -v
[✓] Flutter (Channel dev, v1.1.1, on Mac OS X 10.13.6 17G4015, locale ja)
    • Flutter version 1.1.1 at /Applications/flutter
    • Framework revision 65df90d8b5 (7 days ago), 2018-12-11 19:29:13 -0800
    • Engine revision 25b58c0c67
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/xxxxx/src/android-sdks
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/xxxxx/src/android-sdks
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • iPhone • xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx • ios • iOS 9.3.5

• No issues found!
```

**Comment by MaikuB** [comment] 2018-12-19 02:39
Does the example app behave as expected on the iOS 9.3.5 device you're using?

**Comment by ganessaa** [comment] 2018-12-19 03:11
We wanted to try it, but we have not been able to run the example app yet.
Our other projects are fine.
We do not know why flutter will not search for example ...

```
$ pwd
/Users/xxxxx/src/Flutter/example

$ flutter packages get
Running "flutter packages get" in example...
Could not find a file named "pubspec.yaml" in "/Users/xxxxx/src/Flutter".

pub get failed (66)
```

**Comment by MaikuB** [comment] 2018-12-19 03:14
I get the feeling we are not on the same page. I'm referring to the example app for this plugin. Clone the repo and run the example. Until you're able to run the example app, I can't really provide more assistance on this issue

**Comment by ganessaa** [comment] 2018-12-19 04:05
Perhaps because of our directory name you may have become confused.
We are talking about this example.
https://github.com/MaikuB/flutter_local_notifications/tree/master/example

Is not this a example of this plugin?
We have copied these codes.
/Users/xxxxx/src/Flutter/example

**Comment by MaikuB** [comment] 2018-12-19 04:11
it is an example but looking at the structure you have would imply that you didn't clone the entire repo and the error is likely happening because of that as the example app references the plugin via relative paths

**Comment by ganessaa** [comment] 2018-12-19 04:16
We understood that.
We were able to start the sample.
We will report the results later.

**Comment by ganessaa** [comment] 2018-12-19 04:57
Our operation confirmation is difficult.
This sample does not work on our device.

We executed the following command.
```
flutter clean
flutter upgrade
flutter run --release
```

The following message is displayed.
```
2018-12-19 13:52:36.092 ios-deploy[35620:2614388] [ !! ] Error 0xe8000087: This application does not support this device's CPU type. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
 6.1s
Could not install build/ios/iphoneos/Runner.app on 3e5e26829ceffd08bbc95c4fb648c401145735a0.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error running application on iPad.
```

'arm64' is set in Xcode's Architect.
We added armv7 etc, but it did not improve.

**Comment by ganessaa** [comment] 2018-12-19 05:12
We were able to run this sample application.

I ran it on iPhone 6 and was notified in 5 seconds when I pressed the "Schedule notification to appear in 5 seconds, custom sound, red color, large icon" button.

However, the same operation on iPad mini (iOS 9.3.5) was notified immediately after the button was pressed.

This is the same problem as our app.

**Comment by ganessaa** [comment] 2018-12-19 05:57
We will add information that may be helpful in investigating the problem.

In this Architectures of BuildSettings of xcodeproj which this example produces arm64 was set.
Therefore, we could not launch this on iPad mini.
We added armv7 and armv7s to it, so we could launch on the iPad mini.

However, when we try to do this on iPhone 4s, the following dialog is displayed on Xcode and it can not be executed.
```
Unable to install "Runner"
"Runner" requires the "arm64" capability which is not supported by iPhone
```

**Comment by ganessaa** [comment] 2018-12-19 06:09
We were able to run this sample application.

We ran it on iPhone 6(iOS 12.0.1) and was notified in 5 seconds when We pressed the 'Schedule notification to appear in 5 seconds, custom sound, red color, large icon' button.

However, the same operation on iPad mini (iOS 9.3.5) and iPhone 4S(iOS 9.3.5) was notified immediately after the button was pressed.

This is the same problem as our app.

**Comment by MaikuB** [comment] 2018-12-19 11:33
I personally don't have a device that has an iOS version before 10. I had borrowed a device before where from memory, the scheduling worked as expected. I had also checked before on an iOS 9.0 simulator. Given you are able to reproduce the issue, I would suggest grabbing the code for the plugin and debugging to see what is going and submit a PR if you're able to identify the issue

**Comment by ganessaa** [comment] 2018-12-19 11:38
We understood.
The incidence of this problem is 100%.
We will cooperate with the investigation.

**Comment by MaikuB** [comment] 2018-12-19 11:47
Thanks, your assistance would be greatly appreciated. You can fork the repo and submit a PR from there if you're able to identify the issue

**Comment by ganessaa** [comment] 2018-12-19 12:51
We confirmed the value of `notification.fireDate` and `[notificationDetails.secondsSinceEpoch integerValue]` near the line 426 of FlutterLocalNotificationsPlugin.m.

```
1969/12/21 04:56:01
-965039
```

We think that this is the reason to be notified immediately.

We have forgotten Objective-C as we have passed years since the development of native applications. We may need a lot of time to investigate further.

Also, the following log was output. Does this have a relationship?

```
You've implemented - [<UIApplicationDelegate> application: performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
You've implemented - [<UIApplicationDelegate> application: didReceiveRemoteNotification: fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
```

**Comment by ganessaa** [comment] 2018-12-19 13:23
We confirmed
 the value of `scheduledDate.millisecondsSinceEpoch`
 near line 131 of `flutter_local_notifications.dart`
and confirmed
 the value of `[call.arguments [MILLISECONDS_SINCE_EPOCH] integerValue]`
 near the line 185 of `FlutterLocalNotificationsPlugins.m`.

```
1545225317865
-962908695
```
Where did they change?

**Comment by ganessaa** [comment] 2018-12-19 14:06
We have found this cause.
You should not use integerValue for this value.
Therefore, this value has been lost.
When we replaced integerValue with longLongValue it worked as expected.

**Comment by ganessaa** [comment] 2018-12-19 16:08
We fixed it and made a PR.
Please check it.

**Comment by ganessaa** [comment] 2018-12-20 05:47
Our PR was closed because it was imperfect.
But we are still on this project.

**Comment by MaikuB** [comment] 2019-01-03 10:52
Closing this now as I've created a new release that includes your PR. Thanks!

**Closed by MaikuB** 2019-01-03 10:52 UTC

**Comment by ganessaa** [comment] 2019-01-04 00:11
Sorry for our late reply. 
We appreciate that you merged our PR.
