### ISSUE TITLE
delayed notifications without battery-saving mode

### ISSUE THREAD

**Issue by LucasHnz** [MaikuB/flutter_local_notifications#1312] opened 2021-09-16 21:00 UTC
i read about the alarm-manager problem in the README, but the notifications are delayed without any battery saving modes active. 

Is there a way to send exact notifications, because a timer with a variable timespan of half an hour is too much.

**Comment by MaikuB** [comment] 2021-09-17 21:37
Which API are you calling and what does that can look like? Asking to make sure you're not making use of the deprecated ones

**Comment by LucasHnz** [comment] 2021-09-20 09:09
Using:
 firebase_messaging: ^10.0.2
 flutter_local_notifications: 8.1.1
 rxdart: ^0.27.1


    import 'package:flutter_local_notifications/flutter_local_notifications.dart';
    import 'package:rxdart/rxdart.dart';
    import 'package:timezone/data/latest.dart' as tz;
    import 'package:timezone/timezone.dart' as tz;

    class LocalNotificationsApi {
     static final _notifications = FlutterLocalNotificationsPlugin();
     static final onNotifications = BehaviorSubject<String>();

    static Future showNotification({
     int id,
     String title,
     String body,
     String payload,
    }) async =>
      _notifications.show(id, title, body, await _notificationDetails(),
          payload: payload);

    static Future showScheduledNotification({
     int id,
     String title,
     String body,
     String payload,
     DateTime scheduledDate,
     }) async {
     try {
      tz.initializeTimeZones();
      _notifications.zonedSchedule(
          id,
          title,
          body,
          tz.TZDateTime.from(scheduledDate, tz.local),
          await _notificationDetails(),
          payload: payload,
          androidAllowWhileIdle: true,
          uiLocalNotificationDateInterpretation:
              UILocalNotificationDateInterpretation.absoluteTime);
     } catch (e) {}
    } 

    static Future init({bool initScheduled = false}) async {
     final android = AndroidInitializationSettings("@drawable/ic_notification");
     final iOS = IOSInitializationSettings();
     final settings = InitializationSettings(android: android, iOS: iOS);

    await _notifications.initialize(settings,
        onSelectNotification: (payload) async {
      onNotifications.add(payload);
    });
    }

    static Future _notificationDetails() async {
     return NotificationDetails(
        android: AndroidNotificationDetails("channel_local_id",
            "channel_local_name", "channel_local_description",
            importance: Importance.max,
            priority: Priority.high,
            playSound: true),
        iOS: IOSNotificationDetails());
    }

    }


Tried some more devices, on my Pixel 4 all notifications are on point, on a Samsung S20 are delays between 15 and 45 minutes.

**Comment by MaikuB** [comment] 2021-09-20 09:16
Looks like you're calling the appropriate API from the plugin. As such, you'd need to check the settings on Samsung to see what else could be turned on to get around the issue as the plugin is calling the appropriate Android APIs. I don't have a Samsung phone but I'd imagine the issue is common enough that if you a general search on the web that you can find out what options those might be

**Comment by MaikuB** [comment] 2021-10-05 10:42
Closing this this is working fine on stock Android and using the appropriate Android APIs. As I mentioned in my previous message, you'd need to look into what settings Samsung has that could get in the way and need to be changed

**Closed by MaikuB** 2021-10-05 10:42 UTC
