### ISSUE TITLE
onSelectNotification called when hot restart app

### ISSUE THREAD

**Issue by abdullah432** [MaikuB/flutter_local_notifications#575] opened 2020-04-11 09:39 UTC
**Describe the bug**
When i send first notification. After that when i close app and restart, in example code, app automatically navigate to secondpage.

**To Reproduce**
If applicable, steps to reproduce the behavior:
1. Run the example code
2. Send one notification
3. Hot restart or close and then restart
4. Application will automatically navigate to second page.

**Expected behavior**
I want to navigate to specific scroll possision when user click on notification, not when user open the app.

**Flutter doctor -v**
```
[√] Flutter (Channel master, v1.18.1-pre.2, on Microsoft Windows [Version 10.0.18363.720], locale en-PK)
    • Flutter version 1.18.1-pre.2 at C:\flutter
    • Framework revision de27d7131c (5 days ago), 2020-04-06 13:44:02 -0700
    • Engine revision df257e59c2
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 1210d27678)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\abdul\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.0)
    • VS Code at C:\Users\abdul\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.163
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

Any solution for this problem?

**Comment by MaikuB** [comment] 2020-04-11 10:09
Assuming you described all of the steps accurately, I cannot reproduce it nor has this been reported before. Perhaps something going on with your environment. Can you include the output of running `flutter doctor -v`?

**Comment by abdullah432** [comment] 2020-04-11 10:22
I add `flutter doctor -v` output. I first checked all the reported issues and shocked to not see this bug reported. It's seem like the basic thing. I don't think their is any issue with my environment but if it is then help will be appreciated. Thanks for fast response.

**Comment by MaikuB** [comment] 2020-04-11 10:23
I see you're on master, which can be in a broken state. Have you tried switching to stable?

**Comment by MaikuB** [comment] 2020-04-11 10:25
Also in case you haven't seen this, refer to the docs on the various release channels [here](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels). Master is the least stable.

**Comment by abdullah432** [comment] 2020-04-11 10:27
I changed to master because of web development. I'm now moving to stable for checking this issue. I will update you when done.

**Comment by abdullah432** [comment] 2020-04-11 11:18
Oh man it just take 30 minutes to switch. Issue remain same on stable version. I notice, problem occur only on hot restart. Not on actual restart of app. So it's very confusing until you don't notice it. 
I think issue will be same for you too. Just run example code, send one notification. click on it and then hot restart app.

**Comment by abdullah432** [comment] 2020-04-11 11:23
I know it's un-relevent from issue but need one confirmation. Does release apk file will not work without customise ProGuard configuration file?

**Comment by MaikuB** [comment] 2020-04-11 11:34
> I think issue will be same for you too. Just run example code, send one notification. click on it and then hot restart app.

Ah ok, the steps didn't mention tapping on the notification last time. I don't think there's much I can do around the hot restart issue

> I know it's un-relevent from issue but need one confirmation. Does release apk file will not work without customise ProGuard configuration file?

Yes you'll run into issues, most of them are around scheduling notifications

**Comment by abdullah432** [comment] 2020-04-11 11:41
I didn't expect, someone will reply me that fast. Thanks from the depth of my heart.

**Comment by MaikuB** [comment] 2020-04-11 11:44
No worries :)

Going to close this then

**Closed by MaikuB** 2020-04-11 11:44 UTC
