### ISSUE TITLE
In release mode, call cancel to flash back

### ISSUE THREAD

**Issue by tianshangwuyun** [MaikuB/flutter_local_notifications#433] opened 2020-01-09 09:10 UTC
why In release mode, call cancel to flash back，

**Comment by tianshangwuyun** [comment] 2020-01-09 09:11
debug mode ok

**Comment by tianshangwuyun** [comment] 2020-01-09 09:12
latest version

**Comment by MaikuB** [comment] 2020-01-09 09:13
Sorry but I don't understand what you're saying. Can you try to demonstrate using the example app?

**Comment by tianshangwuyun** [comment] 2020-01-09 09:16
release mode， when executing  await flutterLocalNotificationsPlugin.cancelAll()  method  flashes back
but debug mode ok

**Comment by MaikuB** [comment] 2020-01-09 09:22
Did you mean to say black and not back? Is this on Android or iOS?

**Comment by tianshangwuyun** [comment] 2020-01-09 09:23
I means crash  ，is on Android

**Comment by MaikuB** [comment] 2020-01-09 09:25
I suspect you need to do the setup that is mentioned around configuring the Proguard rules on Android in the readme

**Comment by tianshangwuyun** [comment] 2020-01-09 10:23
I found the reason. If the ID does not exist, cancel (ID) will report an error in release mode

**Comment by tianshangwuyun** [comment] 2020-01-09 10:23
but debug mode ok

**Comment by tianshangwuyun** [comment] 2020-01-09 10:24
maybe can before check

**Comment by MaikuB** [comment] 2020-01-09 10:28
Ok so your issue is more to do with the `cancel` method and not the `cancelAll` that you originally reported? There isn't a way to check a notification id exists so it is up to your application to check. Perhaps what is missing in your app is a try/catch block around your code?

**Comment by tianshangwuyun** [comment] 2020-01-09 10:29
thanks

**Comment by MaikuB** [comment] 2020-01-09 11:45
Going to close this then. Feel free to reopen this if you have an open or create another one

**Comment by Doflatango** [comment] 2020-01-13 13:12
Hello, i have meet the same problem here.

On Android release mode, call `cancel()` will caused a `SIGABRT` and app crash immediately(the notification id does not exist).
```dart
flutterLocalNotificationsPlugin.cancel(id);
```
and,
```
/// try...catch does not working here.
try {
    await flutterLocalNotificationsPlugin.cancel(widget.channel.id);
} catch(e){}
```

if i delete the code above, the app is working fine.

**Comment by MaikuB** [comment] 2020-01-13 20:42
Hmm ok. Sounds like plugin itself needs to catch the exception. Will reopen this. If you'd like to open a PR, I'd be happy to look at it

**Comment by MaikuB** [comment] 2020-01-15 07:33
@Doflatango forgot to mention that if you're cancelling a notification where the ID doesn't exist then there's a bug in your app that you should also investigate.

**Comment by Doflatango** [comment] 2020-01-15 08:20
@MaikuB Thanks. for your reply.
I am not good at Android development, i just wanna cancel the notification whatever the id exist or not. So, may be i should handle it in my app.

**Comment by MaikuB** [comment] 2020-01-18 01:43
I did a release build of the example app and another app with the same code to check and cannot reproduce the problem. As such as I may have to close this issue unless you can provide a fully functionally example app (with code) that can reproduce the problem. One way would be the fork the repository and use the included example app to demonstrate the problem.

**Comment by MaikuB** [comment] 2020-01-23 07:09
Closing due to lack of info to reproduce the issue

**Closed by MaikuB** 2020-01-23 07:09 UTC

**Comment by kevincherryholme** [comment] 2020-06-11 02:05
@MaikuB I have also been experiencing this issue, and I cannot find a solution or explanation.

In my app (only in release builds), the app immediately crashes when executing the statement below. The try catch does not catch any exception.

```
try {
  await flutterLocalNofiticationsPlugin.cancel(0);
} catch(e) {
  // Log Exception e
}
```


I'll provide some code directly from my app. Unfortunately, I cannot share the application. I hope this can help!

For this example, 
Tap button "Start notif.", then tap button "Update notif.", and finally tap button "Cancel notif.".
When you tap the "Cancel notif." button, the android application crashes.

```
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

class NotificationCrashExample extends StatefulWidget {
  @override
  _NotificationCrashExampleState createState() => _NotificationCrashExampleState();
}

class _NotificationCrashExampleState extends State<NotificationCrashExample> {
  FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();
  static const ChannelId = "my_channel_id";
  static const ChannelName = "my chanel name";
  static const ChannelDescription = "my chanel description";

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Row(
        children: <Widget>[
          Expanded(
            child: RaisedButton(
              onPressed: () => startOnGoingNotification(),
              child: Text("Start Notif."),
            ),
          ),
          Expanded(
            child: RaisedButton(
              onPressed: () => updateOnGoingNotification(),
              child: Text("Update Notif."),
            ),
          ),
          Expanded(
            child: RaisedButton(
              onPressed: () => cancelOnGoingNotification(),
              child: Text("Cancel Notif."),
            ),
          ),
        ],
      ),
    );
  }

  startOnGoingNotification() async {
    try {
      var androidPlatformChannelSpecifics = AndroidNotificationDetails(
        ChannelId,
        ChannelName,
        ChannelDescription,
        importance: Importance.Max,
        priority: Priority.High,
        ticker: 'some random string', // What is this?
        ongoing: true,
        playSound: true,
        autoCancel: false,
        enableVibration: true,
        onlyAlertOnce: true,
        color: Colors.red,
      );
      var iOSPlatformChannelSpecifics = IOSNotificationDetails(
        presentAlert: false,
        presentSound: false,
      );
      var platformChannelSpecifics = NotificationDetails(androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
      await flutterLocalNotificationsPlugin.show(0, "Notification title!", "just a body!", platformChannelSpecifics);
    } catch (e) {
      // Log exception
    }
  }

  updateOnGoingNotification() async {
    try {
      var androidPlatformChannelSpecifics = AndroidNotificationDetails(
        ChannelId,
        ChannelName,
        ChannelDescription,
        importance: Importance.Max,
        priority: Priority.High,
        ticker: 'some random string', // What is this?
        autoCancel: false,
        ongoing: true,
        onlyAlertOnce: true,
        color: Colors.red,
      );
      var iOSPlatformChannelSpecifics = IOSNotificationDetails(
        presentAlert: false,
        presentSound: false,
      );
      var platformChannelSpecifics = NotificationDetails(androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
      await flutterLocalNotificationsPlugin.show(0, "Notification updated!", "notification body updated!", platformChannelSpecifics);
    } catch (e) {
      // Log exception
    }
  }

  cancelOnGoingNotification() async {
    try {
      await flutterLocalNotificationsPlugin.cancel(0);
    } catch (e) {
      // Log exception
    }
  }
}

```

If you can get this code running in a release android build, tapping the cancel button will cause the application to crash.

Additionally, I do NOT use proguard for Android. I do use R8 (by default for release bundle builds).

Thank you!

**Comment by MaikuB** [comment] 2020-06-11 02:18
R8 still makes use of Proguard rules so if you didn't set them up then you'll need to do so. If you still have issues after then you'll need to stand up a complete minimal sample app that can reproduce the issue. One way is to fork the repository and update the example app. These code snippets don't help when it comes to release builds and require a complete app to look at

**Comment by kevincherryholme** [comment] 2020-06-11 02:20
Oh does it! I didn't know that. I'll look into setting up the Proguard rules. Thanks for the tip, il comment later if it fixed the issue.

**Comment by MaikuB** [comment] 2020-06-11 02:30
I would suggest you create a brand new app using the latest SDK as last I checked it generates a Proguard rules file now so will have to rules specific to Flutter apps as well. Some of these had been copied over to the rules file for the example app but it is best to check yourself in case the Flutter team has updated the rules over as the SDK has been updated

**Comment by kevincherryholme** [comment] 2020-06-11 02:54
I generated a new flutter app with the latest SDK but I don't think it generated a Proguard rules file. I am deploying a build to Google Play with the Proguard rules from your example app for now. Maybe these Proguard rules will solve the crash.

**Comment by MaikuB** [comment] 2020-06-11 03:01
Perhaps they've removed it. I'm not at my computer to check at the moment but you will need it for this plugin

**Comment by kevincherryholme** [comment] 2020-06-11 20:38
It worked! Adding the Proguard rules resolved the crash! Thanks for the help.
