### ISSUE TITLE
onDidReceiveBackgroundNotificationResponse is never called at Android

### ISSUE THREAD

**Issue by holailusoria** [MaikuB/flutter_local_notifications#2148] opened 2023-11-07 13:41 UTC
onDidReceiveBackgroundNotificationResponse is never called at Android.

**To Reproduce**
1. Initialize flutter local notification plugin.
2. Move the application to the background.
3. Send push notification
4. Tap on push notification. 
5. Logic in onDidReceiveBackgroundNotificationResponse(method as argument must have an annotation @pragma('vm:entry-point')) wasn't called.

**Expected behavior**
In step 5 described above method onDidReveiveBackgroundNotificationResponse has been called.

**Sample code to reproduce the problem**
```
final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
    FlutterLocalNotificationsPlugin();

@pragma('vm:entry-point')
void notificationTapBackground(NotificationResponse notificationResponse) {
  // ignore: avoid_print
  print('notification(${notificationResponse.id}) action tapped: '
      '${notificationResponse.actionId} with'
      ' payload: ${notificationResponse.payload}');
  if (notificationResponse.input?.isNotEmpty ?? false) {
    // ignore: avoid_print
    print(
        'notification action tapped with input: ${notificationResponse.input}');
  }
}

class test{
static initializePlugin() {
    try {
      final DarwinInitializationSettings initializationSettingsIOS =
          DarwinInitializationSettings(
              requestAlertPermission: true,
              requestBadgePermission: true,
              requestSoundPermission: true,
              onDidReceiveLocalNotification:
                  (int id, String? title, String? body, String? payload) async {
                // ignore: avoid_print
                print(
                    'Notification was receive: $title\nBody: $body\nPayload: $payload');
              });

      const AndroidInitializationSettings initializationSettingsAndroid =
          AndroidInitializationSettings('app_icon');

      final InitializationSettings initializationSettings =
          InitializationSettings(
        iOS: initializationSettingsIOS,
        android: initializationSettingsAndroid,
      );
      
      flutterLocalNotificationsPlugin.initialize(
          initializationSettings,
          onDidReceiveNotificationResponse: onDidReceiveNotificationResponse,
          onDidReceiveBackgroundNotificationResponse: notificationTapBackground,
        );
        catch (ex) {
      // ignore: avoid_print
      print('EXCEPTION: $ex');
    }
  }
}
```

**Comment by MaikuB** [comment] 2023-12-04 04:31
This is expected behaviour, this callback is for notification actions and it's documented how you should deal with when a notification is tapped. Closing as it's a duplicate of https://github.com/MaikuB/flutter_local_notifications/issues/2134

**Closed by MaikuB** 2023-12-04 04:31 UTC

**Comment by tong-k-k** [comment] 2023-12-15 07:31
May I ask then how to implement the tap on notification in background or terminated?

I do find the handling in foreground:

`onDidReceiveNotificationResponse` but this method havent been called when the app is in background or terminated.

Thanks
