### ISSUE TITLE
[MacOS] Custom notificaiton sound not working

### ISSUE THREAD

**Issue by ollyde** [MaikuB/flutter_local_notifications#1612] opened 2022-05-28 14:24 UTC
Version: ```flutter_local_notifications: ^9.5.3+1```
MacOS M1 Max
Flutter 3.0.1

<img width="296" alt="Screenshot 2022-05-28 at 16 23 02" src="https://user-images.githubusercontent.com/6940726/170829496-b561d277-bad4-43e1-961f-b0d428cb5ab3.png">
(Coped as file and added to targets)

```
 final notificationDetails = NotificationDetails(
  macOS: MacOSNotificationDetails(sound: "message_received.caf"),
  // TODO Implement sound here.
  // linux: LinuxNotificationDetails()
);

await _flutterLocalNotificationsPlugin.show(
  0,
  title,
  body,
  notificationDetails,
  payload: payload,
);
```

**Comment by MaikuB** [comment] 2022-06-04 07:45
Note I'm not a macOS developer so have you checked to see if you've done everything according to how macOS development works? I'm having trouble with my macOS setup at the moment something but I remember this was working in the example app so may be able to use that as a reference. One difference I noticed is you have the file outside the `Runner` folder. This may not make a difference as I would've thought it's treated as part of the same bundle. The example app also has configured the following when it comes to the sound file

<img width="878" alt="image" src="https://user-images.githubusercontent.com/25263378/171989955-64d48329-06de-4b2c-8d73-d974683c01b5.png">

**Comment by ollydixon** [comment] 2022-06-06 08:23
@MaikuB I tried this yes, didn't work.

**Comment by MaikuB** [comment] 2022-06-13 05:03
I was able to run the example app again and confirm it works. Have you tried the example app yourself? If it's specific to your app then you'll need to get help from the wider community to see what the issue might be

**Comment by ollydixon** [comment] 2022-06-13 06:29
> I was able to run the example app again and confirm it works. Have you tried the example app yourself? If it's specific to your app then you'll need to get help from the wider community to see what the issue might be

Hey, it still won’t work for us with sounds from push notifications. So we’ve decide to go with our own solution. There were a few other issues on MacOS and Windows as well :-)

**Comment by MaikuB** [comment] 2022-06-13 06:42
Given you said push notifications, I'm wondering if you have confused push notifications with local notifications. The former is also known as remote notifications that are triggered from a remote server. If you have confused the two, then this might explain the issue

**Comment by ollydixon** [comment] 2022-06-13 06:43
> Given you said push notifications, I'm wondering if you have confused push notifications with local notifications. The former is also known as remote notifications that are triggered from a remote server. If you have confused the two, then this might explain the issue

No we have not. We tried several solutions before going to our own. We were trying local with our own solution before going entirely to our own.

**Comment by MaikuB** [comment] 2022-06-13 06:46
Ok and your custom solution worked? If so I'm wondering what is different as I would've thought it should call the same APIs etc. I haven't seen other reports on this issue either

**Comment by ollydixon** [comment] 2022-06-13 06:50
> Ok and your custom solution worked? If so I'm wondering what is different as I would've thought it should call the same APIs etc. I haven't seen other reports on this issue either

Yes across all platforms. Even Windows with notifications send via socket and displayed using their notif api. :-) only took less than a week. 

I’m not sure, but if you clear your keychain and setup the example app to actually communicate with a fire base account and push notifications you’ll see the same keychain questions.

**Comment by MaikuB** [comment] 2022-06-13 07:24
You've mentioned Firebase and sockets so how do you know haven't confused local notifications with push notifications then? For the purpose of trying to diagnose the issue, did you try to put a button in your app and have it wired up to call the `show` method? The reason why I asked to make sure you haven't confused push notifications with local ones is I've often seen others not understand which library they're using is the one displaying notifications. if you're using something like Firebase then if you're sending notification messages, it's possible that FCM plugin is the one that displays notifications not this plugin. Using a custom sound would then require your server to include the appropriate info to request this. Using this plugin to configure the sound for local notifications has no relevance to the notification presented by FCM in this scenario

**Comment by ollydixon** [comment] 2022-06-13 07:28
@MaikuB I know the difference between package names, I have been developing on flutter for more than 3 years now, I've used both packages for many projects.

For Local notifications I had a temporary button in the UI, it was displaying the notification but no sound was playing. As I mentioned before. The sound was working on iOS, but with the exact same setup the sound did not work on MacOS (via MacOS directory and not iOS).

There is a bug with MacOS not playing sounds for local notifications.

**Comment by MaikuB** [comment] 2022-06-13 07:47
Ok. Note I was asking to double check, it wasn't meant to be condescending. 

> As I mentioned before. The sound was working on iOS, but with the exact same setup the sound did not work on MacOS (via MacOS directory and not iOS).

Thanks for the info though you haven't mentioned iOS before, the only other platform you've mentioned thus far is Windows and this plugin currently doesn't support it although there is an open PR by another community member to add Windows support

> There is a bug with MacOS not playing sounds for local notifications.

Can you confirm if you have run the example app or not? I asked earlier but push notifications was mentioned so it wasn't clear if you trying to say that you have. 

Would you also be able to help provide a link to a minimal app that can reproduce the issue? If there is indeed an issue then it would be good to try to see where the issue lies and fix it so it helps others in the community

**Comment by ollydixon** [comment] 2022-06-14 08:30
@MaikuB I don't really have time at the moment, there is still a bug from what we can see. The solution we got right now is just playing sounds manually with an audio library in the background which is sufficient for us.

**Comment by okbye123** [comment] 2023-03-17 12:21
This will help https://www.youtube.com/watch?v=aQTvI8L-mZs

**Comment by thaidmfinnick** [comment] 2023-05-18 10:42
Hi guys,
I had double check about this issue, and I've run example app. slow_spring_board @MaikuB added before, it's worked, but when I add my custom sound (copy sound to Xcode), it's not working. Can you check it again? Many thanks!

**Comment by MaikuB** [comment] 2023-05-18 10:47
You need to provide a link to a repo with that has a minimal app that can reproduce the issue

**Comment by thaidmfinnick** [comment] 2023-05-18 11:07
I copy my custom sound to your example app. You can test by coyping file sound .a
iff (not slow_spring_board) to Xcode and run. I tried many ways but it's still not working. Thanks for your response!
![Screenshot 2023-05-18 at 18 06 40](https://github.com/MaikuB/flutter_local_notifications/assets/83997264/ca35b1a1-8381-4127-9eb0-304c88f63a7d)

**Comment by MaikuB** [comment] 2023-05-18 13:17
Ok can confirm there was an issue as I didn't readd the custom sound on iOS and macOS after recreating that side of the example app. This is now fixed with the PR https://github.com/MaikuB/flutter_local_notifications/pull/2003 and it was able to play the sound. The difference from what I could tell from what's in your screenshot and what I did for the example app was to drag it to the `Resources` folder that is one level deeper. Perhaps this will fix your issue and may have fixed @ollyde's problem too. I can't recall the structure of the macOS project from way back then but perhaps how it appears now is different compared to back then so has resulted in issues

**Comment by thaidmfinnick** [comment] 2023-05-19 01:42
I will try again and give you my feedback soon. Very looking forward to this. :v. I really appreciate your help!

**Comment by thaidmfinnick** [comment] 2023-05-19 02:15
So I've copied my custom sound to Resources folder in your example app. Still doesn't work with my sound (your sound slow_spring_board works). You can see detail in 2 screenshots. If I change from `incoming.aiff` to `slow_spring_board.aiff`, your sound has played, but my sound hasn't.

I've checked with 2 Macbook (Macbook Pro M1), both don't run. Do you need any further information to discuss and fix this issue? I think problem can come from configuration as you say. Thankss!

![Screenshot 2023-05-19 at 09 01 21](https://github.com/MaikuB/flutter_local_notifications/assets/83997264/3fae765a-8d40-418e-a80e-3a457431b72c)
![Screenshot 2023-05-19 at 09 01 44](https://github.com/MaikuB/flutter_local_notifications/assets/83997264/7e739109-0439-4bd2-80dd-69a69f371713)

**Comment by MaikuB** [comment] 2023-05-19 02:25
I'd like you to fork the repo, do the steps you mentioned on the example app and provide a link to the fork you're using. Not related to this plugin but have others mentioned they've needed to reboot or uninstall and reinstall the app before custom sounds would work. Not sure if you tried that already as I had similar issues that I'm not sure is due to my laptop or a quirk of doing of macOS app development as that's not an area I have experience in

**Comment by thaidmfinnick** [comment] 2023-05-19 03:08
I try reboot first and boom, it works! I'm very glad to discuss with you in this issue. See you in somewhere issue :v.

**Comment by MaikuB** [comment] 2023-05-19 12:38
As you've confirmed it works and I've been able to do so recently then going to close. The problems experienced are outside the control of the plugin as well

**Closed by MaikuB** 2023-05-19 12:38 UTC

**Comment by michalkubizna** [comment] 2023-09-10 20:59
I am still having this issue. Was trying to run the example app but no sound was played on MacOS. Could you check if it works on your end?

**Comment by thaidmfinnick** [comment] 2024-01-04 13:47
Actually I think custom sound is not working not because of this plugin side, it maybe comes from MacOS. Sometimes it works and sometimes not, I'm still trying to figure out.

**Comment by crimesp** [comment] 2024-11-14 20:01
having issues similar to all of the above and only after a reboot it worked. my last attempt was dragging in the file into xcode into 'resources' which copies it to the root
![Screenshot 2024-11-14 at 19 54 12](https://github.com/user-attachments/assets/3ebab020-00eb-43bf-992b-c82a41c265c5)
![Screenshot 2024-11-14 at 20 01 09](https://github.com/user-attachments/assets/45f13bdb-eef4-42e0-ad68-fa9537576e15)
